import type { MealKind } from "@learn-workbench/shared";

export interface RecipeIngredient {
  name: string;
  amount: string;
}

export type RecipeTag =
  | "quick"
  | "high-protein"
  | "low-carb"
  | "high-fiber"
  | "vegetarian"
  | "fat-loss"
  | "muscle-gain"
  | "omega-3"
  | "low-calorie";

export interface Recipe {
  id: string;
  name: string;
  summary: string;
  meals: MealKind[];
  tags: RecipeTag[];
  kcal: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  prepMinutes: number;
  cookMinutes: number;
  servings: number;
  ingredients: RecipeIngredient[];
  steps: string[];
  tip?: string;
}

export const recipeTagLabels: Record<RecipeTag, string> = {
  quick: "快手",
  "high-protein": "高蛋白",
  "low-carb": "低碳水",
  "high-fiber": "高纤维",
  vegetarian: "素食友好",
  "fat-loss": "减脂",
  "muscle-gain": "增肌",
  "omega-3": "Omega-3",
  "low-calorie": "低热量",
};

/**
 * 精选家常食谱（单人份营养为估算值，用于日常记录参考，不替代医学或营养师建议）。
 * 所有数据为项目自行整理，和 `foods` 食物库互补：食物库解决“吃了多少”，
 * 食谱目录解决“今天可以怎么做”。
 */
export const recipeCatalog: Recipe[] = [
  {
    id: "banana-oat-milk",
    name: "香蕉燕麦牛奶碗",
    summary: "前一夜也能准备，适合作为高纤维早餐或训练前加餐。",
    meals: ["breakfast"],
    tags: ["quick", "high-fiber", "vegetarian"],
    kcal: 420,
    proteinG: 18,
    carbsG: 62,
    fatG: 11,
    prepMinutes: 5,
    cookMinutes: 5,
    servings: 1,
    ingredients: [
      { name: "即食燕麦", amount: "50 g" },
      { name: "低脂牛奶", amount: "250 ml" },
      { name: "香蕉", amount: "1 根" },
      { name: "奇亚籽", amount: "10 g" },
      { name: "肉桂粉", amount: "少许" },
    ],
    steps: [
      "燕麦与牛奶放入小锅，小火煮 3-5 分钟至浓稠。",
      "香蕉切片，一半拌入燕麦，一半铺在表面。",
      "撒上奇亚籽和肉桂粉；想冷吃可直接冷藏浸泡一夜。",
    ],
    tip: "乳糖不耐受可用无糖豆奶替代牛奶。",
  },
  {
    id: "tomato-egg-toast",
    name: "番茄鸡蛋全麦三明治",
    summary: "中式番茄炒蛋放进全麦吐司，蛋白质和饱腹感都更稳。",
    meals: ["breakfast"],
    tags: ["quick", "high-protein", "vegetarian"],
    kcal: 390,
    proteinG: 22,
    carbsG: 42,
    fatG: 15,
    prepMinutes: 6,
    cookMinutes: 7,
    servings: 1,
    ingredients: [
      { name: "全麦吐司", amount: "2 片" },
      { name: "鸡蛋", amount: "2 个" },
      { name: "番茄", amount: "1 个" },
      { name: "生菜", amount: "2 片" },
      { name: "橄榄油", amount: "5 g" },
    ],
    steps: [
      "番茄切块，鸡蛋打散后加少量盐。",
      "平底锅少油炒熟鸡蛋，盛出后下番茄炒软。",
      "鸡蛋回锅拌匀，夹入烤热的吐司和生菜中。",
    ],
  },
  {
    id: "purple-potato-soymilk-egg",
    name: "紫薯豆浆鸡蛋餐",
    summary: "主食、蛋白和饮品一次配齐，适合需要稳定上午精力的人。",
    meals: ["breakfast"],
    tags: ["quick", "high-protein", "high-fiber", "vegetarian"],
    kcal: 430,
    proteinG: 22,
    carbsG: 58,
    fatG: 12,
    prepMinutes: 5,
    cookMinutes: 15,
    servings: 1,
    ingredients: [
      { name: "紫薯", amount: "200 g" },
      { name: "无糖豆浆", amount: "300 ml" },
      { name: "水煮蛋", amount: "2 个" },
      { name: "小番茄", amount: "100 g" },
    ],
    steps: [
      "紫薯洗净切块，蒸锅上汽后蒸 12-15 分钟。",
      "鸡蛋可同锅蒸熟或提前煮好。",
      "紫薯、鸡蛋、小番茄装盘，搭配无糖豆浆食用。",
    ],
  },
  {
    id: "avocado-egg-toast",
    name: "牛油果鸡蛋全麦吐司",
    summary: "优质脂肪配蛋白质，适合早餐吃得少但需要扛饿的人。",
    meals: ["breakfast"],
    tags: ["quick", "high-fiber", "vegetarian"],
    kcal: 460,
    proteinG: 20,
    carbsG: 38,
    fatG: 26,
    prepMinutes: 5,
    cookMinutes: 6,
    servings: 1,
    ingredients: [
      { name: "全麦吐司", amount: "2 片" },
      { name: "牛油果", amount: "1/2 个" },
      { name: "鸡蛋", amount: "2 个" },
      { name: "柠檬汁", amount: "少许" },
      { name: "黑胡椒", amount: "少许" },
    ],
    steps: [
      "鸡蛋煮熟或煎至喜欢的熟度。",
      "牛油果压成泥，加柠檬汁和黑胡椒拌匀。",
      "牛油果泥抹在吐司上，放上鸡蛋即可。",
    ],
  },
  {
    id: "chicken-veggie-wrap",
    name: "蔬菜鸡肉卷饼",
    summary: "用全麦饼卷起鸡胸和蔬菜，适合早餐或带饭。",
    meals: ["breakfast", "lunch"],
    tags: ["quick", "high-protein", "fat-loss"],
    kcal: 420,
    proteinG: 32,
    carbsG: 38,
    fatG: 14,
    prepMinutes: 8,
    cookMinutes: 8,
    servings: 1,
    ingredients: [
      { name: "全麦卷饼", amount: "1 张" },
      { name: "鸡胸肉", amount: "100 g" },
      { name: "生菜", amount: "3 片" },
      { name: "番茄", amount: "1/2 个" },
      { name: "黄瓜", amount: "1/2 根" },
      { name: "无糖酸奶", amount: "30 g" },
    ],
    steps: [
      "鸡胸肉切条，用黑胡椒和少量盐腌 5 分钟后煎熟。",
      "蔬菜洗净切条，酸奶加少量芥末或柠檬汁做酱。",
      "卷饼铺上蔬菜、鸡肉和酸奶酱，卷紧后对半切。",
    ],
  },
  {
    id: "low-fat-cheese-fruit",
    name: "低脂奶酪水果杯",
    summary: "无需开火，适合忙碌早晨或下午加餐。",
    meals: ["breakfast", "snack"],
    tags: ["quick", "high-protein", "vegetarian"],
    kcal: 320,
    proteinG: 20,
    carbsG: 38,
    fatG: 9,
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    ingredients: [
      { name: "低脂茅屋奶酪", amount: "150 g" },
      { name: "奇异果", amount: "1 个" },
      { name: "蓝莓", amount: "80 g" },
      { name: "全麦饼干", amount: "4 片" },
    ],
    steps: [
      "奇异果去皮切丁，蓝莓洗净。",
      "奶酪放入杯中，铺上水果。",
      "搭配全麦饼干食用；可提前一晚分装冷藏。",
    ],
  },
  {
    id: "chicken-quinoa-salad",
    name: "香煎鸡胸藜麦沙拉",
    summary: "高蛋白、可带饭的经典减脂午餐。",
    meals: ["lunch"],
    tags: ["high-protein", "fat-loss", "muscle-gain"],
    kcal: 520,
    proteinG: 42,
    carbsG: 45,
    fatG: 18,
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 1,
    ingredients: [
      { name: "鸡胸肉", amount: "150 g" },
      { name: "熟藜麦", amount: "120 g" },
      { name: "混合生菜", amount: "100 g" },
      { name: "小番茄", amount: "100 g" },
      { name: "黄瓜", amount: "1/2 根" },
      { name: "橄榄油", amount: "10 g" },
    ],
    steps: [
      "鸡胸肉用盐、黑胡椒和少量蒜粉腌制 10 分钟。",
      "平底锅少油，中火将鸡胸两面煎熟后静置切片。",
      "蔬菜与藜麦装碗，放上鸡肉，淋橄榄油和柠檬汁。",
    ],
    tip: "藜麦可一次煮 3-4 份冷藏，工作日直接取用。",
  },
  {
    id: "tomato-beef-pasta",
    name: "番茄牛肉意面",
    summary: "一锅到底的碳水与蛋白组合，适合训练日午餐。",
    meals: ["lunch"],
    tags: ["high-protein", "muscle-gain"],
    kcal: 610,
    proteinG: 36,
    carbsG: 72,
    fatG: 18,
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 1,
    ingredients: [
      { name: "全麦意面（干重）", amount: "100 g" },
      { name: "瘦牛肉", amount: "120 g" },
      { name: "番茄", amount: "2 个" },
      { name: "洋葱", amount: "1/2 个" },
      { name: "橄榄油", amount: "8 g" },
    ],
    steps: [
      "意面按包装时间煮至有嚼劲，保留少量面汤。",
      "牛肉末或牛肉丝炒至变色，加入洋葱和番茄炒软。",
      "放入意面和少量面汤翻匀，用盐、黑胡椒和罗勒调味。",
    ],
  },
  {
    id: "pepper-chicken-brown-rice",
    name: "黑椒鸡腿糙米饭",
    summary: "饱腹感强，适合需要长时间专注或下午训练的人。",
    meals: ["lunch"],
    tags: ["high-protein", "muscle-gain", "high-fiber"],
    kcal: 620,
    proteinG: 38,
    carbsG: 68,
    fatG: 20,
    prepMinutes: 12,
    cookMinutes: 18,
    servings: 1,
    ingredients: [
      { name: "去皮鸡腿肉", amount: "150 g" },
      { name: "熟糙米饭", amount: "180 g" },
      { name: "西兰花", amount: "150 g" },
      { name: "胡萝卜", amount: "80 g" },
      { name: "黑胡椒汁", amount: "15 g" },
    ],
    steps: [
      "鸡腿肉切块，用黑胡椒和少量生抽腌 10 分钟。",
      "西兰花和胡萝卜焯熟或蒸熟。",
      "鸡腿肉煎熟后加入黑胡椒汁，和糙米饭、蔬菜一起装盘。",
    ],
  },
  {
    id: "steamed-sea-bass-grain-rice",
    name: "清蒸鲈鱼杂粮饭",
    summary: "清淡但蛋白质充足，适合想把午餐吃得轻一点的人。",
    meals: ["lunch"],
    tags: ["high-protein", "low-carb", "fat-loss"],
    kcal: 540,
    proteinG: 45,
    carbsG: 58,
    fatG: 14,
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 1,
    ingredients: [
      { name: "鲈鱼", amount: "180 g" },
      { name: "熟杂粮饭", amount: "150 g" },
      { name: "芦笋或小青菜", amount: "180 g" },
      { name: "姜丝", amount: "10 g" },
      { name: "蒸鱼豉油", amount: "10 ml" },
    ],
    steps: [
      "鲈鱼擦干，铺姜丝，水开后大火蒸 8-10 分钟。",
      "蔬菜焯熟，杂粮饭提前加热。",
      "鱼出锅后淋少量蒸鱼豉油，与杂粮饭、蔬菜搭配。",
    ],
  },
  {
    id: "shrimp-broccoli-fried-rice",
    name: "虾仁西兰花蛋炒饭",
    summary: "利用剩饭的高蛋白炒饭，蔬菜量足够。",
    meals: ["lunch"],
    tags: ["high-protein", "quick"],
    kcal: 560,
    proteinG: 32,
    carbsG: 65,
    fatG: 18,
    prepMinutes: 8,
    cookMinutes: 12,
    servings: 1,
    ingredients: [
      { name: "熟糙米饭", amount: "180 g" },
      { name: "虾仁", amount: "120 g" },
      { name: "鸡蛋", amount: "1 个" },
      { name: "西兰花", amount: "120 g" },
      { name: "豌豆", amount: "50 g" },
      { name: "食用油", amount: "8 g" },
    ],
    steps: [
      "虾仁用盐和黑胡椒腌 5 分钟，西兰花切小朵焯水。",
      "鸡蛋炒散盛出，虾仁炒至变色后加入米饭。",
      "加入西兰花、豌豆和鸡蛋翻匀，用少量生抽调味。",
    ],
  },
  {
    id: "shiitake-chicken-buckwheat",
    name: "香菇鸡丝荞麦面",
    summary: "汤面结构更适合秋冬，荞麦面比精制面条纤维更高。",
    meals: ["lunch", "dinner"],
    tags: ["high-protein", "high-fiber"],
    kcal: 520,
    proteinG: 34,
    carbsG: 62,
    fatG: 14,
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 1,
    ingredients: [
      { name: "荞麦面（干重）", amount: "100 g" },
      { name: "鸡胸肉", amount: "120 g" },
      { name: "鲜香菇", amount: "100 g" },
      { name: "青菜", amount: "120 g" },
      { name: "低盐鸡汤", amount: "500 ml" },
    ],
    steps: [
      "鸡胸肉切丝，用少量盐和淀粉抓匀。",
      "鸡汤煮开，加入香菇和鸡丝煮 5 分钟。",
      "下荞麦面和青菜煮熟，最后用白胡椒调味。",
    ],
  },
  {
    id: "onion-mushroom-chicken-pumpkin",
    name: "洋葱蘑菇鸡排配烤南瓜",
    summary: "鸡排、蘑菇和南瓜一盘完成，适合晚餐控制主食量。",
    meals: ["dinner"],
    tags: ["high-protein", "low-carb", "fat-loss"],
    kcal: 520,
    proteinG: 42,
    carbsG: 45,
    fatG: 18,
    prepMinutes: 12,
    cookMinutes: 25,
    servings: 1,
    ingredients: [
      { name: "鸡胸肉", amount: "160 g" },
      { name: "南瓜", amount: "200 g" },
      { name: "口蘑", amount: "120 g" },
      { name: "洋葱", amount: "1/2 个" },
      { name: "橄榄油", amount: "10 g" },
    ],
    steps: [
      "南瓜切块，拌一半橄榄油后 200℃ 烤 20-25 分钟。",
      "鸡胸拍松调味，平底锅煎至两面金黄并熟透。",
      "同一锅中炒香洋葱和口蘑，和鸡排、南瓜一起装盘。",
    ],
  },
  {
    id: "winter-melon-shrimp-tofu",
    name: "冬瓜虾仁豆腐汤配糙米",
    summary: "热量轻、蛋白足，适合晚餐或白天吃多后平衡一餐。",
    meals: ["dinner"],
    tags: ["low-calorie", "high-protein", "fat-loss"],
    kcal: 480,
    proteinG: 30,
    carbsG: 55,
    fatG: 14,
    prepMinutes: 10,
    cookMinutes: 18,
    servings: 1,
    ingredients: [
      { name: "冬瓜", amount: "250 g" },
      { name: "虾仁", amount: "100 g" },
      { name: "北豆腐", amount: "150 g" },
      { name: "熟糙米饭", amount: "120 g" },
      { name: "姜片", amount: "3 片" },
    ],
    steps: [
      "冬瓜切片，豆腐切块。",
      "锅中加水、姜片和冬瓜煮 10 分钟，加入豆腐和虾仁再煮 5 分钟。",
      "用盐和白胡椒调味，搭配加热好的糙米饭。",
    ],
  },
  {
    id: "tomato-beef-brisket-grain-rice",
    name: "番茄炖牛腩杂粮饭",
    summary: "适合提前炖一锅，分装后工作日复热。",
    meals: ["dinner"],
    tags: ["high-protein", "muscle-gain"],
    kcal: 650,
    proteinG: 38,
    carbsG: 68,
    fatG: 24,
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 1,
    ingredients: [
      { name: "瘦牛腩", amount: "150 g" },
      { name: "番茄", amount: "2 个" },
      { name: "胡萝卜", amount: "100 g" },
      { name: "熟杂粮饭", amount: "180 g" },
      { name: "洋葱", amount: "1/2 个" },
    ],
    steps: [
      "牛腩冷水下锅焯水，洗去浮沫。",
      "炒香洋葱，加入番茄和牛腩，加水没过食材。",
      "小火炖 40 分钟，加入胡萝卜再炖 10 分钟，搭配杂粮饭。",
    ],
    tip: "一次做 3-4 份，冷藏 3 天内吃完。",
  },
  {
    id: "garlic-broccoli-chicken",
    name: "蒜蓉西兰花鸡胸肉",
    summary: "十几分钟完成的高蛋白晚餐，适合减脂期。",
    meals: ["dinner"],
    tags: ["quick", "high-protein", "low-carb", "fat-loss"],
    kcal: 430,
    proteinG: 46,
    carbsG: 35,
    fatG: 14,
    prepMinutes: 8,
    cookMinutes: 12,
    servings: 1,
    ingredients: [
      { name: "鸡胸肉", amount: "160 g" },
      { name: "西兰花", amount: "250 g" },
      { name: "红薯", amount: "100 g" },
      { name: "蒜", amount: "3 瓣" },
      { name: "橄榄油", amount: "8 g" },
    ],
    steps: [
      "红薯切块蒸熟，西兰花切小朵焯水 1 分钟。",
      "鸡胸切片，用盐和黑胡椒调味后煎熟。",
      "锅中少油炒香蒜末，加入西兰花翻匀，与鸡肉和红薯装盘。",
    ],
  },
  {
    id: "salmon-avocado-salad",
    name: "三文鱼牛油果沙拉",
    summary: "补充 Omega-3 的一餐，适合不想吃厚重主食的晚上。",
    meals: ["dinner"],
    tags: ["high-protein", "omega-3", "low-carb"],
    kcal: 560,
    proteinG: 35,
    carbsG: 24,
    fatG: 35,
    prepMinutes: 10,
    cookMinutes: 12,
    servings: 1,
    ingredients: [
      { name: "三文鱼", amount: "150 g" },
      { name: "牛油果", amount: "1/2 个" },
      { name: "混合生菜", amount: "120 g" },
      { name: "熟藜麦", amount: "50 g" },
      { name: "柠檬汁", amount: "10 ml" },
    ],
    steps: [
      "三文鱼擦干，用盐和黑胡椒调味后煎至喜欢的熟度。",
      "牛油果切片，生菜洗净沥干。",
      "生菜、藜麦、牛油果装盘，放三文鱼并淋柠檬汁。",
    ],
  },
  {
    id: "pepper-beef-quinoa",
    name: "彩椒牛肉炒藜麦",
    summary: "颜色丰富，适合训练后补蛋白和碳水。",
    meals: ["dinner"],
    tags: ["high-protein", "muscle-gain"],
    kcal: 580,
    proteinG: 40,
    carbsG: 52,
    fatG: 22,
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 1,
    ingredients: [
      { name: "瘦牛肉", amount: "140 g" },
      { name: "熟藜麦", amount: "150 g" },
      { name: "红黄彩椒", amount: "150 g" },
      { name: "洋葱", amount: "1/2 个" },
      { name: "橄榄油", amount: "8 g" },
    ],
    steps: [
      "牛肉切片，用生抽、黑胡椒和少量淀粉腌 10 分钟。",
      "热锅少油快速炒牛肉，变色后盛出。",
      "炒香洋葱和彩椒，加入藜麦和牛肉翻匀调味。",
    ],
  },
  {
    id: "greek-yogurt-berry-nuts",
    name: "希腊酸奶坚果莓果杯",
    summary: "高蛋白加餐，适合下午饿但不想吃甜点的时候。",
    meals: ["snack"],
    tags: ["quick", "high-protein", "vegetarian"],
    kcal: 280,
    proteinG: 20,
    carbsG: 24,
    fatG: 12,
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    ingredients: [
      { name: "无糖希腊酸奶", amount: "200 g" },
      { name: "蓝莓", amount: "80 g" },
      { name: "杏仁", amount: "15 g" },
      { name: "南瓜籽", amount: "5 g" },
    ],
    steps: [
      "酸奶倒入杯中。",
      "铺上蓝莓、杏仁和南瓜籽。",
      "直接食用；坚果建议按份量装袋控制摄入。",
    ],
  },
  {
    id: "apple-peanut-butter-toast",
    name: "苹果花生酱全麦吐司",
    summary: "甜口但不依赖添加糖，适合训练前后补充能量。",
    meals: ["snack"],
    tags: ["quick", "vegetarian", "high-fiber"],
    kcal: 300,
    proteinG: 10,
    carbsG: 38,
    fatG: 14,
    prepMinutes: 4,
    cookMinutes: 2,
    servings: 1,
    ingredients: [
      { name: "全麦吐司", amount: "1 片" },
      { name: "苹果", amount: "1/2 个" },
      { name: "无糖花生酱", amount: "15 g" },
      { name: "肉桂粉", amount: "少许" },
    ],
    steps: [
      "吐司烤热，抹上花生酱。",
      "苹果切薄片铺在吐司上。",
      "撒少量肉桂粉即可。",
    ],
  },
  {
    id: "banana-oat-energy-balls",
    name: "香蕉燕麦能量球",
    summary: "一次做几份冷藏，运动前或下午补能量很方便。",
    meals: ["snack"],
    tags: ["vegetarian", "high-fiber"],
    kcal: 180,
    proteinG: 6,
    carbsG: 30,
    fatG: 6,
    prepMinutes: 12,
    cookMinutes: 0,
    servings: 1,
    ingredients: [
      { name: "即食燕麦", amount: "40 g" },
      { name: "香蕉", amount: "1 根" },
      { name: "无糖花生酱", amount: "10 g" },
      { name: "可可粉", amount: "5 g" },
    ],
    steps: [
      "香蕉压泥，与燕麦、花生酱和可可粉拌匀。",
      "分成 3 个小球，冷藏 30 分钟定型。",
      "每次吃 3 个，剩余密封冷藏。",
    ],
  },
  {
    id: "edamame-tofu-bites",
    name: "毛豆豆干拼盘",
    summary: "咸口高蛋白加餐，适合不想吃甜食的下午。",
    meals: ["snack"],
    tags: ["high-protein", "vegetarian", "high-fiber"],
    kcal: 260,
    proteinG: 24,
    carbsG: 20,
    fatG: 11,
    prepMinutes: 5,
    cookMinutes: 8,
    servings: 1,
    ingredients: [
      { name: "毛豆", amount: "150 g" },
      { name: "五香豆干", amount: "100 g" },
      { name: "芝麻油", amount: "3 g" },
      { name: "辣椒粉", amount: "少许" },
    ],
    steps: [
      "毛豆煮熟后捞出放凉。",
      "豆干切条，与毛豆混合。",
      "淋少量芝麻油，按口味撒辣椒粉。",
    ],
  },
  {
    id: "boiled-egg-cucumber-rolls",
    name: "水煮蛋黄瓜卷",
    summary: "低碳水、准备快的咸口加餐。",
    meals: ["snack"],
    tags: ["quick", "low-carb", "high-protein"],
    kcal: 180,
    proteinG: 14,
    carbsG: 8,
    fatG: 10,
    prepMinutes: 6,
    cookMinutes: 10,
    servings: 1,
    ingredients: [
      { name: "鸡蛋", amount: "2 个" },
      { name: "黄瓜", amount: "1 根" },
      { name: "无糖酸奶", amount: "20 g" },
      { name: "黄芥末", amount: "3 g" },
    ],
    steps: [
      "鸡蛋冷水下锅，水开后煮 8 分钟，过凉后去壳。",
      "黄瓜用削皮器削成长片。",
      "鸡蛋切块，用黄瓜片卷起，搭配酸奶芥末酱。",
    ],
  },
  {
    id: "cottage-cheese-fruit-cup",
    name: "茅屋奶酪奇亚籽水果杯",
    summary: "蛋白质高、糖分低，适合作为晚间轻加餐。",
    meals: ["snack"],
    tags: ["quick", "high-protein", "vegetarian", "fat-loss"],
    kcal: 250,
    proteinG: 22,
    carbsG: 26,
    fatG: 6,
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    ingredients: [
      { name: "低脂茅屋奶酪", amount: "150 g" },
      { name: "奇异果", amount: "1 个" },
      { name: "草莓", amount: "100 g" },
      { name: "奇亚籽", amount: "8 g" },
    ],
    steps: [
      "水果洗净切块。",
      "奶酪放入杯中，铺上水果。",
      "撒奇亚籽，静置 5 分钟让口感更浓稠。",
    ],
  },
];

export function recipesForMeal(meal: MealKind, limit = 6): Recipe[] {
  return recipeCatalog.filter((recipe) => recipe.meals.includes(meal)).slice(0, limit);
}

export function recipeById(id: string): Recipe | null {
  return recipeCatalog.find((recipe) => recipe.id === id) ?? null;
}
