import { judgeQuestion, singleQuestion } from "./question-builders";
import type { LearningTrack } from "./types";

export const aiEngineeringTrack: LearningTrack = {
  slug: "ai-engineering",
  title: "AI 应用工程",
  category: "人工智能",
  level: "进阶",
  accent: "#7357C8",
  softAccent: "#F0ECFC",
  icon: "sparkles-outline",
  summary: "从模型基础、RAG 和 Agent 到评测、安全与成本治理，建立可上线的 AI 应用工程能力。",
  whyLearn: "AI 应用的核心竞争力不只是调用模型，而是把检索、工具、状态、评测和安全组织成可靠产品。",
  prerequisites: ["掌握 Python 或 JavaScript", "理解 HTTP API、JSON 和基础数据库概念"],
  studyMethod: ["先做最小闭环再扩展能力", "每个 Prompt 或模型改动都配评测样例", "把失败样本、成本和延迟作为一等工程指标"],
  estimatedHours: 104,
  featured: true,
  sources: [
    {
      key: "microsoft-generative-ai",
      name: "Generative AI for Beginners",
      url: "https://github.com/microsoft/generative-ai-for-beginners",
      license: "MIT",
      usage: "import",
      note: "生成式 AI 课程结构、RAG 和应用安全主题",
    },
    {
      key: "openai-cookbook",
      name: "OpenAI Cookbook",
      url: "https://github.com/openai/openai-cookbook",
      license: "MIT",
      usage: "import",
      note: "结构化输出、检索、评测和工程实践示例",
    },
    {
      key: "langgraph",
      name: "LangGraph",
      url: "https://github.com/langchain-ai/langgraph",
      license: "MIT",
      usage: "import",
      note: "有状态 Agent、工作流和人工确认节点",
    },
  ],
  stages: [
    {
      key: "ai-foundations",
      title: "模型、提示与数据结构",
      weeks: "第 1-3 周",
      goal: "理解 token、上下文、提示边界、结构化输出和向量表示。",
      outcome: "完成一个带结构校验、错误恢复和成本记录的模型调用模块。",
      topics: [
        {
          key: "ai-model-basics",
          title: "模型输入与上下文",
          summary: "token、上下文窗口、采样参数、系统提示和模型边界。",
          concepts: ["token", "上下文窗口", "温度与采样", "系统与用户消息"],
          principles: ["模型按 token 处理上下文，窗口限制同时约束输入和输出", "生成结果是概率输出，不等于事实数据库"],
          applications: ["文本生成", "分类抽取", "对话助手"],
          pitfalls: ["把上下文长度等同于可靠记忆", "依赖温度解决事实错误"],
          method: "先定义输入输出和失败方式，再选择模型与参数。",
          exercise: "实现带超时、重试和 token 统计的模型调用封装。",
          checkpoint: "能解释输入长度、输出质量、延迟和成本之间的关系。",
        },
        {
          key: "ai-prompt-output",
          title: "提示与结构化输出",
          summary: "任务说明、示例、约束、JSON Schema 和校验。",
          concepts: ["指令层次", "少样本示例", "JSON Schema", "失败重试"],
          principles: ["提示应明确角色、任务、输入、约束和输出格式", "结构输出必须经过程序校验，不能只相信模型格式"],
          applications: ["信息抽取", "工单分类", "多步骤规划"],
          pitfalls: ["提示同时包含冲突规则", "把模型返回文本直接执行"],
          method: "先用一个最小样例稳定输出，再逐步增加边界和异常输入。",
          exercise: "实现工单分类器的结构化输出和失败重试。",
          checkpoint: "非法格式会被拦截，错误原因可定位并可重试。",
        },
        {
          key: "ai-embeddings",
          title: "向量与语义表示",
          summary: "嵌入、相似度、索引、维度和语义检索边界。",
          concepts: ["embedding", "余弦相似度", "向量索引", "语义漂移"],
          principles: ["向量表示可计算语义接近度，但不保证业务相关性", "索引和切分方式会直接改变检索结果"],
          applications: ["相似搜索", "去重", "候选召回"],
          pitfalls: ["把相似度分数直接当作答案质量", "不同模型生成的向量混用"],
          method: "固定嵌入模型与数据版本，用标注查询验证召回效果。",
          exercise: "为一组技术文档建立向量索引并评估 Top 5 召回。",
          checkpoint: "能说明召回失败来自切分、模型还是查询表达。",
        },
      ],
      questionKeys: ["ai-q1", "ai-q2", "ai-q3", "ai-q4"],
    },
    {
      key: "ai-rag",
      title: "RAG、检索与评测",
      weeks: "第 4-6 周",
      goal: "构建从文档切分、检索到带引用回答的完整 RAG 闭环。",
      outcome: "交付一个可引用来源、可评测、可定位失败环节的 RAG 应用。",
      topics: [
        {
          key: "ai-chunking",
          title: "文档切分与索引",
          summary: "语义切分、元数据、去重、版本和增量更新。",
          concepts: ["chunk", "重叠窗口", "元数据", "增量索引"],
          principles: ["切分应尽量保持完整语义单元并保留来源定位", "索引必须与文档版本一致"],
          applications: ["知识库", "帮助中心", "技术文档"],
          pitfalls: ["仅按固定字数切断表格或代码", "文档更新后索引未同步"],
          method: "先分析内容结构，再选择标题、段落或语义切分策略。",
          exercise: "为 Markdown 文档实现带标题路径和版本的切分器。",
          checkpoint: "每个片段都能回到原文位置，更新和删除不会留下旧内容。",
        },
        {
          key: "ai-retrieval-generation",
          title: "检索与回答生成",
          summary: "查询改写、混合检索、重排、上下文组装和引用。",
          concepts: ["关键词检索", "向量检索", "重排", "引用"],
          principles: ["检索负责找到证据，生成负责组织和表达证据", "回答范围应受上下文证据约束"],
          applications: ["企业问答", "政策检索", "研发助手"],
          pitfalls: ["把所有召回片段直接塞进上下文", "回答没有来源或引用错误"],
          method: "分别评估召回和生成，再把失败样本回填到检索策略。",
          exercise: "实现混合检索、重排和带原文引用的回答接口。",
          checkpoint: "回答中的关键结论都能定位到被检索来源。",
        },
        {
          key: "ai-rag-eval",
          title: "RAG 评测与失败归因",
          summary: "测试集、召回率、忠实度、答案覆盖、人工复核和回归。",
          concepts: ["评测集", "召回率", "忠实度", "回归"],
          principles: ["评测集应覆盖真实问题和困难边界", "检索失败和生成失败必须分开统计"],
          applications: ["版本发布", "Prompt 调整", "模型替换"],
          pitfalls: ["只用几个顺利样例判断效果", "自动评分替代全部人工复核"],
          method: "建立固定问题集和评分口径，每次变更都跑同一基线。",
          exercise: "建立 30 条 RAG 评测样例并定位两类主要失败。",
          checkpoint: "能说明改动提升了什么、牺牲了什么以及剩余风险。",
        },
      ],
      questionKeys: ["ai-q5", "ai-q6", "ai-q7", "ai-q8"],
    },
    {
      key: "ai-agent",
      title: "工具调用、Agent 与协议",
      weeks: "第 7-9 周",
      goal: "掌握工具定义、状态机、循环控制、人工确认和多 Agent 边界。",
      outcome: "完成一个具备工具调用、状态恢复、权限控制和失败回退的 Agent。",
      topics: [
        {
          key: "ai-tools",
          title: "工具与函数调用",
          summary: "工具 schema、参数校验、结果封装、权限和幂等。",
          concepts: ["function calling", "参数校验", "工具结果", "幂等键"],
          principles: ["工具是外部世界边界，所有输入输出都必须校验", "高风险动作需要权限和人工确认"],
          applications: ["查询系统", "创建工单", "数据分析"],
          pitfalls: ["让模型直接拼 SQL 或 Shell", "工具失败信息过度暴露"],
          method: "先定义工具契约和权限，再写模型调用与错误映射。",
          exercise: "实现只读查询和需确认写操作两类工具。",
          checkpoint: "越权参数被拒绝，重复调用不会产生重复副作用。",
        },
        {
          key: "ai-agent-loop",
          title: "Agent 循环与状态",
          summary: "观察、思考、行动循环，最大步数、状态持久化和中断恢复。",
          concepts: ["agent loop", "状态机", "检查点", "人工确认"],
          principles: ["Agent 必须有终止条件和预算", "状态应可序列化，才能恢复和审计"],
          applications: ["多步检索", "任务自动化", "异常处理"],
          pitfalls: ["无限循环调用工具", "把全部中间状态只留在内存"],
          method: "先画状态转移，再实现节点、条件边和失败出口。",
          exercise: "用状态机实现带最大步数和人工确认的工单处理流程。",
          checkpoint: "流程可暂停、恢复和审计，且不会无限执行。",
        },
        {
          key: "ai-multi-agent",
          title: "多 Agent 与协议",
          summary: "角色拆分、协作边界、消息协议、MCP 和共享上下文。",
          concepts: ["角色分工", "消息协议", "MCP", "共享状态"],
          principles: ["多 Agent 应解决明确的分工问题，而不是为了数量而拆分", "协议和权限决定系统边界"],
          applications: ["研究写作", "代码审查", "复杂运营流程"],
          pitfalls: ["角色提示互相冲突", "多个 Agent 重复执行同一工具"],
          method: "先验证单 Agent 上限，再按能力或权限拆分角色。",
          exercise: "实现规划、检索、审校三个角色并限制共享工具。",
          checkpoint: "每个角色职责和输入输出明确，总成本与失败路径可追踪。",
        },
      ],
      questionKeys: ["ai-q9", "ai-q10", "ai-q11", "ai-q12"],
    },
    {
      key: "ai-production",
      title: "上线、评测、安全与成本",
      weeks: "第 10-12 周",
      goal: "把 AI 功能做成可观测、可回归、可控成本和合规的生产系统。",
      outcome: "交付一套带评测门禁、trace、降级、安全和成本预算的 AI 服务。",
      topics: [
        {
          key: "ai-observability",
          title: "可观测性与评测门禁",
          summary: "请求 trace、模型版本、延迟、成本、错误和离线回归。",
          concepts: ["trace", "黄金集", "延迟分位数", "成本归因"],
          principles: ["线上问题需要能还原请求、模型、检索和工具链路", "发布门禁应同时约束质量、延迟、成本和错误率"],
          applications: ["灰度发布", "模型替换", "故障定位"],
          pitfalls: ["只记录最终文本不记录上下文版本", "只看平均延迟"],
          method: "先定义关键指标和采样策略，再接入 trace 与发布门禁。",
          exercise: "为 AI 服务建立 trace 字段、成本指标和 20 条回归集。",
          checkpoint: "任一线上回答都能还原使用的数据、模型和工具路径。",
        },
        {
          key: "ai-safety",
          title: "安全、权限与内容边界",
          summary: "提示注入、数据泄露、越权工具、输出过滤和人工兜底。",
          concepts: ["提示注入", "最小权限", "输出校验", "人工兜底"],
          principles: ["不可信内容不能获得系统指令级权限", "安全控制应放在可执行边界而不是只写在提示里"],
          applications: ["企业知识库", "客服", "自动化操作"],
          pitfalls: ["把用户文档直接拼接进系统提示", "依赖模型自己决定是否越权"],
          method: "识别信任边界，对输入、检索内容、工具参数和输出分别校验。",
          exercise: "为 RAG + 工具 Agent 做一次提示注入和越权测试。",
          checkpoint: "高风险动作始终经过独立授权与确认。",
        },
        {
          key: "ai-cost-reliability",
          title: "成本、可靠性与治理",
          summary: "缓存、模型路由、限流、降级、隐私和数据保留。",
          concepts: ["模型路由", "缓存", "限流", "数据保留"],
          principles: ["不同任务可使用不同成本和能力等级的模型", "可靠系统应设计超时、降级和人工接管"],
          applications: ["高频问答", "批量抽取", "内部助手"],
          pitfalls: ["所有请求都使用最贵模型", "高峰时没有限流和排队策略"],
          method: "按任务价值和风险分层，再配置模型、缓存与降级路径。",
          exercise: "为问答服务设计低成本、标准和高可靠三种执行路径。",
          checkpoint: "成本有预算和归因，依赖故障时核心流程仍可降级运行。",
        },
      ],
      questionKeys: ["ai-q13", "ai-q14", "ai-q15", "ai-q16"],
    },
  ],
  questions: [
    singleQuestion({
      key: "ai-q1",
      stageKey: "ai-foundations",
      stem: "上下文窗口主要限制什么？",
      options: ["模型文件大小", "一次请求可处理的 token 总量", "用户数量", "数据库连接数"],
      answer: "B",
      explanation: "上下文窗口约束输入、输出和中间内容可使用的 token 总量。",
      difficulty: "easy",
      tags: ["上下文", "token"],
      sourceKey: "microsoft-generative-ai",
    }),
    judgeQuestion({
      key: "ai-q2",
      stageKey: "ai-foundations",
      stem: "降低 temperature 可以从根本上保证模型输出事实正确。",
      answer: false,
      explanation: "较低温度通常减少随机性，但无法修复知识缺失、错误来源或推理错误。",
      difficulty: "easy",
      tags: ["采样", "事实性"],
      sourceKey: "openai-cookbook",
    }),
    singleQuestion({
      key: "ai-q3",
      stageKey: "ai-foundations",
      stem: "模型返回 JSON 后，最稳妥的工程处理是什么？",
      options: ["直接写入数据库", "使用 Schema 解析校验后再处理", "只检查大括号", "截取第一行"],
      answer: "B",
      explanation: "结构校验能拦截缺字段、类型错误和非法枚举，并触发重试或人工处理。",
      difficulty: "easy",
      tags: ["结构化输出", "校验"],
      sourceKey: "openai-cookbook",
    }),
    judgeQuestion({
      key: "ai-q4",
      stageKey: "ai-foundations",
      stem: "不同嵌入模型生成的向量通常可以直接混用并比较相似度。",
      answer: false,
      explanation: "不同模型的向量空间不保证兼容，混用会导致相似度失去稳定含义。",
      difficulty: "medium",
      tags: ["embedding", "向量"],
      sourceKey: "openai-cookbook",
    }),
    singleQuestion({
      key: "ai-q5",
      stageKey: "ai-rag",
      stem: "RAG 文档切分最重要的质量目标之一是什么？",
      options: ["每段长度完全一样", "保留完整语义并支持来源定位", "全部转成小写", "删除标题"],
      answer: "B",
      explanation: "片段既要包含可独立理解的语义，也要保留文档位置和版本，便于引用与更新。",
      difficulty: "medium",
      tags: ["RAG", "切分"],
      sourceKey: "microsoft-generative-ai",
    }),
    singleQuestion({
      key: "ai-q6",
      stageKey: "ai-rag",
      stem: "混合检索通常组合哪两类信号？",
      options: ["关键词和向量相似度", "字体和颜色", "CPU 和内存", "语音和视频"],
      answer: "A",
      explanation: "关键词检索擅长精确术语，向量检索擅长语义接近，组合后通常更稳健。",
      difficulty: "medium",
      tags: ["检索", "混合搜索"],
      sourceKey: "microsoft-generative-ai",
    }),
    judgeQuestion({
      key: "ai-q7",
      stageKey: "ai-rag",
      stem: "RAG 系统回答错误时，应把检索失败和生成失败分开统计。",
      answer: true,
      explanation: "分开统计才能判断应该改切分、召回、重排还是提示和生成策略。",
      difficulty: "medium",
      tags: ["RAG", "评测"],
      sourceKey: "openai-cookbook",
    }),
    singleQuestion({
      key: "ai-q8",
      stageKey: "ai-rag",
      stem: "提高 RAG 可追溯性最直接的做法是什么？",
      options: ["删除来源", "在回答中引用检索片段和原文位置", "增加 temperature", "缩短上下文"],
      answer: "B",
      explanation: "带来源引用能让用户核查结论，也便于开发者定位错误证据。",
      difficulty: "easy",
      tags: ["引用", "可追溯"],
      sourceKey: "microsoft-generative-ai",
    }),
    singleQuestion({
      key: "ai-q9",
      stageKey: "ai-agent",
      stem: "工具调用的参数为什么必须在执行前校验？",
      options: ["为了增加动画", "防止模型产生非法或越权操作", "为了减少文字", "为了改变颜色"],
      answer: "B",
      explanation: "模型参数不可信，工具边界必须校验类型、范围、资源和权限。",
      difficulty: "easy",
      tags: ["工具调用", "校验"],
      sourceKey: "openai-cookbook",
    }),
    judgeQuestion({
      key: "ai-q10",
      stageKey: "ai-agent",
      stem: "Agent 循环应设置最大步数、超时或成本预算中的至少一种终止条件。",
      answer: true,
      explanation: "终止预算可防止循环、工具故障或错误规划导致无限执行和成本失控。",
      difficulty: "easy",
      tags: ["Agent", "预算"],
      sourceKey: "langgraph",
    }),
    singleQuestion({
      key: "ai-q11",
      stageKey: "ai-agent",
      stem: "什么情况下适合把单 Agent 拆成多 Agent？",
      options: ["只要能多创建几个角色", "存在明确的能力、权限或审校分工", "为了让日志更长", "为了减少测试"],
      answer: "B",
      explanation: "多 Agent 的价值来自清晰分工和边界，而不是角色数量。",
      difficulty: "medium",
      tags: ["多 Agent", "架构"],
      sourceKey: "microsoft-generative-ai",
    }),
    singleQuestion({
      key: "ai-q12",
      stageKey: "ai-agent",
      stem: "有状态 Agent 适合用什么方式实现暂停和恢复？",
      options: ["只保存在浏览器变量", "可序列化状态和检查点", "随机重试", "关闭日志"],
      answer: "B",
      explanation: "可序列化状态和检查点让流程能暂停、恢复、审计和从失败节点重启。",
      difficulty: "medium",
      tags: ["状态", "LangGraph"],
      sourceKey: "langgraph",
    }),
    singleQuestion({
      key: "ai-q13",
      stageKey: "ai-production",
      stem: "AI 请求 trace 最需要串起哪些信息？",
      options: ["模型、Prompt、检索、工具、成本和结果", "只记录最终文本", "只记录用户头像", "只记录按钮颜色"],
      answer: "A",
      explanation: "完整链路记录能还原一次回答使用的数据和计算路径，支持评测与排障。",
      difficulty: "medium",
      tags: ["trace", "可观测性"],
      sourceKey: "openai-cookbook",
    }),
    judgeQuestion({
      key: "ai-q14",
      stageKey: "ai-production",
      stem: "只要系统提示写了“不要泄露数据”，就不需要工具权限控制。",
      answer: false,
      explanation: "提示不是安全边界，必须通过权限、参数校验、数据隔离和人工确认实施控制。",
      difficulty: "easy",
      tags: ["安全", "权限"],
      sourceKey: "microsoft-generative-ai",
    }),
    singleQuestion({
      key: "ai-q15",
      stageKey: "ai-production",
      stem: "控制 AI 应用成本最合理的思路是什么？",
      options: ["所有请求都用最大模型", "按任务价值与风险分层选择模型和降级路径", "关闭监控", "删除缓存"],
      answer: "B",
      explanation: "不同任务需要不同能力等级，模型路由、缓存和降级能在质量与成本间取得平衡。",
      difficulty: "medium",
      tags: ["成本", "模型路由"],
      sourceKey: "openai-cookbook",
    }),
    singleQuestion({
      key: "ai-q16",
      stageKey: "ai-production",
      stem: "AI 服务依赖故障时，最可靠的产品策略是什么？",
      options: ["无限等待", "超时、降级或转人工", "返回伪造答案", "关闭错误日志"],
      answer: "B",
      explanation: "明确超时、缓存降级和人工接管能让核心流程在依赖异常时保持可用和可信。",
      difficulty: "easy",
      tags: ["可靠性", "降级"],
      sourceKey: "langgraph",
    }),
  ],
};
