import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

const complexityQuestions = [
  ...topicQuestionPair(
    "algo-complexity-basics",
    "algo-complexity",
    {
      stem: "一段代码对长度为 n 的数组做双重循环，每次内层循环都从头遍历一遍，其时间复杂度是？",
      options: ["O(n)", "O(n log n)", "O(n²)", "O(2^n)"],
      answer: "C",
      explanation: "外层 n 次、内层 n 次的嵌套循环，基本操作执行次数与 n² 成正比，因此是 O(n²)。",
      difficulty: "easy",
      tags: ["复杂度", "大O"],
      sourceKey: "algorithms-python",
    },
    {
      stem: "大 O 记法描述的是算法执行时间的上界，忽略常数与低阶项。",
      answer: true,
      explanation: "大 O 关注增长量级：3n² + 5n + 7 记为 O(n²)，常数与低阶项在 n 足够大时不影响量级判断。",
      difficulty: "easy",
      tags: ["复杂度", "渐近分析"],
      sourceKey: "algorithms-python",
    }
  ),
  ...topicQuestionPair(
    "algo-space-tradeoff",
    "algo-complexity",
    {
      stem: "用哈希表把「查找是否出现过」从逐个比较改为一次定位，本质上是？",
      options: ["把时间复杂度换成空间复杂度", "同时降低时间与空间", "只降低常数因子", "把算法变成并行"],
      answer: "A",
      explanation: "额外开一张表记录已见元素，用 O(n) 额外空间把单次查找从 O(n) 降到 O(1)，是典型的时空权衡。",
      difficulty: "medium",
      tags: ["空间复杂度", "时空权衡"],
      sourceKey: "algorithms-java",
    },
    {
      stem: "递归实现如果每层都复制一份子数组，空间复杂度会随层数线性增长。",
      answer: true,
      explanation: "每层复制产生 O(n) 额外空间，递归深度为 n 时总空间达 O(n²)；改成传下标区间即可降为 O(1) 额外空间。",
      difficulty: "medium",
      tags: ["递归", "空间复杂度"],
      sourceKey: "algorithms-java",
    }
  ),
  ...topicQuestionPair(
    "algo-correctness-invariants",
    "algo-complexity",
    {
      stem: "循环不变式在算法分析中主要用于？",
      options: ["证明算法在每轮迭代后保持某个为真的性质", "估算运行时间常数", "压缩内存占用", "替代单元测试"],
      answer: "A",
      explanation: "不变式在初始化、保持、终止三处成立，即可推出算法正确；它是把「看起来对」变成「可以证明对」的工具。",
      difficulty: "medium",
      tags: ["正确性", "不变式"],
      sourceKey: "coding-interview-university",
    },
    {
      stem: "二分查找把区间写成 [left, right) 半开区间时，循环条件通常写 left < right。",
      answer: true,
      explanation: "半开区间下 right 是哨兵位置（不含），因此当 left == right 时区间为空，循环应结束；写成 <= 会越界访问。",
      difficulty: "hard",
      tags: ["二分查找", "边界"],
      sourceKey: "algorithms-javascript",
    }
  ),
];

const linearQuestions = [
  ...topicQuestionPair(
    "algo-array-two-pointer",
    "algo-linear",
    {
      stem: "在有序数组中找两数之和等于目标值，双指针（左右夹逼）的核心依据是？",
      options: ["和偏大就让右指针左移，偏小就让左指针右移", "随机移动任意指针", "每次重置两个指针", "先排序再暴力枚举"],
      answer: "A",
      explanation: "有序性保证：和偏大时只有减小较大者才可能命中，偏小时只有增大较小者才可能命中，因此每步都能排除一行/一列。",
      difficulty: "medium",
      tags: ["双指针", "有序数组"],
      sourceKey: "algorithms-python",
    },
    {
      stem: "滑动窗口求「最长无重复子串」时，右指针扩张、左指针只在出现重复字符时收缩。",
      answer: true,
      explanation: "窗口内始终维持「无重复」这一不变式：右指针纳入新字符，若重复则左指针收缩到重复字符之后，全程 O(n)。",
      difficulty: "medium",
      tags: ["滑动窗口", "不变式"],
      sourceKey: "algorithms-python",
    }
  ),
  ...topicQuestionPair(
    "algo-linked-list",
    "algo-linear",
    {
      stem: "单链表原地反转需要几个指针，且循环体内赋值顺序为何关键？",
      options: ["三个指针，必须先保存 next 再改指针指向", "一个指针即可", "两个指针，先改指向再保存 next", "不需要指针，直接交换节点值"],
      answer: "A",
      explanation: "prev/curr/next 三指针；必须先 `next = curr.next`，否则改掉 curr.next 后就丢失了剩余链表。",
      difficulty: "medium",
      tags: ["链表", "指针"],
      sourceKey: "algorithms-java",
    },
    {
      stem: "检测链表是否有环可以用快慢指针，相遇即说明存在环。",
      answer: true,
      explanation: "快指针每步走两格、慢指针走一格；若有环，两者必在环内相遇（相对速度为 1，不会跳过）。",
      difficulty: "medium",
      tags: ["链表", "快慢指针"],
      sourceKey: "algorithms-java",
    }
  ),
  ...topicQuestionPair(
    "algo-stack-queue",
    "algo-linear",
    {
      stem: "用两个栈实现队列，元素入队与出队的均摊代价是？",
      options: ["O(1) 均摊", "O(n) 每次", "O(log n)", "O(n²)"],
      answer: "A",
      explanation: "入队压入 in 栈；出队时若 out 栈为空则一次性把 in 全倒入 out。每个元素最多被搬一次，故均摊 O(1)。",
      difficulty: "hard",
      tags: ["栈", "队列", "均摊分析"],
      sourceKey: "algorithms-python",
    },
    {
      stem: "单调栈适合解决「下一个更大元素」这类问题，因为它在栈内维持单调性。",
      answer: true,
      explanation: "栈内保持递减（或递增）时，新元素弹出所有比它小的元素，被弹出的元素的下一个更大元素就是当前元素，整体 O(n)。",
      difficulty: "hard",
      tags: ["单调栈", "线性时间"],
      sourceKey: "algorithms-go",
    }
  ),
];

const hashTreeQuestions = [
  ...topicQuestionPair(
    "algo-hash-table",
    "algo-hash-tree",
    {
      stem: "哈希表平均 O(1) 查找，最坏情况退化为 O(n) 的直接原因是？",
      options: ["大量键冲突到同一个桶", "哈希函数太慢", "表容量太小", "键的数据类型不同"],
      answer: "A",
      explanation: "冲突集中时桶退化成链表/长链，查找需要顺序扫描，最坏 O(n)；好的哈希函数与负载因子控制是缓解手段。",
      difficulty: "medium",
      tags: ["哈希表", "冲突"],
      sourceKey: "algorithms-java",
    },
    {
      stem: "开放寻址法与链地址法都要在负载因子过高时扩容。",
      answer: true,
      explanation: "负载因子上升会显著增加探测长度或链长，扩容并重新散列是维持均摊 O(1) 的必要条件。",
      difficulty: "medium",
      tags: ["哈希表", "负载因子"],
      sourceKey: "algorithms-java",
    }
  ),
  ...topicQuestionPair(
    "algo-binary-search",
    "algo-hash-tree",
    {
      stem: "二分查找中计算中点时用 left + (right - left) / 2 而不是 (left + right) / 2，是为了？",
      options: ["避免两数相加溢出", "让代码更短", "提高缓存命中", "处理负数下标"],
      answer: "A",
      explanation: "在定长整型里 left + right 可能溢出为负数，导致下标非法；先减后加可把中间量控制在区间长度内。",
      difficulty: "medium",
      tags: ["二分查找", "整数溢出"],
      sourceKey: "algorithms-javascript",
    },
    {
      stem: "在「求第一个满足条件的下标」这类二分中，需要额外维护答案变量而不是直接返回 mid。",
      answer: true,
      explanation: "命中 mid 时不能立刻返回（左侧可能还有更早的满足者），要用 ans 记录后继续收缩左边界，循环结束再返回 ans。",
      difficulty: "hard",
      tags: ["二分查找", "边界"],
      sourceKey: "algorithms-javascript",
    }
  ),
  ...topicQuestionPair(
    "algo-tree-traversal",
    "algo-hash-tree",
    {
      stem: "中序遍历二叉搜索树得到的序列具有什么性质？",
      options: ["严格递增", "随机分布", "等于层序", "等于前序"],
      answer: "A",
      explanation: "BST 保证左子树键小于根、右子树键大于根，中序（左-根-右）遍历因此按升序输出。",
      difficulty: "easy",
      tags: ["二叉树", "BST"],
      sourceKey: "algorithms-go",
    },
    {
      stem: "递归遍历改成显式栈迭代时，需要自己维护访问顺序，否则会丢失回溯信息。",
      answer: true,
      explanation: "递归把回溯信息放在调用栈里；迭代实现必须显式压入「待处理节点或标记」，否则无法正确回到父节点。",
      difficulty: "medium",
      tags: ["遍历", "迭代"],
      sourceKey: "algorithms-go",
    }
  ),
];

const sortGraphQuestions = [
  ...topicQuestionPair(
    "algo-sorting",
    "algo-sort-graph",
    {
      stem: "下列排序算法中，哪一个不是稳定的？",
      options: ["归并排序", "冒泡排序", "插入排序", "快速排序"],
      answer: "D",
      explanation: "快排的分区交换会跨越相同键的元素，可能改变相等元素的相对次序，因此不稳定（可用三路划分等技巧缓解）。",
      difficulty: "medium",
      tags: ["排序", "稳定性"],
      sourceKey: "algorithms-python",
    },
    {
      stem: "基于比较的排序算法最坏情况下的下界是 O(n log n)。",
      answer: true,
      explanation: "n 个元素有 n! 种排列，每次比较至多把可能性减半，故需 Ω(log(n!)) = Ω(n log n) 次比较。",
      difficulty: "hard",
      tags: ["排序", "下界"],
      sourceKey: "coding-interview-university",
    }
  ),
  ...topicQuestionPair(
    "algo-graph-search",
    "algo-sort-graph",
    {
      stem: "在边权均为 1 的图上求最短路径，最合适的是？",
      options: ["BFS", "DFS", "拓扑排序", "并查集"],
      answer: "A",
      explanation: "BFS 按层扩展，第一次到达某节点必然经过最少边数，因此边权相等时即最短路（有权且非负则用 Dijkstra）。",
      difficulty: "medium",
      tags: ["图", "BFS"],
      sourceKey: "algorithms-go",
    },
    {
      stem: "拓扑排序只对存在环的有向图有意义。",
      answer: false,
      explanation: "拓扑排序要求有向无环图（DAG）；若存在环则不存在满足所有先后约束的线性序列，算法会检测到并报错。",
      difficulty: "medium",
      tags: ["图", "拓扑排序"],
      sourceKey: "algorithms-go",
    }
  ),
  ...topicQuestionPair(
    "algo-dp-greedy",
    "algo-sort-graph",
    {
      stem: "动态规划相比暴力递归的关键改进是？",
      options: ["缓存重叠子问题的结果", "把递归改成循环", "减少输入规模", "使用更快的语言"],
      answer: "A",
      explanation: "DP 通过记忆化/表格避免重复求解同一个子问题，把指数级搜索降为多项式级；改循环只是形式，缓存才是本质。",
      difficulty: "medium",
      tags: ["动态规划", "重叠子问题"],
      sourceKey: "algorithms-python",
    },
    {
      stem: "贪心算法能得到全局最优的前提是问题具有贪心选择性质与最优子结构。",
      answer: true,
      explanation: "缺少贪心选择性质时，局部最优会锁死后续选择（如 0-1 背包用单位价值贪心即失败），此时需要 DP。",
      difficulty: "hard",
      tags: ["贪心", "最优子结构"],
      sourceKey: "algorithms-java",
    }
  ),
];

export const algorithmsTrack: LearningTrack = {
  slug: "algorithms",
  title: "算法与数据结构",
  category: "计算机基础",
  level: "进阶",
  accent: "#1F6F6B",
  softAccent: "#E6F2F1",
  icon: "git-branch-outline",
  summary: "从复杂度分析到线性结构、散列与树、排序与图，建立能推导、能证明、能取舍的算法能力。",
  whyLearn:
    "算法能力不是「刷题数量」，而是遇到新问题时能判断数据形状、估计代价、说清正确性依据。这份能力直接决定代码在数据量增长后是否还站得住。",
  prerequisites: ["能读写一门编程语言（Python / Java / Go / JavaScript 任选）", "理解变量、循环与函数调用"],
  studyMethod: [
    "先写清输入输出与约束，再动手写代码",
    "每个实现都给出复杂度与正确性理由，不靠「感觉对了」",
    "用边界样例（空、单元素、全相同、极值）验证，而不是只跑一个好例子",
  ],
  estimatedHours: 96,
  featured: true,
  sources: [
    {
      key: "algorithms-python",
      name: "TheAlgorithms/Python",
      url: "https://github.com/TheAlgorithms/Python",
      license: "MIT",
      usage: "import",
      note: "算法与数据结构的 Python 实现参考，用于核对边界条件与复杂度",
    },
    {
      key: "algorithms-java",
      name: "TheAlgorithms/Java",
      url: "https://github.com/TheAlgorithms/Java",
      license: "MIT",
      usage: "import",
      note: "Java 实现与集合容器行为参考",
    },
    {
      key: "algorithms-go",
      name: "TheAlgorithms/Go",
      url: "https://github.com/TheAlgorithms/Go",
      license: "MIT",
      usage: "import",
      note: "Go 实现参考，用于对照并发与切片语义下的写法",
    },
    {
      key: "algorithms-javascript",
      name: "trekhleb/javascript-algorithms",
      url: "https://github.com/trekhleb/javascript-algorithms",
      license: "MIT",
      usage: "import",
      note: "JS/TS 实现的算法与数据结构集合，含复杂度标注",
    },
    {
      key: "coding-interview-university",
      name: "Coding Interview University",
      url: "https://github.com/jwasham/coding-interview-university",
      license: "CC BY-SA 4.0",
      usage: "reference",
      note: "计算机基础覆盖面清单，仅作外链引用与校对",
    },
    {
      key: "system-design-primer",
      name: "System Design Primer",
      url: "https://github.com/donnemartin/system-design-primer",
      license: "CC BY 4.0",
      usage: "reference",
      note: "复杂度与取舍的工程视角参考，仅作外链",
    },
  ],
  stages: [
    {
      key: "algo-complexity",
      title: "复杂度与算法思维",
      weeks: "第 1-2 周",
      goal: "学会用增长量级而不是运行毫秒数比较算法，并能说明正确性依据。",
      outcome: "给定一段代码能写出时间/空间复杂度，并为循环写清不变式。",
      topics: [
        {
          key: "algo-complexity-basics",
          title: "时间复杂度与大 O",
          summary: "用增长量级描述代价：最好、最坏、平均与均摊的区别。",
          concepts: ["渐进记号", "最坏与均摊", "嵌套与递归的计数", "常见量级排序"],
          principles: [
            "只保留最高阶项并忽略常数系数，因为比较的是 n 增大后的趋势",
            "最坏情况决定容量规划，平均情况决定日常体验，均摊用于解释偶发高开销",
            "递归式 T(n)=2T(n/2)+O(n) 展开后是 O(n log n)，可用主定理快速判断",
          ],
          applications: ["容量评估", "方案取舍", "性能瓶颈定位"],
          pitfalls: ["拿本机运行时间当复杂度证据", "忽略隐藏的高阶操作（如隐式复制）", "把均摊当最坏承诺"],
          method: "先数清「主导操作执行了多少次」，再按 n 的增长取量级。",
          exercise: "给出一段带嵌套循环与递归调用的代码，分别写出时间与空间复杂度并说明推导过程。",
          checkpoint: "能对同一问题的两种实现给出量级比较，并指出在什么 n 范围下差距才显现。",
        },
        {
          key: "algo-space-tradeoff",
          title: "空间复杂度与时空权衡",
          summary: "额外空间的来源，以及用空间换时间（或反过来）的判断依据。",
          concepts: ["额外空间与输入空间", "递归栈深度", "原地算法", "缓存换时间"],
          principles: [
            "空间复杂度只算额外申请的空间，输入本身不计入",
            "递归的空间开销等于最大栈深度，而不是总调用次数",
            "缓存是典型的时间换空间：命中率不高时反而是负收益",
          ],
          applications: ["内存受限环境", "流式处理", "缓存设计"],
          pitfalls: ["以为递归「不占空间」", "忽略哈希表的负载因子开销", "在内存紧张时缓存整个结果集"],
          method: "先问「能不能只读一遍」，再决定是否值得开额外结构。",
          exercise: "把一段需要 O(n) 额外空间的实现改成原地版本，说明牺牲了哪些可读性或稳定性。",
          checkpoint: "能说清一个方案多花了多少空间、换回了什么，以及代价是否值得。",
        },
        {
          key: "algo-correctness-invariants",
          title: "正确性与循环不变式",
          summary: "用不变式与终止条件把「看起来对」变成可证明的正确性。",
          concepts: ["前置与后置条件", "循环不变式", "终止性", "边界与极端输入"],
          principles: [
            "不变式必须在初始化时成立、每轮迭代后保持，并在终止时推出目标结论",
            "终止性要有单调递减的度量（如区间长度），否则循环可能永不结束",
            "边界用例不是补充，而是验证不变式是否写对的主要手段",
          ],
          applications: ["二分与双指针", "排序与分区", "算法复盘"],
          pitfalls: ["只测正常输入就宣称正确", "不变式写得太弱（保持成立但推不出结论）", "忽略空输入与单元素"],
          method: "动手前先写三句话：初始、保持、终止，再写代码。",
          exercise: "为一个二分查找实现写出不变式与终止条件，并构造三个边界用例验证。",
          checkpoint: "能指出某个实现中不变式在第几行被破坏。",
        },
      ],
      questionKeys: complexityQuestions.map((question) => question.key),
    },
    {
      key: "algo-linear",
      title: "线性结构",
      weeks: "第 3-4 周",
      goal: "掌握数组、链表、栈与队列的代价差异，并能据此选择容器。",
      outcome: "能写出双指针/滑动窗口与链表指针操作的正确实现。",
      topics: [
        {
          key: "algo-array-two-pointer",
          title: "数组、双指针与滑动窗口",
          summary: "基于有序性或窗口不变式，把嵌套扫描降为一次线性扫描。",
          concepts: ["连续内存与随机访问", "双指针夹逼", "滑动窗口", "窗口不变式"],
          principles: [
            "数组随机访问 O(1)，但中间插入删除要搬移元素 O(n)",
            "双指针成立的前提是「能安全地排除一整行或一整列」",
            "滑动窗口的关键是窗口内维护一个可增量更新的性质",
          ],
          applications: ["有序数组求和", "子串/子数组统计", "区间合并"],
          pitfalls: ["在无序数据上套用夹逼", "窗口收缩条件写错导致漏解", "忘记处理空数组"],
          method: "先确认单调性/不变式，再决定指针怎么动。",
          exercise: "实现「最长无重复子串」并给出复杂度与不变式说明。",
          checkpoint: "能解释每一步指针移动为什么不会漏掉更优解。",
        },
        {
          key: "algo-linked-list",
          title: "链表与指针操作",
          summary: "指针改写的顺序、虚拟头节点与快慢指针的用法。",
          concepts: ["节点与指针", "虚拟头节点", "快慢指针", "原地反转"],
          principles: [
            "改指针前必须先保存后继，否则会丢失剩余链表",
            "虚拟头节点把「删除/插入首元素」变成普通情况，消除特判",
            "快慢指针能在 O(1) 空间内解决中点、环检测与倒数第 k 个",
          ],
          applications: ["LRU 链表", "大整数运算", "内存紧凑场景"],
          pitfalls: ["循环里改错顺序导致断链", "忘记把尾节点置空造成环", "对空链表与单节点路路径不测"],
          method: "画图再写代码，标出每一步三个指针的位置。",
          exercise: "实现单链表原地反转与环检测，并各写一个边界用例。",
          checkpoint: "能在一张纸上逐步演算指针变化而不出错。",
        },
        {
          key: "algo-stack-queue",
          title: "栈、队列与单调结构",
          summary: "受限访问顺序带来的价值，以及单调栈/队列的线性时间技巧。",
          concepts: ["LIFO 与 FIFO", "调用栈", "单调栈", "双端队列"],
          principles: [
            "栈适合处理「最近未匹配」的嵌套关系（括号、表达式求值）",
            "单调结构通过弹出「已经确定答案的元素」把嵌套比较压成 O(n)",
            "用两个栈模拟队列是均摊分析的标准范例",
          ],
          applications: ["表达式解析", "下一个更大元素", "滑动窗口最值"],
          pitfalls: ["在需要随机访问的场景硬用栈", "把栈当队列用导致结果逆序", "单调性维护条件写反"],
          method: "先判断问题是否只需「最近的」信息，是则考虑栈。",
          exercise: "用单调栈求数组中每个元素的下一个更大元素，并解释为什么是 O(n)。",
          checkpoint: "能说明被弹出的元素为何不可能再有更优答案。",
        },
      ],
      questionKeys: linearQuestions.map((question) => question.key),
    },
    {
      key: "algo-hash-tree",
      title: "散列与树",
      weeks: "第 5-6 周",
      goal: "用哈希与树形结构处理查找、去重与有序访问。",
      outcome: "能为查找类问题选择哈希或有序结构，并写对二分边界。",
      topics: [
        {
          key: "algo-hash-table",
          title: "哈希表与冲突处理",
          summary: "哈希函数、冲突策略与负载因子如何决定平均代价。",
          concepts: ["哈希函数", "链地址法", "开放寻址", "负载因子与扩容"],
          principles: [
            "哈希把键映射到桶，平均 O(1)，但依赖均匀分布与受控负载因子",
            "链地址法实现简单、删除友好；开放寻址缓存友好但删除要打墓碑",
            "扩容时重新散列是 O(n) 的一次性开销，均摊后仍是 O(1)",
          ],
          applications: ["去重与计数", "缓存键索引", "集合运算"],
          pitfalls: ["用可变对象当键导致查不到", "哈希函数与 equals 不一致", "对顺序有要求却用哈希表"],
          method: "先问是否需要有序或范围查询；不需要才优先哈希。",
          exercise: "统计一段文本中出现次数最多的 k 个词，说明为什么哈希表优于排序。",
          checkpoint: "能解释负载因子升高后查找代价上升的原因。",
        },
        {
          key: "algo-binary-search",
          title: "二分查找与边界",
          summary: "区间定义、边界收缩与「找第一个满足条件的元素」的写法。",
          concepts: ["有序前提", "半开区间", "边界收缩", "溢出与死循环"],
          principles: [
            "二分要求单调性：能把「满足」与「不满足」分成连续两段",
            "区间开闭必须与循环条件、指针更新保持一致，混用是死循环主因",
            "求第一个满足的位置时用 ans 暂存并继续收缩，而不是命中即返回",
          ],
          applications: ["有序查找", "答案二分（最小可行值）", "旋转数组"],
          pitfalls: ["中点计算溢出", "边界更新写成 mid 导致死循环", "忘记处理不在范围内的情形"],
          method: "先定区间语义，再写更新，最后用两个边界用例验证。",
          exercise: "实现「在有序数组中找第一个大于等于目标值的下标」，并覆盖目标小于最小/大于最大的情况。",
          checkpoint: "能对任意 mid 说明下一轮区间为何不会丢掉答案。",
        },
        {
          key: "algo-tree-traversal",
          title: "二叉树遍历与递归",
          summary: "前中后序与层序的差别，以及递归到迭代的转换。",
          concepts: ["树与递归结构", "前中后序", "层序 BFS", "BST 性质"],
          principles: [
            "遍历顺序决定能解决的问题：中序用于 BST 有序化，层序用于最短层数",
            "递归深度即树高，退化成链时深度为 n，需警惕栈溢出",
            "迭代实现必须显式保存回溯信息，本质是把调用栈搬到堆上",
          ],
          applications: ["BST 校验与查找", "表达式树", "层级统计"],
          pitfalls: ["BST 校验只比父子不等而漏掉祖先约束", "递归改迭代时丢失回溯", "忽略空树"],
          method: "先写出递归版本，再考虑是否需要迭代与显式栈。",
          exercise: "用中序与迭代两种方式校验一棵树是否为 BST，并说明各自的复杂度。",
          checkpoint: "能指出仅比较父子为什么不足以判断 BST。",
        },
      ],
      questionKeys: hashTreeQuestions.map((question) => question.key),
    },
    {
      key: "algo-sort-graph",
      title: "排序、图与策略",
      weeks: "第 7-8 周",
      goal: "掌握排序权衡、图遍历模型与动态规划/贪心的适用边界。",
      outcome: "能针对具体约束选择排序、建图搜索或 DP，并说明为什么不用另一种。",
      topics: [
        {
          key: "algo-sorting",
          title: "排序算法与稳定性",
          summary: "常见排序的复杂度、稳定性与适用数据规模。",
          concepts: ["比较排序下界", "稳定性", "分治与分区", "非比较排序"],
          principles: [
            "比较排序最坏下界 Ω(n log n)，想更快必须利用键的取值范围",
            "稳定性决定多关键字排序能否分步完成",
            "小数组用插入排序、大数组用快排/归并的混合策略是工程常态",
          ],
          applications: ["多关键字排序", "Top-K", "数据去重前处理"],
          pitfalls: ["快排固定取首元素导致有序输入退化", "以为归并一定比快排慢", "忽略缓存局部性"],
          method: "先看数据规模与是否要求稳定，再选算法。",
          exercise: "用两种排序处理 10 万条带重复键的记录，比较耗时并解释差异。",
          checkpoint: "能说明为什么工程实现常在小规模区间切回插入排序。",
        },
        {
          key: "algo-graph-search",
          title: "图的遍历与最短路",
          summary: "BFS/DFS 的选择、拓扑排序与带权最短路的基本条件。",
          concepts: ["邻接表与矩阵", "BFS 分层", "DFS 与回溯", "拓扑序与 Dijkstra"],
          principles: [
            "BFS 保证层数最小，DFS 适合连通性与路径枚举",
            "拓扑排序要求 DAG，存在环时无解并应被检测出来",
            "Dijkstra 要求边权非负；含负权需要 Bellman-Ford 一类方法",
          ],
          applications: ["依赖解析", "社交关系层次", "路由与最短跳数"],
          pitfalls: ["用 DFS 求无权最短路", "拓扑排序忘记入度更新", "Dijkstra 用在负权图上"],
          method: "先判断图是有向/无向、有权/无权，再选算法。",
          exercise: "给定一张依赖图，判断能否拓扑排序；若能则给出一个合法顺序。",
          checkpoint: "能说明换算法会让哪一类输入得到错误结果。",
        },
        {
          key: "algo-dp-greedy",
          title: "动态规划与贪心",
          summary: "状态与转移的建模方法，以及贪心的适用条件。",
          concepts: ["重叠子问题", "状态与转移", "记忆化与自底向上", "贪心选择性质"],
          principles: [
            "DP 的本质是缓存重叠子问题，把指数搜索降为多项式",
            "状态定义决定转移难度：状态要能无后效地描述「到这一步的全部必要信息」",
            "贪心只有在具备贪心选择性质时才最优，否则必须回退到 DP",
          ],
          applications: ["背包与编辑距离", "区间调度", "路径计数"],
          pitfalls: ["状态定义有后效导致答案错误", "忘记初始化边界状态", "对 0-1 背包误用单位价值贪心"],
          method: "先写暴力递归，观察重复子问题，再补缓存或改成表格。",
          exercise: "用 DP 解决 0-1 背包并给出状态定义与转移方程，说明为什么贪心会失败。",
          checkpoint: "能指出某个 DP 状态定义为什么会产生后效性。",
        },
      ],
      questionKeys: sortGraphQuestions.map((question) => question.key),
    },
  ],
  questions: [...complexityQuestions, ...linearQuestions, ...hashTreeQuestions, ...sortGraphQuestions],
};
