import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

const foundationQuestions = [
  ...topicQuestionPair(
    "sec-trust-boundary",
    "sec-foundation",
    {
      stem: "在「浏览器 → 网关 → 应用 → 数据库」这条链路上，哪一段最应被视为不可信？",
      options: ["数据库内部", "应用进程内部", "从浏览器到应用边界之前的一切输入", "操作系统的内存管理"],
      answer: "C",
      explanation: "凡是跨越进程/网络边界进入应用的数据都必须按不可信处理，包括请求参数、头部、Cookie、上传文件与上游回调。",
      difficulty: "easy",
      tags: ["信任边界", "威胁建模"],
      sourceKey: "juice-shop",
    },
    {
      stem: "只要客户端做了输入校验，服务端就可以信任客户端传来的数据。",
      answer: false,
      explanation: "客户端校验只提升体验，攻击者可以完全绕过前端直接构造请求，服务端必须独立做校验与鉴权。",
      difficulty: "easy",
      tags: ["信任边界", "客户端校验"],
      sourceKey: "juice-shop",
    }
  ),
  ...topicQuestionPair(
    "sec-input-validation",
    "sec-foundation",
    {
      stem: "对用户输入采用「白名单校验」相比「黑名单过滤」的主要优势是？",
      options: ["运行更快", "只接受已知合法形态，未知变体默认拒绝", "更容易写正则", "不需要转义"],
      answer: "B",
      explanation: "白名单默认拒绝，能覆盖编码绕过等未知变体；黑名单总是落后于新的绕过手法。",
      difficulty: "medium",
      tags: ["输入校验", "白名单"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "对输入先做 Unicode 规范化与解码，再做校验，能减少「编码绕过」。",
      answer: true,
      explanation: "多层编码（如 %2e%2e、全角字符）常被用来绕过朴素过滤；先解码规范化到唯一表示再校验可显著减少此类绕过。",
      difficulty: "medium",
      tags: ["规范化", "编码绕过"],
      sourceKey: "owasp-cheatsheets",
    }
  ),
  ...topicQuestionPair(
    "sec-least-privilege",
    "sec-foundation",
    {
      stem: "「失败安全（fail-safe）」在本章语境下指的是？",
      options: ["出错时直接放行以免影响体验", "出错时按拒绝/最小权限处理", "出错时打印更多日志", "出错时自动重试"],
      answer: "B",
      explanation: "fail-safe 指鉴权或校验环节异常时默认拒绝访问（fail-closed），而不是默认放行。",
      difficulty: "medium",
      tags: ["最小权限", "失败安全"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "给应用配数据库账号时，遵循最小权限意味着不应直接使用超级用户。",
      answer: true,
      explanation: "应用账号只应拥有完成业务所需的库表权限；使用超级用户会让一次注入或泄露直接升级为全库乃至主机失陷。",
      difficulty: "easy",
      tags: ["最小权限", "数据库账号"],
      sourceKey: "owasp-wstg",
    }
  ),
];

const webQuestions = [
  ...topicQuestionPair(
    "sec-injection",
    "sec-web",
    {
      stem: "下面哪种写法最能从根本上避免 SQL 注入？",
      options: ["对特殊字符做转义拼接", "使用参数化查询（预编译占位符）", "限制输入长度", "把 SQL 放进存储过程名里"],
      answer: "B",
      explanation: "参数化查询把数据与语句结构分离，数据库不会把参数当代码执行，是防注入的根本手段；拼接+转义容易遗漏。",
      difficulty: "easy",
      tags: ["SQL注入", "参数化查询"],
      sourceKey: "juice-shop",
    },
    {
      stem: "把用户输入直接拼进 shell 命令字符串，即使做了转义也依然存在命令注入风险。",
      answer: true,
      explanation: "shell 解析规则复杂，转义难以覆盖全部边界；应改用不经过 shell 的 API 并把参数作为数组传递。",
      difficulty: "medium",
      tags: ["命令注入", "转义"],
      sourceKey: "owasp-cheatsheets",
    }
  ),
  ...topicQuestionPair(
    "sec-xss-output",
    "sec-web",
    {
      stem: "防 XSS 最有效的通用手段是？",
      options: ["过滤 <script> 标签", "在输出到不同上下文时做正确的输出编码", "把输入全部去掉尖括号", "禁用 JavaScript"],
      answer: "B",
      explanation: "XSS 的本质是数据被当成代码执行，应按 HTML/属性/URL/JS 等具体输出上下文做转义，而不是靠黑名单过滤。",
      difficulty: "medium",
      tags: ["XSS", "输出编码"],
      sourceKey: "juice-shop",
    },
    {
      stem: "设置了 Content-Security-Policy 后就可以完全不再对输出做编码。",
      answer: false,
      explanation: "CSP 是纵深防御的一层，能减轻影响但不替代输出编码；策略配置不当或存在可绕过的内联点时仍会失效。",
      difficulty: "hard",
      tags: ["CSP", "纵深防御"],
      sourceKey: "owasp-cheatsheets",
    }
  ),
  ...topicQuestionPair(
    "sec-csrf-cors",
    "sec-web",
    {
      stem: "对基于 Cookie 会话的应用，防御 CSRF 的常见有效手段是？",
      options: ["把 Cookie 设为 HttpOnly", "校验同源来源并使用 CSRF Token / SameSite", "加密请求体", "缩短会话超时"],
      answer: "B",
      explanation: "CSRF 利用浏览器自动携带 Cookie 的特性，需要服务端校验请求确来自本站：CSRF Token、SameSite Cookie 与 Origin 校验是主力。",
      difficulty: "medium",
      tags: ["CSRF", "SameSite"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "CORS 的 Access-Control-Allow-Origin 配置为 * 时，配合凭证请求仍能安全共享会话。",
      answer: false,
      explanation: "携带凭证的请求不允许使用通配来源；把来源设成 * 且允许凭证属于错误配置，会破坏同源隔离。",
      difficulty: "hard",
      tags: ["CORS", "同源策略"],
      sourceKey: "owasp-wstg",
    }
  ),
];

const authQuestions = [
  ...topicQuestionPair(
    "sec-password-hashing",
    "sec-auth",
    {
      stem: "存储用户口令时，正确做法是？",
      options: ["MD5 加固定盐", "SHA-256 直接哈希", "使用 bcrypt/argon2 等慢哈希并每个用户独立随机盐", "Base64 编码后存库"],
      answer: "C",
      explanation: "口令需要抗暴力破解的慢哈希（bcrypt、scrypt、argon2）并配独立随机盐，快速哈希与可逆编码都不合格。",
      difficulty: "medium",
      tags: ["口令存储", "哈希"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "对同一口令，使用相同盐会让攻击者可以用彩虹表批量命中多个账户。",
      answer: true,
      explanation: "相同盐使哈希可被统一预计算；每用户独立随机盐能迫使攻击者逐账号计算，显著抬高成本。",
      difficulty: "medium",
      tags: ["盐", "彩虹表"],
      sourceKey: "juice-shop",
    }
  ),
  ...topicQuestionPair(
    "sec-session-token",
    "sec-auth",
    {
      stem: "把会话 Cookie 设置为 HttpOnly 的作用是？",
      options: ["防止被 JavaScript 读取，降低 XSS 窃取会话的风险", "让 Cookie 只在 HTTPS 下发送", "防止 CSRF", "加密 Cookie 内容"],
      answer: "A",
      explanation: "HttpOnly 阻止脚本通过 document.cookie 读取会话；Secure 负责仅 HTTPS 传输，SameSite 才与 CSRF 更相关。",
      difficulty: "easy",
      tags: ["会话", "Cookie标志"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "登录成功后应保持同一个会话标识不变，方便用户识别。",
      answer: false,
      explanation: "登录成功后必须轮换会话标识（session fixation 防御），否则攻击者预置的会话标识在登录后即可直接使用。",
      difficulty: "hard",
      tags: ["会话固定", "登录"],
      sourceKey: "owasp-wstg",
    }
  ),
  ...topicQuestionPair(
    "sec-access-control",
    "sec-auth",
    {
      stem: "「水平越权」指的是？",
      options: ["低权限用户执行了高权限操作", "同权限用户访问了本不属于自己的同级资源", "跨站点脚本请求", "绕过验证码"],
      answer: "B",
      explanation: "水平越权是同级主体越界访问他人资源（如改 URL 里的 id 读别人订单）；垂直越权才是低权限做了高权限操作。",
      difficulty: "medium",
      tags: ["授权", "越权"],
      sourceKey: "juice-shop",
    },
    {
      stem: "访问控制只在前端隐藏入口即可，后端接口不必再判断归属。",
      answer: false,
      explanation: "前端隐藏只是界面约束，攻击者可直接调用接口；每个资源访问都必须在服务端校验主体对该资源的授权归属。",
      difficulty: "easy",
      tags: ["授权", "前端隐藏"],
      sourceKey: "owasp-wstg",
    }
  ),
];

const defenseQuestions = [
  ...topicQuestionPair(
    "sec-secrets",
    "sec-defense",
    {
      stem: "应用密钥（数据库口令、API Key）最不该出现的地方是？",
      options: ["环境变量注入", "密钥管理服务的引用", "提交进代码仓库的配置文件", "运行时的密文挂载"],
      answer: "C",
      explanation: "密钥一旦进入版本历史就难以彻底清除；应通过环境变量或密钥管理服务注入，并在泄露时轮换。",
      difficulty: "easy",
      tags: ["密钥管理", "配置"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "密钥一旦泄露，只要替换掉引用它的代码就无需再轮换密钥本身。",
      answer: false,
      explanation: "泄露的密钥必须视为已失陷并立即轮换，因为旧值仍可能被攻击者持有；改代码并不能使旧凭据失效。",
      difficulty: "medium",
      tags: ["密钥轮换", "泄露响应"],
      sourceKey: "owasp-cheatsheets",
    }
  ),
  ...topicQuestionPair(
    "sec-dependencies",
    "sec-defense",
    {
      stem: "防御供应链风险最符合工程实践的做法是？",
      options: ["只使用自己写的依赖", "锁定依赖版本、审计告警并及时修复高危漏洞", "禁用所有第三方库", "只在生产环境安装依赖"],
      answer: "B",
      explanation: "既不可能零依赖，也不能放任漂移；通过锁文件固定版本、依赖审计（如 npm audit / OSV）和及时升级来控制供应链风险。",
      difficulty: "medium",
      tags: ["供应链", "依赖审计"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "引入一个依赖前评估其维护活跃度与许可，属于供应链安全的一部分。",
      answer: true,
      explanation: "弃维护或来源不明的依赖会长期带漏洞且无人修复，评估活跃度、下载来源与许可是引入前的必要动作。",
      difficulty: "easy",
      tags: ["供应链", "依赖选型"],
      sourceKey: "owasp-wstg",
    }
  ),
  ...topicQuestionPair(
    "sec-defense-in-depth",
    "sec-defense",
    {
      stem: "「纵深防御」的核心含义是？",
      options: ["用一层最强的防护挡住所有攻击", "多层独立控制，任一层失效仍有兜底", "把所有安全措施集中在网关上", "只做审计不做防护"],
      answer: "B",
      explanation: "纵深防御承认单点会失效，因此在输入校验、鉴权、编码、运行时与监控上叠加彼此独立的控制。",
      difficulty: "easy",
      tags: ["纵深防御"],
      sourceKey: "owasp-cheatsheets",
    },
    {
      stem: "安全日志只用于事后取证，对及时发现入侵没有价值。",
      answer: false,
      explanation: "脱敏后的安全审计日志可用于实时告警与异常检测，是发现持续攻击的关键；事后取证只是用途之一。",
      difficulty: "medium",
      tags: ["审计日志", "监控"],
      sourceKey: "owasp-wstg",
    }
  ),
];

export const applicationSecurityTrack: LearningTrack = {
  slug: "application-security",
  title: "应用安全",
  category: "网络安全",
  level: "进阶",
  accent: "#9E2F3F",
  softAccent: "#F8E8EA",
  icon: "shield-checkmark-outline",
  summary: "从信任边界、注入与输出编码到认证授权与纵深防御，建立「按不可信输入设计、层层兜底」的应用安全能力。",
  whyLearn:
    "绝大多数线上事故并非来自高深攻击，而是一个未被校验的参数、一次拼接的 SQL 或一枚写死在仓库里的密钥。把安全当成功能而非补丁，才能让系统在上线后长期可守。",
  prerequisites: ["了解 HTTP 与前后端基本交互", "能读写至少一门后端语言（Python / Go / Java / Node 皆可）"],
  studyMethod: [
    "每个漏洞都追问「数据在哪个边界从数据变成代码」",
    "写修复方案时同时写出对应的验证用例（攻击载荷）",
    "把安全控制按层归类：输入、鉴权、输出、运行时、监控",
  ],
  estimatedHours: 88,
  featured: true,
  sources: [
    {
      key: "juice-shop",
      name: "OWASP Juice Shop",
      url: "https://github.com/juice-shop/juice-shop",
      license: "MIT",
      usage: "import",
      note: "故意含漏洞的靶场，用于说明漏洞成因与修复验证（MIT，可导入）",
    },
    {
      key: "owasp-cheatsheets",
      name: "OWASP Cheat Sheet Series",
      url: "https://github.com/OWASP/CheatSheetSeries",
      license: "CC BY-SA 4.0",
      usage: "reference",
      note: "防护措施速查表，作为写原理时的权威参照，仅外链引用",
    },
    {
      key: "owasp-wstg",
      name: "OWASP Web Security Testing Guide",
      url: "https://github.com/OWASP/wstg",
      license: "CC BY-SA 4.0",
      usage: "reference",
      note: "测试与验证方法参考，仅外链引用，不复制正文",
    },
  ],
  stages: [
    {
      key: "sec-foundation",
      title: "信任边界与输入",
      weeks: "第 1-2 周",
      goal: "建立「所有跨边界输入都不可信」的默认假设与校验习惯。",
      outcome: "能为一条请求链路画出信任边界，并对每个入口给出校验与权限策略。",
      topics: [
        {
          key: "sec-trust-boundary",
          title: "信任边界与不可信输入",
          summary: "识别数据从何处跨入可信域，并据此确定校验与鉴权位置。",
          concepts: ["信任边界", "数据流", "威胁建模", "攻击面"],
          principles: [
            "跨进程/网络边界的输入默认不可信，包括参数、头部、Cookie 与上传文件",
            "客户端校验只改善体验，安全判定必须发生在服务端",
            "先画数据流再找边界，安全控制应贴着边界布置",
          ],
          applications: ["接口设计评审", "威胁建模", "安全需求梳理"],
          pitfalls: ["把内网调用当成可信", "只校验前端", "遗漏回调与 Webhook 入口"],
          method: "先列出数据从哪来、到哪去，再在每次跨边界处标注校验与鉴权点。",
          exercise: "为一个含登录、下单与回调的接口画出信任边界，标注三处必须校验的位置。",
          checkpoint: "能指出链路中哪一段绝不能被视为可信。",
        },
        {
          key: "sec-input-validation",
          title: "输入校验与规范化",
          summary: "用白名单与规范化把不可信输入收敛到合法形态。",
          concepts: ["白名单校验", "规范化", "编码绕过", "类型与范围约束"],
          principles: [
            "白名单默认拒绝，比黑名单更能覆盖未知变体",
            "先解码规范化再校验，避免多重编码绕过",
            "校验要覆盖类型、长度、范围与格式，而不只是特殊字符",
          ],
          applications: ["表单与 API 校验", "文件上传限制", "查询参数约束"],
          pitfalls: ["只做黑名单过滤", "先校验后解码", "用客户端校验替代服务端"],
          method: "为每个字段定义允许的形态，再用统一校验层在边界处强制。",
          exercise: "为一个文件上传接口写出类型、大小与文件名校验规则，并说明如何防路径穿越。",
          checkpoint: "能解释为什么先解码再校验更安全。",
        },
        {
          key: "sec-least-privilege",
          title: "最小权限与失败安全",
          summary: "让每个组件只拿到完成职责所需的权限，并在异常时默认拒绝。",
          concepts: ["最小权限", "失败安全", "权限隔离", "默认拒绝"],
          principles: [
            "应用账号只授予业务所需权限，避免超级用户",
            "鉴权异常时默认拒绝（fail-closed），不默认放行",
            "按职责拆分凭据，泄露一个不牵连全局",
          ],
          applications: ["数据库账号授权", "服务间凭据", "网关策略"],
          pitfalls: ["复用高权限账号", "异常分支默认 return true", "共享一套全局密钥"],
          method: "为每个组件列出它真正需要的操作集合，再据此收敛权限。",
          exercise: "为一个只读报表服务设计数据库账号权限，并说明为什么不用读写账号。",
          checkpoint: "能举例说明失败时默认放行会带来什么后果。",
        },
      ],
      questionKeys: foundationQuestions.map((question) => question.key),
    },
    {
      key: "sec-web",
      title: "注入与输出编码",
      weeks: "第 3-4 周",
      goal: "理解数据何时被当成代码执行，掌握注入与 XSS 的根本防线。",
      outcome: "能识别注入点并给出参数化、输出编码与跨站防护方案。",
      topics: [
        {
          key: "sec-injection",
          title: "注入类漏洞",
          summary: "SQL、命令与模板注入的共同成因：把数据拼接进了代码结构。",
          concepts: ["SQL 注入", "命令注入", "模板注入", "参数化查询"],
          principles: [
            "参数化查询把数据与语句结构分离，是防注入的根本",
            "调用外部命令应传参数数组，避免经过 shell",
            "模板渲染不得把用户输入当模板本身执行",
          ],
          applications: ["数据访问层", "运维脚本", "邮件与页面模板"],
          pitfalls: ["字符串拼接 SQL", "对输入转义后仍拼 shell", "把用户输入当模板"],
          method: "定位所有「数据进入代码结构」的位置，逐一改造成参数化或结构化传递。",
          exercise: "把一段拼接查询改成参数化，并写出两个能验证修复的攻击载荷。",
          checkpoint: "能说明参数化为什么比转义更可靠。",
        },
        {
          key: "sec-xss-output",
          title: "XSS 与输出编码",
          summary: "按输出上下文做编码，配合 CSP 形成纵深防御。",
          concepts: ["反射型/存储型 XSS", "输出上下文", "转义与编码", "CSP"],
          principles: [
            "输出到 HTML、属性、URL、JS 不同上下文需要不同编码",
            "黑名单过滤标签无法覆盖编码绕过",
            "CSP 是纵深防御的一层，不能替代输出编码",
          ],
          applications: ["富文本渲染", "用户资料展示", "日志回显"],
          pitfalls: ["只在输入侧过滤", "用 innerHTML 直接插入用户数据", "CSP 配置过宽"],
          method: "列出所有把数据渲染进页面的位置，按上下文选择编码器。",
          exercise: "为一段把昵称渲染到属性与文本节点的代码给出正确编码方案。",
          checkpoint: "能解释为什么防 XSS 的关键在输出侧。",
        },
        {
          key: "sec-csrf-cors",
          title: "CSRF 与跨域策略",
          summary: "在浏览器自动携带凭证的前提下保护状态变更接口。",
          concepts: ["CSRF", "SameSite Cookie", "CSRF Token", "同源策略与 CORS"],
          principles: [
            "状态变更请求需校验来源：Token、SameSite 或 Origin 校验",
            "CORS 允许凭证时不得使用通配来源",
            "GET 不应产生副作用，降低被 CSRF 利用的面",
          ],
          applications: ["表单提交", "后台接口", "跨域 API 开放"],
          pitfalls: ["仅靠 Cookie 鉴权无来源校验", "CORS 通配+凭证", "把写操作放 GET"],
          method: "先确认鉴权是否依赖 Cookie，再为写接口补齐来源校验。",
          exercise: "为一个依赖 Cookie 的下单接口设计 CSRF 防护并写明 CORS 配置。",
          checkpoint: "能说明 CSRF 与 CORS 分别防的是什么。",
        },
      ],
      questionKeys: webQuestions.map((question) => question.key),
    },
    {
      key: "sec-auth",
      title: "认证与会话",
      weeks: "第 5-6 周",
      goal: "正确处理口令、会话与授权，避免身份被冒用或越权。",
      outcome: "能实现安全的登录、会话与访问控制，并识别越权风险。",
      topics: [
        {
          key: "sec-password-hashing",
          title: "口令存储与哈希",
          summary: "用慢哈希与独立随机盐抵抗口令破解。",
          concepts: ["慢哈希", "盐", "彩虹表", "口令策略"],
          principles: [
            "口令使用 bcrypt/argon2 等慢哈希而非快速哈希",
            "每个用户独立随机盐，禁止全局固定盐",
            "永远不会以可逆方式保存或返回口令",
          ],
          applications: ["账号系统", "找回与重置", "迁移既有口令库"],
          pitfalls: ["MD5/SHA-256 直接哈希", "固定盐", "明文或可逆存储"],
          method: "选一个经过审查的慢哈希算法，按每用户随机盐存储并统一参数。",
          exercise: "给出注册与登录的口令处理流程，说明盐与成本参数的作用。",
          checkpoint: "能解释为什么快哈希不适合存口令。",
        },
        {
          key: "sec-session-token",
          title: "会话与令牌",
          summary: "会话标识的生成、存储、轮换与失效。",
          concepts: ["会话标识", "Cookie 标志", "会话固定", "令牌过期与撤销"],
          principles: [
            "会话标识需足够随机，登录后必须轮换",
            "HttpOnly/Secure/SameSite 按场景组合使用",
            "令牌应有合理过期与撤销机制",
          ],
          applications: ["Web 会话", "移动端令牌", "服务间调用"],
          pitfalls: ["登录后不轮换标识", "把令牌存进 localStorage", "令牌永不过期"],
          method: "从生成、下发、存储到失效逐环节确认会话标识的安全属性。",
          exercise: "为一个 Web 登录流程写出会话 Cookie 的完整标志与轮换时机。",
          checkpoint: "能说明登录后不轮换会话会带来什么问题。",
        },
        {
          key: "sec-access-control",
          title: "授权与访问控制",
          summary: "在每个资源访问点校验主体对资源的授权归属。",
          concepts: ["垂直/水平越权", "资源归属校验", "RBAC", "默认拒绝"],
          principles: [
            "每个资源访问都要在服务端校验归属，前端隐藏不算控制",
            "按角色或属性授权，切忌只按前端菜单判断",
            "权限判定默认拒绝，未知情况不放行",
          ],
          applications: ["订单与资料访问", "后台管理", "多租户隔离"],
          pitfalls: ["只校验登录不校验归属", "依赖前端隐藏入口", "按 id 直接取数据"],
          method: "为每个涉及资源 id 的接口补上主体-资源归属校验。",
          exercise: "指出一个「改 id 即越权」的接口并给出修复与测试用例。",
          checkpoint: "能区分水平越权与垂直越权并各举一例。",
        },
      ],
      questionKeys: authQuestions.map((question) => question.key),
    },
    {
      key: "sec-defense",
      title: "密钥、依赖与纵深防御",
      weeks: "第 7-8 周",
      goal: "把单点控制升级为多层兜底，并管理密钥与供应链风险。",
      outcome: "能为一个服务设计密钥管理、依赖治理与审计监控的完整防线。",
      topics: [
        {
          key: "sec-secrets",
          title: "密钥与凭据管理",
          summary: "让密钥不落代码、可轮换、泄露可响应。",
          concepts: ["密钥管理服务", "环境变量注入", "轮换", "最小暴露"],
          principles: [
            "密钥不进代码仓库与日志，通过环境或密钥服务注入",
            "泄露一律视为失陷并立即轮换",
            "按用途拆分密钥，限制单次泄露影响面",
          ],
          applications: ["数据库凭据", "第三方 API Key", "签名密钥"],
          pitfalls: ["密钥提交进仓库", "日志打印密钥", "泄露后不轮换"],
          method: "清点所有密钥，改成注入式并制定轮换与泄露响应流程。",
          exercise: "为一个服务列出全部密钥并给出注入、轮换与泄露处置方案。",
          checkpoint: "能说明为什么改代码不能替代轮换密钥。",
        },
        {
          key: "sec-dependencies",
          title: "依赖与供应链",
          summary: "通过锁定、审计与升级治理第三方依赖风险。",
          concepts: ["锁文件", "依赖审计", "漏洞告警", "许可合规"],
          principles: [
            "依赖版本要锁定，避免构建漂移",
            "持续审计高危漏洞并设定修复时限",
            "引入依赖前评估维护活跃度与许可",
          ],
          applications: ["CI 质量门禁", "依赖升级", "第三方 SDK 引入"],
          pitfalls: ["放任版本漂移", "从不看审计报告", "引入弃维护依赖"],
          method: "在 CI 中固化依赖审计与许可检查，并为高危漏洞设修复 SLA。",
          exercise: "为一个项目配置依赖审计门禁，并说明高危漏洞的处理流程。",
          checkpoint: "能说明锁文件对供应链安全的作用。",
        },
        {
          key: "sec-defense-in-depth",
          title: "纵深防御与审计",
          summary: "用多层独立控制与脱敏审计日志形成可观测的防线。",
          concepts: ["纵深防御", "安全审计日志", "异常检测", "最小暴露"],
          principles: [
            "多层独立控制，任一层失效仍有兜底",
            "审计日志脱敏后可用于实时告警",
            "错误信息对外最小暴露，对内保留可诊断细节",
          ],
          applications: ["安全监控", "入侵检测", "事故复盘"],
          pitfalls: ["依赖单一防护", "日志含敏感明文", "对外抛栈暴露实现"],
          method: "按输入、鉴权、输出、运行时与监控逐层列出控制并查漏。",
          exercise: "为一个服务画出一张纵深防御控制清单并标注监控点。",
          checkpoint: "能说明审计日志除取证外的实时价值。",
        },
      ],
      questionKeys: defenseQuestions.map((question) => question.key),
    },
  ],
  questions: [...foundationQuestions, ...webQuestions, ...authQuestions, ...defenseQuestions],
};
