import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

const apiDesignQuestions = [
  ...topicQuestionPair(
    "be-rest-resource",
    "be-api-design",
    {
      stem: "把「把订单标记为已支付」设计成接口，最符合资源语义的做法是？",
      options: [
        "POST /orders/{id}/payment 并返回支付结果",
        "GET /orders/pay?id=1",
        "POST /updateOrderStatus",
        "GET /orders/{id}?status=paid",
      ],
      answer: "A",
      explanation: "支付是订单的子资源动作，用子资源 + POST 表达；GET 携带副作用会破坏幂等与缓存语义，动词化路径则丢失资源建模。",
      difficulty: "medium",
      tags: ["REST", "资源建模"],
      sourceKey: "system-design-primer",
    },
    {
      stem: "用 PUT 更新资源时，同一请求重复发送应与发送一次结果相同。",
      answer: true,
      explanation: "PUT 定义为幂等：以请求体整体替换目标状态，重复执行不改变最终结果，因此可以安全重试。",
      difficulty: "easy",
      tags: ["REST", "幂等"],
      sourceKey: "system-design-primer",
    }
  ),
  ...topicQuestionPair(
    "be-validation-errors",
    "be-api-design",
    {
      stem: "错误响应中除了面向用户的文案，还应提供什么才能真正被客户端可靠处理？",
      options: ["稳定的机器可读错误码", "更长的文案", "堆栈信息", "HTTP 200 加错误字段"],
      answer: "A",
      explanation: "文案可以随时改，客户端要按错误类型分流（去登录/重试/提示校验）就必须依赖稳定的 code；堆栈会泄漏内部细节。",
      difficulty: "medium",
      tags: ["错误契约", "API"],
      sourceKey: "fastapi",
    },
    {
      stem: "把校验失败和服务器异常都返回 500 会让客户端无法区分该重试还是该改输入。",
      answer: true,
      explanation: "客户端输入问题应返回 4xx（不重试），服务器异常才 5xx（可重试）；混用会导致无效重试或错误放弃。",
      difficulty: "easy",
      tags: ["错误契约", "状态码"],
      sourceKey: "fastapi",
    }
  ),
  ...topicQuestionPair(
    "be-idempotency-timeout",
    "be-api-design",
    {
      stem: "移动端离线补发同一笔提交流程时，服务端最可靠的去重手段是？",
      options: ["客户端生成的幂等键 + 数据库唯一约束", "应用层先查一遍再插入", "限制同一 IP 频率", "前端按钮禁用"],
      answer: "A",
      explanation: "应用层「先查后插」在并发下仍有窗口；唯一约束把去重下沉到数据库，是唯一能兜住并发的手段。",
      difficulty: "hard",
      tags: ["幂等", "并发"],
      sourceKey: "system-design-primer",
    },
    {
      stem: "上游调用设置超时后，仍需处理「超时但对方其实已成功」的情况。",
      answer: true,
      explanation: "超时只说明本地等不到响应，对方可能已提交；因此重试必须幂等，否则会制造重复数据。",
      difficulty: "medium",
      tags: ["超时", "重试"],
      sourceKey: "system-design-primer",
    }
  ),
];

const dataAccessQuestions = [
  ...topicQuestionPair(
    "be-orm-vs-sql",
    "be-data-access",
    {
      stem: "报表类复杂聚合查询更适合哪种实现方式？",
      options: ["手写 SQL 并显式控制执行计划", "ORM 的链式方法拼接", "在应用内存里聚合", "每条记录一次查询"],
      answer: "A",
      explanation: "复杂聚合交给数据库引擎（更少数据传输、可利用索引与并行）；ORM 适合常规 CRUD，硬套会生成难以优化的 SQL。",
      difficulty: "medium",
      tags: ["ORM", "SQL"],
      sourceKey: "postgresql",
    },
    {
      stem: "ORM 的惰性加载在序列化响应时可能触发大量额外查询。",
      answer: true,
      explanation: "惰性加载在访问关联属性时才发查询，遍历集合并访问关联字段就会变成 N+1；需显式预加载或改成一次 JOIN。",
      difficulty: "medium",
      tags: ["ORM", "N+1"],
      sourceKey: "spring-boot",
    }
  ),
  ...topicQuestionPair(
    "be-transaction-boundary",
    "be-data-access",
    {
      stem: "事务边界设计的核心原则是？",
      options: ["尽量短，且不包含网络调用", "尽量长，覆盖整个请求", "越长越安全", "由前端决定"],
      answer: "A",
      explanation: "长事务占用连接与锁、放大死锁概率；把 HTTP/RPC 调用放进事务会因外部延迟把锁持有时间拉长几个数量级。",
      difficulty: "hard",
      tags: ["事务", "锁"],
      sourceKey: "postgresql",
    },
    {
      stem: "「先读后写」的检查逻辑放进同一事务后仍有并发问题，因为默认隔离级别下读不会加锁。",
      answer: true,
      explanation: "在提交读隔离级别，普通 SELECT 不加锁，两个事务可能同时通过检查；需要唯一约束、SELECT FOR UPDATE 或更高隔离级别。",
      difficulty: "hard",
      tags: ["隔离级别", "并发"],
      sourceKey: "postgresql",
    }
  ),
  ...topicQuestionPair(
    "be-nplusone-index",
    "be-data-access",
    {
      stem: "为高频查询「按用户取最近 N 条」建立索引，最合适的是？",
      options: ["(user_id, created_at DESC) 复合索引", "只对 created_at 建索引", "只对 user_id 建索引", "不建索引靠缓存"],
      answer: "A",
      explanation: "等值列在前、排序列在后，数据库可先定位用户再顺序取前 N 条，避免额外排序与大量行扫描。",
      difficulty: "medium",
      tags: ["索引", "查询优化"],
      sourceKey: "postgresql",
    },
    {
      stem: "外键列上不建索引，删除父行会退化为全表扫描。",
      answer: true,
      explanation: "数据库需要检查子表是否有引用，缺少索引时只能扫描整张子表，删除与更新父行都会显著变慢。",
      difficulty: "medium",
      tags: ["索引", "外键"],
      sourceKey: "postgresql",
    }
  ),
];

const runtimeQuestions = [
  ...topicQuestionPair(
    "be-concurrency-model",
    "be-runtime",
    {
      stem: "多线程环境下对共享可变状态做「检查后修改」，正确的做法是？",
      options: ["用锁或原子操作保证复合操作整体原子", "只加 volatile 就够了", "把变量拆成两个变量", "降低线程数到 1"],
      answer: "A",
      explanation: "检查与修改是两步复合操作，中间可被切换；必须用锁、原子指令或数据库层面的原子 UPDATE 保证整体不可分割。",
      difficulty: "hard",
      tags: ["并发", "原子性"],
      sourceKey: "spring-boot",
    },
    {
      stem: "把 CPU 密集任务放进单线程事件循环会阻塞其它请求的处理。",
      answer: true,
      explanation: "事件循环靠非阻塞回调推进，长时间占用 CPU 会让所有待处理请求排队；应拆成小片或交给工作线程/进程。",
      difficulty: "medium",
      tags: ["事件循环", "并发模型"],
      sourceKey: "gin",
    }
  ),
  ...topicQuestionPair(
    "be-cache-strategy",
    "be-runtime",
    {
      stem: "缓存最常见的失效手段是给键设置过期时间，但更关键的是？",
      options: ["在写路径上主动失效对应键", "把过期时间设得很长", "只缓存小对象", "让客户端也缓存"],
      answer: "A",
      explanation: "只靠过期会在一段时间内返回旧值；写后主动删键（或更新键）能把不一致窗口压到最小。",
      difficulty: "medium",
      tags: ["缓存", "失效"],
      sourceKey: "system-design-primer",
    },
    {
      stem: "缓存穿透指查询不存在的数据，导致每次都打到数据库。",
      answer: true,
      explanation: "不存在的键不会被缓存，恶意或异常查询会持续穿透；可用空值缓存（带短过期）或布隆过滤器缓解。",
      difficulty: "medium",
      tags: ["缓存", "穿透"],
      sourceKey: "system-design-primer",
    }
  ),
  ...topicQuestionPair(
    "be-resilience",
    "be-runtime",
    {
      stem: "熔断器与限流器解决的问题有什么区别？",
      options: [
        "熔断保护自身不再调用故障依赖；限流保护自身不被过量请求压垮",
        "两者作用完全相同",
        "熔断限制请求速率；限流断开依赖",
        "都是前端能力",
      ],
      answer: "A",
      explanation: "熔断针对「下游已故障」快速失败避免堆积；限流针对「流量超过容量」主动丢弃；两者正交，通常同时使用。",
      difficulty: "hard",
      tags: ["限流", "熔断"],
      sourceKey: "system-design-primer",
    },
    {
      stem: "降级方案必须是预先实现的，否则故障时来不及补。",
      answer: true,
      explanation: "降级要在设计阶段就准备好（返回缓存值、返回默认结果、关闭非核心功能），并在开关后立刻可用。",
      difficulty: "medium",
      tags: ["降级", "可用性"],
      sourceKey: "system-design-primer",
    }
  ),
];

const deliveryQuestions = [
  ...topicQuestionPair(
    "be-config-secrets",
    "be-delivery",
    {
      stem: "应用读取数据库密码等秘密的正确来源是？",
      options: ["环境变量或密钥管理服务", "提交进仓库的配置文件", "硬编码在源码里", "写在接口文档中"],
      answer: "A",
      explanation: "秘密必须与代码分离，通过环境变量或密钥服务在部署时注入；进仓库等于永久泄漏（历史提交也会保留）。",
      difficulty: "easy",
      tags: ["配置", "秘密管理"],
      sourceKey: "spring-boot",
    },
    {
      stem: "配置缺失时应用应当启动失败并明确报错，而不是用猜测的默认值继续运行。",
      answer: true,
      explanation: "静默默认值会把配置错误变成难以定位的运行时问题；必要时区分「必须配置」与「可选配置」两类。",
      difficulty: "medium",
      tags: ["配置", "启动检查"],
      sourceKey: "spring-boot",
    }
  ),
  ...topicQuestionPair(
    "be-observability",
    "be-delivery",
    {
      stem: "把一次前端报错与服务端日志对应起来，最省事的做法是？",
      options: ["为每个请求生成 requestId 并同时出现在响应与日志里", "记录客户端 IP", "输出完整堆栈给前端", "只记录时间戳"],
      answer: "A",
      explanation: "requestId 把「一次请求」变成可检索的对象，排查时一次 grep 就能对齐前后端与下游调用。",
      difficulty: "easy",
      tags: ["可观测", "requestId"],
      sourceKey: "system-design-primer",
    },
    {
      stem: "指标标签里放用户 ID 会让时间序列基数爆炸。",
      answer: true,
      explanation: "每个用户 ID 都会产生一条时间序列，内存与存储会随用户数线性增长；标签值应只来自固定枚举。",
      difficulty: "hard",
      tags: ["指标", "基数"],
      sourceKey: "system-design-primer",
    }
  ),
  ...topicQuestionPair(
    "be-migration-deploy",
    "be-delivery",
    {
      stem: "给已有大表新增「非空且带默认值」的列时，安全的做法是？",
      options: ["先加可空列并回填，确认后再加非空约束", "直接加非空列锁定整表", "先停服再改", "在应用层补默认值即可"],
      answer: "A",
      explanation: "一步加非空默认可能长时间持锁阻塞写入；拆成「加列 → 回填 → 加约束」可在不停服情况下完成。",
      difficulty: "hard",
      tags: ["迁移", "在线变更"],
      sourceKey: "postgresql",
    },
    {
      stem: "迁移脚本应当只追加，并配套可执行的回滚脚本。",
      answer: true,
      explanation: "改写历史迁移会让不同环境的实际结构分叉；回滚脚本在回滚演练中验证过才可信。",
      difficulty: "medium",
      tags: ["迁移", "回滚"],
      sourceKey: "postgresql",
    }
  ),
];

export const backendEngineeringTrack: LearningTrack = {
  slug: "backend-engineering",
  title: "后端工程",
  category: "后端开发",
  level: "进阶",
  accent: "#2F5D9E",
  softAccent: "#E8EEF8",
  icon: "server-outline",
  summary: "从接口契约、事务与索引到并发、缓存与可观测，建立能扛住真实流量与故障的后端工程能力。",
  whyLearn:
    "接口能跑通只是起点。真实系统的难点在边界：并发下的幂等、事务里的锁、索引缺失导致的慢查询、故障时的降级与回滚。这些能力决定服务能否长期稳定。",
  prerequisites: ["能写一门后端语言（Python / Go / Java 任选）", "了解 HTTP 与 SQL 基础"],
  studyMethod: [
    "每个结论都要落到「哪个资源受限」：锁、连接、内存、还是网络往返",
    "写代码前先定义错误契约与幂等口径",
    "把可观测当设计的一部分：先想清楚出问题时要看什么数字",
  ],
  estimatedHours: 104,
  featured: true,
  sources: [
    {
      key: "fastapi",
      name: "FastAPI",
      url: "https://github.com/fastapi/fastapi",
      license: "MIT",
      usage: "import",
      note: "依赖注入、请求校验与契约生成的工程范式参考",
    },
    {
      key: "gin",
      name: "Gin",
      url: "https://github.com/gin-gonic/gin",
      license: "MIT",
      usage: "import",
      note: "Go Web 框架的中间件链与上下文传递实现参考",
    },
    {
      key: "system-design-primer",
      name: "System Design Primer",
      url: "https://github.com/donnemartin/system-design-primer",
      license: "CC BY 4.0",
      usage: "import",
      note: "容量估算、缓存与可用性取舍的系统设计参考",
    },
    {
      key: "spring-boot",
      name: "Spring Boot",
      url: "https://github.com/spring-projects/spring-boot",
      license: "Apache-2.0",
      usage: "reference",
      note: "自动配置与约定优于配置的实现参考，仅外链引用",
    },
    {
      key: "postgresql",
      name: "PostgreSQL",
      url: "https://github.com/postgres/postgres",
      license: "PostgreSQL License",
      usage: "reference",
      note: "事务、隔离级别与查询计划的权威行为依据",
    },
  ],
  stages: [
    {
      key: "be-api-design",
      title: "接口设计",
      weeks: "第 1-2 周",
      goal: "把接口设计成「可预测、可重试、错误可分流」的契约。",
      outcome: "能为一组业务写清资源路径、状态码、错误码与幂等口径。",
      topics: [
        {
          key: "be-rest-resource",
          title: "资源建模与 REST 语义",
          summary: "用资源与子资源表达业务，借助 HTTP 方法的语义获得可预测性。",
          concepts: ["资源与子资源", "方法语义", "状态码约定", "路径与查询参数"],
          principles: [
            "路径标识资源，方法表达动作语义，动词不应出现在路径里",
            "GET 必须无副作用且可缓存，写操作一律用 POST/PUT/PATCH/DELETE",
            "状态码表达结果类别，具体原因交给响应体里的错误码",
          ],
          applications: ["接口评审", "客户端错误处理", "网关缓存策略"],
          pitfalls: ["用 GET 触发写操作", "把动作塞进路径导致资源不可寻址", "所有错误都返回 200"],
          method: "先列出业务名词作为资源，再给每个资源列出允许的方法与状态迁移。",
          exercise: "为一套「订单 + 支付 + 退款」设计资源路径与方法，并标注每个接口的幂等性。",
          checkpoint: "能指出一个接口设计中破坏了哪条 HTTP 语义，并给出修正。",
        },
        {
          key: "be-validation-errors",
          title: "输入校验与错误契约",
          summary: "把外部输入当不可信数据，并给客户端稳定的错误码。",
          concepts: ["边界校验", "错误码与文案分离", "4xx 与 5xx 分界", "错误上下文"],
          principles: [
            "校验在系统边界做一次，内部传递已校验的数据结构",
            "面向用户的文案可以改，机器可读的错误码发布后必须稳定",
            "错误响应要能回答「谁的问题、能不能重试」",
          ],
          applications: ["表单提交", "导入接口", "SDK 错误处理"],
          pitfalls: ["把数据库异常直接透出给客户端", "只靠前端校验", "错误信息里带内部堆栈"],
          method: "先定义错误码表，再写校验与响应。",
          exercise: "为一个批量导入接口定义错误码表，写出每种错误的 HTTP 状态与响应体结构。",
          checkpoint: "能说明某个错误为什么属于 4xx 而不是 5xx。",
        },
        {
          key: "be-idempotency-timeout",
          title: "幂等、重试与超时",
          summary: "让「网络不可靠」不再制造重复数据。",
          concepts: ["幂等键", "唯一约束去重", "超时预算", "重试退避"],
          principles: [
            "超时代表「结果未知」，不是「失败」，所以重试必须幂等",
            "去重下沉到数据库唯一约束，才能兜住并发",
            "重试要有次数上限与退避，否则会把故障放大成雪崩",
          ],
          applications: ["离线补发", "支付与订单", "消息消费"],
          pitfalls: ["用随机 ID 做幂等键（每次都不一样）", "无上限重试", "把超时误判为失败并直接回滚"],
          method: "先问「重复执行会发生什么」，再决定是否需要幂等键。",
          exercise: "为一个「提交作业」接口设计幂等方案，说明并发下如何保证只落一条。",
          checkpoint: "能解释为什么应用层「先查后插」不能替代唯一约束。",
        },
      ],
      questionKeys: apiDesignQuestions.map((question) => question.key),
    },
    {
      key: "be-data-access",
      title: "数据访问与事务",
      weeks: "第 3-4 周",
      goal: "把数据访问的代价与并发风险显式化，而不是交给框架黑箱。",
      outcome: "能画出关键查询的执行路径，并写出边界明确的事务。",
      topics: [
        {
          key: "be-orm-vs-sql",
          title: "ORM 与手写 SQL 的取舍",
          summary: "常规 CRUD 用 ORM，复杂聚合与性能敏感路径用手写 SQL。",
          concepts: ["映射与惰性加载", "生成的 SQL", "聚合与窗口函数", "预加载"],
          principles: [
            "ORM 的价值是减少样板与类型安全，不是隐藏 SQL",
            "复杂聚合交给数据库，避免把大量行拉到应用内存",
            "惰性加载在循环里访问关联字段就会变成 N+1",
          ],
          applications: ["列表查询", "报表接口", "数据导出"],
          pitfalls: ["对生成 SQL 不做审查", "循环内访问关联", "手写 SQL 拼接字符串导致注入"],
          method: "先写清 SQL 意图，再决定用 ORM 表达还是手写。",
          exercise: "把一个 N+1 的列表接口改成一次查询，并对比查询次数与响应时间。",
          checkpoint: "能说出某接口实际发了哪几条 SQL。",
        },
        {
          key: "be-transaction-boundary",
          title: "事务边界与隔离级别",
          summary: "事务要短、要不含网络调用，并理解默认隔离级别不保证什么。",
          concepts: ["ACID 与隔离级别", "锁与死锁", "检查后修改", "乐观锁与版本号"],
          principles: [
            "事务越短，持锁时间越短，并发能力越强",
            "默认隔离级别下普通读取不加锁，因此「先读后写」的检查不可靠",
            "跨行更新顺序不一致是死锁主因，统一加锁顺序可规避大部分死锁",
          ],
          applications: ["转账与扣减", "库存", "状态机流转"],
          pitfalls: ["事务里调用外部接口", "无脑用最大隔离级别", "把长列表放在一个事务里逐条更新"],
          method: "先划出必须同时成立的最小写集合，再包事务。",
          exercise: "为一个「库存扣减」写出并发安全实现，分别用唯一约束/行锁/乐观锁三法。",
          checkpoint: "能说明两个并发事务在什么时间点会看到对方的中间状态。",
        },
        {
          key: "be-nplusone-index",
          title: "N+1 与索引设计",
          summary: "用复合索引与正确列顺序让高频查询走索引扫描而不是全表。",
          concepts: ["复合索引列顺序", "覆盖索引", "部分索引", "执行计划"],
          principles: [
            "等值条件列在前、排序或范围列在后，才能同时利用定位与顺序",
            "外键列没有索引时，父行的删除/更新会退化为全表扫描",
            "用 EXPLAIN 看实际计划，不要凭列上有索引就假定会被使用",
          ],
          applications: ["列表分页", "统计查询", "级联删除"],
          pitfalls: ["为每列各建一个索引", "对低选择性列单独建索引", "忽略函数包裹列导致索引失效"],
          method: "先把高频查询列出来，再按「等值→范围→排序」排序建索引。",
          exercise: "为一个分页列表接口设计复合索引，并用执行计划验证是否命中。",
          checkpoint: "能解释为什么 (a, b) 索引无法高效支持只按 b 的查询。",
        },
      ],
      questionKeys: dataAccessQuestions.map((question) => question.key),
    },
    {
      key: "be-runtime",
      title: "并发、缓存与可靠性",
      weeks: "第 5-6 周",
      goal: "在真实并发与部分故障下保持服务可用。",
      outcome: "能为关键路径设计并发安全、缓存与降级策略。",
      topics: [
        {
          key: "be-concurrency-model",
          title: "并发模型与共享状态",
          summary: "线程、协程与事件循环的差别，以及共享可变状态的处理原则。",
          concepts: ["共享可变状态", "锁与原子操作", "协程与事件循环", "背压"],
          principles: [
            "复合操作（检查后修改）必须整体原子化，否则必有竞态",
            "单线程事件循环里 CPU 密集任务会阻塞所有请求，需要拆分或转移",
            "队列要有容量上限与背压策略，否则内存会先于服务崩溃",
          ],
          applications: ["并发写同一行", "定时任务与请求共存", "任务队列"],
          pitfalls: ["以为加了 volatile 就有原子性", "在事件循环里做同步 IO", "无上限队列"],
          method: "先找出被多方同时修改的状态，再决定用锁、原子操作还是数据库原子 UPDATE。",
          exercise: "写一个计数器并演示竞态，再用锁与原子操作各修一次。",
          checkpoint: "能指出一段并发代码里竞态发生的具体指令间隙。",
        },
        {
          key: "be-cache-strategy",
          title: "缓存策略与失效",
          summary: "缓存的位置、粒度与失效方式决定收益与一致性窗口。",
          concepts: ["缓存键设计", "过期与主动失效", "穿透/击穿/雪崩", "缓存与真实来源"],
          principles: [
            "写路径主动失效能把不一致窗口压到最小，过期只是兜底",
            "不存在的键不会被缓存，需空值缓存或过滤器防穿透",
            "热点键同时过期会造成击穿，需加随机抖动或单飞（single-flight）",
          ],
          applications: ["读多写少的配置", "聚合统计", "会话与权限"],
          pitfalls: ["缓存里存了不该缓存的用户私有数据", "键过大导致序列化开销", "把缓存当数据库"],
          method: "先问「不一致能忍多久」，再决定失效策略。",
          exercise: "为一个读多写少的详情接口设计缓存，写清键、过期时间与失效时机。",
          checkpoint: "能区分穿透、击穿与雪崩，并各给一个缓解手段。",
        },
        {
          key: "be-resilience",
          title: "限流、降级与熔断",
          summary: "在过载与依赖故障时主动取舍，保住核心链路。",
          concepts: ["限流算法", "熔断状态机", "降级预案", "超时预算"],
          principles: [
            "限流保护自己不被压垮，熔断避免对已故障依赖持续堆积",
            "降级必须预先实现并带开关，故障时才有可执行动作",
            "超时预算要逐级递减，否则内层超时会超过外层等待",
          ],
          applications: ["登录与鉴权", "第三方接口调用", "大促容量保护"],
          pitfalls: ["限流阈值凭感觉设定", "熔断没有半开恢复", "降级返回错误数据却不标注"],
          method: "先确定核心链路与非核心功能，再给非核心功能准备降级。",
          exercise: "为一个依赖第三方的接口设计超时、重试、熔断与降级四件套，并写清触发条件。",
          checkpoint: "能说明限流与熔断在同一个故障场景里分别起什么作用。",
        },
      ],
      questionKeys: runtimeQuestions.map((question) => question.key),
    },
    {
      key: "be-delivery",
      title: "交付与可观测",
      weeks: "第 7-8 周",
      goal: "让服务可部署、可配置、可观测、可回滚。",
      outcome: "能设计一次不停服迁移与一套可用的观测方案。",
      topics: [
        {
          key: "be-config-secrets",
          title: "配置与秘密管理",
          summary: "配置与代码分离，缺失时明确失败而不是猜默认值。",
          concepts: ["环境变量", "密钥管理", "环境差异", "启动自检"],
          principles: [
            "秘密只从环境或密钥服务注入，绝不进仓库",
            "必须配置缺失时启动即失败，把错误提前到部署阶段",
            "环境差异应集中在一处配置，而不是散落在业务代码的条件分支里",
          ],
          applications: ["部署脚本", "本地开发", "密钥轮换"],
          pitfalls: ["把秘密写进默认值", "用 if (isProd) 散落各处", "轮换秘密后忘记重启或同步调用方"],
          method: "先列出配置清单并标注「必填/可选/有默认」，再写读取代码。",
          exercise: "为一个服务写配置清单，并实现启动自检：缺必填项时给出明确报错。",
          checkpoint: "能说明某次事故是否本可以被启动自检拦住。",
        },
        {
          key: "be-observability",
          title: "日志、指标与追踪",
          summary: "用结构化日志、低基数指标与请求 ID 把问题定位到具体一次请求。",
          concepts: ["结构化日志", "指标类型与标签", "requestId/链路", "告警阈值"],
          principles: [
            "日志给人看，指标给机器看：两者不要互相替代",
            "指标标签只放固定枚举，用户 ID 这类高基数值不能进标签",
            "每个请求带 requestId 并贯穿下游，才能把散落日志拼回一次调用",
          ],
          applications: ["故障定位", "容量与延迟监控", "成本分析"],
          pitfalls: ["日志里输出完整请求体（含隐私）", "用日志埋点算业务指标", "告警阈值没有基线"],
          method: "先写下「出问题时我想看什么数字」，再决定埋点。",
          exercise: "为一个导入任务设计日志与指标方案，写清失败率与耗时的计算口径。",
          checkpoint: "能说明为什么某个标签会导致时间序列基数爆炸。",
        },
        {
          key: "be-migration-deploy",
          title: "数据库迁移与滚动发布",
          summary: "让结构变更与代码发布可以独立进行，并随时可回滚。",
          concepts: ["只追加迁移", "在线加列/加约束", "回滚演练", "向后兼容发布"],
          principles: [
            "迁移与代码要向后兼容：新代码能读旧结构，旧代码能容忍新结构",
            "大表加列与加约束要拆步执行，避免长时间持锁",
            "回滚脚本必须演练过，未验证的回滚等于没有回滚",
          ],
          applications: ["表结构演进", "索引上线", "灰度发布"],
          pitfalls: ["直接改历史迁移文件", "一步加非空默认值上锁", "发布与迁移强绑定导致无法单独回滚"],
          method: "把变更拆成「兼容 → 迁移 → 收口」三步，每步都能独立回滚。",
          exercise: "为一个字段重命名设计三步方案，并说明每步的回滚动作。",
          checkpoint: "能说明为什么改写历史迁移会让环境结构分叉。",
        },
      ],
      questionKeys: deliveryQuestions.map((question) => question.key),
    },
  ],
  questions: [...apiDesignQuestions, ...dataAccessQuestions, ...runtimeQuestions, ...deliveryQuestions],
};
