import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

export const cloudPlatformTrack: LearningTrack = {
  slug: "cloud-platform",
  title: "云平台与容器",
  category: "云平台",
  level: "进阶",
  accent: "#1E88A8",
  softAccent: "#E6F4F8",
  icon: "cloud-outline",
  summary: "从云基础、容器与编排到存储、可观测性与成本安全，建立可上线的云上交付能力。",
  whyLearn: "云上交付的难点不在「会不会创建资源」，而在责任边界、权限、发布与成本。能否把这些讲清楚，决定系统是能长期运行，还是只能演示一次。",
  prerequisites: ["能在 Linux 上排障（日志、进程、网络）", "了解 HTTP、DNS 和基础网络概念"],
  studyMethod: ["每个资源都先写明责任边界和最小权限", "变更走声明式并保留可回滚版本", "把成本与可观测性当成一等验收项"],
  estimatedHours: 92,
  featured: true,
  sources: [
    {
      key: "az104",
      name: "Microsoft AZ-104 Azure Administrator",
      url: "https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator",
      license: "MIT",
      usage: "import",
      note: "微软官方管理员实验室：身份、网络、存储与计算的管理任务结构",
    },
    {
      key: "aks-labs",
      name: "Azure Samples AKS Labs",
      url: "https://github.com/Azure-Samples/aks-labs",
      license: "MIT",
      usage: "import",
      note: "AKS 集群动手实验：发布、扩缩、探针与排障",
    },
    {
      key: "kubernetes",
      name: "Kubernetes",
      url: "https://github.com/kubernetes/kubernetes",
      license: "Apache-2.0",
      usage: "reference",
      note: "上游实现与 API 约定参考，只保留外链不复制正文",
    },
    {
      key: "k8s-hard-way",
      name: "Kubernetes The Hard Way",
      url: "https://github.com/kelseyhightower/kubernetes-the-hard-way",
      license: "Apache-2.0",
      usage: "reference",
      note: "从零搭建控制面与数据面的步骤参考",
    },
  ],
  stages: [
    {
      key: "cloud-foundation",
      title: "云基础与责任边界",
      weeks: "第 1-2 周",
      goal: "理解服务模型、区域与身份体系，能说出每个资源由谁负责哪一部分。",
      outcome: "能设计一个带最小权限与可用区冗余的初始环境，并说明责任边界。",
      topics: [
        {
          key: "cloud-service-models",
          title: "服务模型与责任边界",
          summary: "IaaS、PaaS、SaaS 的差异与共享责任模型。",
          concepts: ["服务模型", "共享责任模型", "区域与可用区", "托管边界"],
          principles: [
            "云厂商负责「云本身的安全」，客户负责「云里的安全」，边界随服务模型移动",
            "选择服务模型的依据是团队愿意承担多少运维责任",
            "可用区隔离故障域，跨可用区部署是可用性的第一层保障",
          ],
          applications: ["环境选型", "灾备设计", "合规边界划分"],
          pitfalls: ["以为用了托管服务就不用管补丁与配置", "把可用区当成数据中心内的一台机器", "把成本与责任边界分开讨论"],
          method: "先画出「厂商负责什么、我们负责什么」，再据此选择服务模型。",
          exercise: "为一个 Web 应用列出所选服务模型下的责任清单，标出补丁、备份与权限各自归属。",
          checkpoint: "能逐项说明每个资源由谁负责，且没有「没人负责」的空白项。",
        },
        {
          key: "cloud-compute-network",
          title: "计算与网络基础",
          summary: "虚拟机规格、子网划分、安全组与负载均衡的基本取舍。",
          concepts: ["计算规格与弹性", "虚拟网络与子网", "安全组与规则方向", "负载均衡与健康检查"],
          principles: [
            "规格选择应由实测负载决定，而不是凭机型名称猜",
            "安全组规则要区分入站与出站，默认拒绝比默认允许安全",
            "负载均衡必须配合健康检查，否则会把流量送到坏实例",
          ],
          applications: ["Web 服务部署", "多层架构隔离", "灰度流量"],
          pitfalls: ["把数据库子网暴露到公网", "安全组规则写成 0.0.0.0/0 全放通", "健康检查路径返回 200 但业务已不可用"],
          method: "先划分网络分区与流量方向，再决定计算规格与均衡策略。",
          exercise: "设计两个子网加一个负载均衡的最小拓扑，写清每一条安全组规则的必要性。",
          checkpoint: "能画出请求进入系统的完整路径，并指出每一跳的访问控制。",
        },
        {
          key: "cloud-identity",
          title: "身份与最小权限",
          summary: "主体、角色、权限边界与凭证轮换。",
          concepts: ["主体与身份", "角色与策略", "权限边界", "凭证与轮换"],
          principles: [
            "权限授予角色而不是个人，人离开只需调整角色成员",
            "自动化流程用托管身份或短期凭证，不用长期密钥",
            "所有权限变更都要能回答「为什么需要」并留下审计记录",
          ],
          applications: ["按职责分权", "CI 部署身份", "跨团队资源隔离"],
          pitfalls: ["给自动化账号配超级管理员", "把长期密钥写进代码仓库", "权限只增不减"],
          method: "从「这个主体要完成什么任务」出发，只授予完成它所需的最小动作与范围。",
          exercise: "为只读排障与自动发布两个角色分别写出权限清单，并各自说明理由。",
          checkpoint: "能对任意一个权限条目说出它服务于哪个具体任务。",
        },
      ],
      questionKeys: [
        "cloud-service-models-single",
        "cloud-service-models-judge",
        "cloud-compute-network-single",
        "cloud-compute-network-judge",
        "cloud-identity-single",
        "cloud-identity-judge",
      ],
    },
    {
      key: "cloud-container",
      title: "容器与编排",
      weeks: "第 3-4 周",
      goal: "掌握镜像、运行时与声明式编排，能让服务稳定发布并优雅终止。",
      outcome: "能在集群上完成一次带探针、资源限制与回滚方案的发布。",
      topics: [
        {
          key: "cloud-container-basics",
          title: "容器与镜像",
          summary: "镜像分层、运行时隔离与标签策略。",
          concepts: ["镜像分层与缓存", "运行时隔离", "镜像仓库与标签", "不可变镜像"],
          principles: [
            "镜像应不可变：同一标签指向的内容不能变化",
            "分层顺序决定构建缓存命中率，变化频繁的层放后面",
            "容器只包含运行所需内容，构建工具不应进入运行镜像",
          ],
          applications: ["构建流水线", "多环境发布", "回滚到上一个镜像"],
          pitfalls: ["用 latest 标签部署生产", "把密钥打包进镜像", "镜像体积过大拖慢扩缩"],
          method: "先固定基础镜像与依赖层，再让业务代码层保持最小变更。",
          exercise: "为一个服务写出多阶段构建，并说明哪些层会被缓存复用。",
          checkpoint: "能指出每次发布时哪些层会重建、哪些会被复用。",
        },
        {
          key: "cloud-k8s-workloads",
          title: "编排与工作负载",
          summary: "声明式模型、控制器与常见工作负载的选择。",
          concepts: ["声明式与期望状态", "控制器循环", "无状态与有状态负载", "服务发现"],
          principles: [
            "声明式意味着描述期望状态，由控制器持续把实际状态拉回来",
            "无状态负载可随意替换实例，有状态负载需要稳定的身份与存储",
            "服务发现把实例列表的变动与调用方解耦",
          ],
          applications: ["无状态 API", "定时任务", "有状态中间件"],
          pitfalls: ["把有状态服务塞进无状态工作负载", "手工改实例导致期望状态漂移", "忽略就绪探针导致流量提前进入"],
          method: "先判断负载是否有状态，再选择工作负载类型与存储方案。",
          exercise: "为 API 与数据库分别选择工作负载类型，并说明各自的身份与存储需求。",
          checkpoint: "能解释一次实例被替换时，声明式模型如何自动收敛回期望状态。",
        },
        {
          key: "cloud-k8s-ops",
          title: "发布、探针与回滚",
          summary: "滚动更新、探针语义与资源请求限制。",
          concepts: ["滚动更新与批次", "存活与就绪探针", "资源请求与限制", "优雅终止"],
          principles: [
            "就绪探针决定何时接流量，存活探针决定何时重启，两者语义不能混用",
            "资源请求影响调度，限制影响运行上限，只设限不设请求会导致调度失真",
            "优雅终止需要应用配合：接到信号后先停止接新请求再处理完存量",
          ],
          applications: ["灰度发布", "扩缩容", "故障自愈"],
          pitfalls: ["存活探针依赖外部依赖导致级联重启", "限制设得过低触发频繁 OOM", "终止宽限期短于真实处理时间"],
          method: "先明确「什么时候可以接流量」「什么时候必须重启」，再设计探针与资源参数。",
          exercise: "为一个 API 设计探针与资源参数，并写出回滚到上一版本的操作与判定标准。",
          checkpoint: "能说明发布过程中新实例何时接流量、旧实例何时退出。",
        },
      ],
      questionKeys: [
        "cloud-container-basics-single",
        "cloud-container-basics-judge",
        "cloud-k8s-workloads-single",
        "cloud-k8s-workloads-judge",
        "cloud-k8s-ops-single",
        "cloud-k8s-ops-judge",
      ],
    },
    {
      key: "cloud-storage-data",
      title: "存储与数据接入",
      weeks: "第 5-6 周",
      goal: "按访问模式选择存储形态，管好生命周期、缓存与接入层。",
      outcome: "能为一个应用设计存储、缓存与接入层方案，并说明一致性与失效策略。",
      topics: [
        {
          key: "cloud-object-block",
          title: "对象存储与块存储",
          summary: "对象、块与文件存储的适用场景与生命周期管理。",
          concepts: ["对象存储", "块存储", "文件存储", "生命周期与分层"],
          principles: [
            "对象存储适合海量非结构化数据，通过 HTTP 接口访问，不适合做数据库文件系统",
            "块存储提供低延迟随机读写，但需要挂载且通常绑定单个实例",
            "生命周期策略让冷数据自动下沉到低成本层，是成本治理的第一手段",
          ],
          applications: ["静态资源与备份", "数据库数据盘", "多实例共享配置"],
          pitfalls: ["把对象存储当成本地文件系统使用", "不设生命周期导致冷数据长期占高价层", "块存储快照未验证可恢复"],
          method: "先判断访问模式是顺序大文件还是随机小 IO，再选择存储形态。",
          exercise: "为一个内容型应用分配存储：静态资源、数据库数据、日志归档各选一种并说明理由。",
          checkpoint: "能说出每种数据选择的存储形态，以及它的成本与访问代价。",
        },
        {
          key: "cloud-db-cache",
          title: "托管数据库与缓存",
          summary: "托管实例、只读副本与缓存失效策略。",
          concepts: ["托管数据库", "只读副本", "连接管理", "缓存与失效"],
          principles: [
            "只读副本分摊读流量，但复制延迟意味着读到的是稍旧数据",
            "连接是有限资源，应用侧必须限制池大小并复用连接",
            "缓存必须同时设计失效策略，否则会长期返回过期数据",
          ],
          applications: ["读多写少业务", "热点数据加速", "报表查询隔离"],
          pitfalls: ["在只读副本上读刚写入的数据", "缓存无过期时间导致永久脏数据", "连接池按实例数放大拖垮数据库"],
          method: "先明确哪些读可以容忍延迟，再决定副本与缓存的边界。",
          exercise: "为商品详情页设计缓存与副本策略，并说明写入后如何让缓存失效。",
          checkpoint: "能指出哪些查询走副本、哪些走主库，以及缓存何时必须失效。",
        },
        {
          key: "cloud-cdn-dns",
          title: "CDN 与 DNS 接入",
          summary: "DNS 记录与 TTL、缓存与回源、HTTPS 证书管理。",
          concepts: ["记录类型与 TTL", "缓存与回源", "证书与 HTTPS", "灰度与切流"],
          principles: [
            "TTL 决定变更生效速度，故障切换场景应提前调小",
            "缓存命中率决定回源压力，回源带宽是成本与稳定性关键",
            "证书续期必须自动化，人工续期迟早会过期",
          ],
          applications: ["静态资源加速", "多地域接入", "故障切换"],
          pitfalls: ["切换前没调小 TTL 导致长时间不一致", "缓存未区分动态内容导致脏数据", "证书过期未告警"],
          method: "先规划域名与记录，再设计缓存规则并留出切流窗口。",
          exercise: "为一个站点规划 DNS 与缓存策略，并写出一次故障切换的前置动作。",
          checkpoint: "能说明一次域名切换从改记录到全部生效需要多久、为什么。",
        },
      ],
      questionKeys: [
        "cloud-object-block-single",
        "cloud-object-block-judge",
        "cloud-db-cache-single",
        "cloud-db-cache-judge",
        "cloud-cdn-dns-single",
        "cloud-cdn-dns-judge",
      ],
    },
    {
      key: "cloud-reliability",
      title: "可观测性、IaC 与成本",
      weeks: "第 7-8 周",
      goal: "把可观测性、基础设施即代码与成本安全治理落到日常流程里。",
      outcome: "能为一个线上服务给出 SLO、告警分级、IaC 变更流程与成本归因方案。",
      topics: [
        {
          key: "cloud-observability",
          title: "可观测性与告警",
          summary: "指标、日志、追踪的分工，以及 SLO 与告警分级。",
          concepts: ["指标与维度", "日志与结构化", "分布式追踪", "SLO 与错误预算"],
          principles: [
            "指标回答「好不好」，日志回答「发生了什么」，追踪回答「慢在哪一段」",
            "告警应对着用户可感知的症状，而不是对着单个内部指标",
            "SLO 是取舍依据：预算耗尽时优先恢复稳定性而不是继续发布",
          ],
          applications: ["容量与性能监控", "故障定位", "发布准入"],
          pitfalls: ["告警过多导致真实故障被淹没", "只看平均值忽略长尾延迟", "日志无关联标识无法串联请求"],
          method: "先定义用户可感知的指标，再倒推需要采集的指标、日志与追踪。",
          exercise: "为一个 API 定义 SLO 与三条分级告警，并说明每条告警的处置动作。",
          checkpoint: "能说明一条告警为什么值得打断值班，以及它的处置路径。",
        },
        {
          key: "cloud-iac",
          title: "基础设施即代码",
          summary: "声明式资源、状态管理与变更评审。",
          concepts: ["声明式资源定义", "状态与漂移", "模块与复用", "变更评审与预览"],
          principles: [
            "资源变更必须通过代码，手工修改会造成状态漂移",
            "每次变更先预览差异再应用，预览结果是评审依据",
            "销毁与替换类操作要显式确认，不能和常规变更混在一起自动执行",
          ],
          applications: ["环境复制", "权限与网络配置", "审计追溯"],
          pitfalls: ["控制台手工改完不同步回代码", "预览结果不评审直接应用", "把敏感值写进代码仓库"],
          method: "先让所有资源进入代码，再用预览—评审—应用的固定流程推进变更。",
          exercise: "把一个网络与计算资源写成声明式定义，并演示一次预览差异。",
          checkpoint: "能说明当前环境与代码之间是否存在漂移，以及如何消除。",
        },
        {
          key: "cloud-cost-security",
          title: "成本与安全治理",
          summary: "成本归因、权限复核与网络边界审计。",
          concepts: ["成本归因与标签", "闲置资源识别", "权限复核", "边界与审计"],
          principles: [
            "成本必须先能归因到团队或业务，才谈得上优化",
            "闲置资源的识别是成本治理中见效最快的动作",
            "权限与网络边界应定期复核，只增不减的授权迟早失控",
          ],
          applications: ["月度成本复盘", "季度权限审计", "合规检查"],
          pitfalls: ["无标签导致成本无法归因", "长期保留已下线业务的资源", "审计日志未保存或未审查"],
          method: "先建立标签与归因口径，再按「闲置—规格—架构」顺序优化。",
          exercise: "为一个月度账单做归因分析，列出三条可执行的优化动作与预期收益。",
          checkpoint: "能说出本月成本的构成与下一步优化动作，而不是只报总额。",
        },
      ],
      questionKeys: [
        "cloud-observability-single",
        "cloud-observability-judge",
        "cloud-iac-single",
        "cloud-iac-judge",
        "cloud-cost-security-single",
        "cloud-cost-security-judge",
      ],
    },
  ],
  questions: [
    ...topicQuestionPair(
      "cloud-service-models",
      "cloud-foundation",
      {
        stem: "把数据库换成云厂商的托管实例后，哪部分责任仍然在客户侧？",
        options: ["机房供电", "数据库引擎的官方补丁", "数据模型、访问控制与备份策略", "物理硬盘更换"],
        answer: "C",
        explanation: "托管服务上移了基础设施与引擎维护，但数据、权限、备份与配置仍由客户负责，责任边界随模型移动而不消失。",
        difficulty: "medium",
        tags: ["共享责任", "托管服务"],
        sourceKey: "az104",
      },
      {
        stem: "跨可用区部署的主要目的是隔离故障域、提高可用性。",
        answer: true,
        explanation: "可用区之间相互隔离供电与网络，跨区部署能在单区故障时继续提供服务。",
        difficulty: "easy",
        tags: ["可用区", "可用性"],
        sourceKey: "az104",
      }
    ),
    ...topicQuestionPair(
      "cloud-compute-network",
      "cloud-foundation",
      {
        stem: "负载均衡已配置但流量仍打到故障实例，最可能缺少什么？",
        options: ["更多实例", "有效的健康检查", "更大的规格", "更多安全组规则"],
        answer: "B",
        explanation: "负载均衡靠健康检查判断实例可用性；检查缺失或路径不反映真实业务状态时，坏实例仍会收到流量。",
        difficulty: "medium",
        tags: ["负载均衡", "健康检查"],
        sourceKey: "az104",
      },
      {
        stem: "数据库子网开放公网入站，只要密码足够复杂就可以接受。",
        answer: false,
        explanation: "暴露公网会显著扩大攻击面，正确做法是让数据库只在内网可达，通过白名单与跳板访问。",
        difficulty: "easy",
        tags: ["网络边界", "安全组"],
        sourceKey: "aks-labs",
      }
    ),
    ...topicQuestionPair(
      "cloud-identity",
      "cloud-foundation",
      {
        stem: "自动发布流水线访问云资源，推荐使用哪种凭证？",
        options: ["管理员账号密码", "长期访问密钥写在配置里", "托管身份或短期凭证", "个人账号的访问密钥"],
        answer: "C",
        explanation: "托管身份与短期凭证自动轮换、无需落盘，能避免长期密钥泄漏与忘记轮换的问题。",
        difficulty: "medium",
        tags: ["身份", "凭证"],
        sourceKey: "az104",
      },
      {
        stem: "把权限授予角色而不是个人，能简化人员变动时的权限维护。",
        answer: true,
        explanation: "角色把权限与职责绑定，人员调整只需变更角色成员，避免遗留个人权限。",
        difficulty: "easy",
        tags: ["角色", "最小权限"],
        sourceKey: "az104",
      }
    ),
    ...topicQuestionPair(
      "cloud-container-basics",
      "cloud-container",
      {
        stem: "生产环境用 latest 标签部署，最主要的问题是什么？",
        options: ["镜像更大", "同一标签指向的内容会变化，无法复现与回滚", "构建更慢", "无法推送到仓库"],
        answer: "B",
        explanation: "标签不变性是可复现部署的前提；latest 会漂移，导致回滚时拿到的其实是另一个镜像。",
        difficulty: "easy",
        tags: ["镜像标签", "可复现"],
        sourceKey: "aks-labs",
      },
      {
        stem: "多阶段构建可以把构建工具留在构建阶段，使运行镜像更小。",
        answer: true,
        explanation: "只把运行所需产物复制到最终镜像，能减小体积、降低攻击面并加快扩缩。",
        difficulty: "easy",
        tags: ["多阶段构建", "镜像体积"],
        sourceKey: "aks-labs",
      }
    ),
    ...topicQuestionPair(
      "cloud-k8s-workloads",
      "cloud-container",
      {
        stem: "声明式编排的最大特点是什么？",
        options: ["每次都要手工执行命令", "描述期望状态，由控制器持续收敛实际状态", "只能部署无状态服务", "不需要任何配置"],
        answer: "B",
        explanation: "声明式模型不描述步骤而描述目标，控制器循环会不断把实际状态修正为期望状态，从而自愈并抵抗漂移。",
        difficulty: "medium",
        tags: ["声明式", "控制器"],
        sourceKey: "kubernetes",
      },
      {
        stem: "需要稳定网络标识与持久存储的服务，应使用有状态工作负载。",
        answer: true,
        explanation: "有状态工作负载为实例提供稳定身份与专属存储，适合数据库、消息队列等需要持久身份的服务。",
        difficulty: "medium",
        tags: ["工作负载", "有状态"],
        sourceKey: "k8s-hard-way",
      }
    ),
    ...topicQuestionPair(
      "cloud-k8s-ops",
      "cloud-container",
      {
        stem: "就绪探针与存活探针的语义区别是什么？",
        options: ["没有区别", "就绪决定是否接流量，存活决定是否重启", "存活用于接流量", "就绪只用于日志"],
        answer: "B",
        explanation: "就绪探针不通过时把实例从服务端点摘除，存活探针不通过时重启实例；混用会造成流量进入未就绪实例或依赖抖动引发级联重启。",
        difficulty: "medium",
        tags: ["探针", "发布"],
        sourceKey: "aks-labs",
      },
      {
        stem: "只设置资源限制而不设置资源请求，会导致调度依据失真。",
        answer: true,
        explanation: "调度以请求值为依据；缺失请求时调度器可能把大量实例挤在同一节点，运行期再触发资源争抢。",
        difficulty: "medium",
        tags: ["资源请求", "调度"],
        sourceKey: "kubernetes",
      }
    ),
    ...topicQuestionPair(
      "cloud-object-block",
      "cloud-storage-data",
      {
        stem: "存放海量静态图片与备份归档，最合适的是哪种存储？",
        options: ["块存储", "对象存储", "内存缓存", "实例本地盘"],
        answer: "B",
        explanation: "对象存储按 HTTP 接口访问、容量近乎无限，配合生命周期分层能以低成本长期保存海量非结构化数据。",
        difficulty: "easy",
        tags: ["对象存储", "生命周期"],
        sourceKey: "az104",
      },
      {
        stem: "对象存储适合直接作为数据库的数据目录挂载使用。",
        answer: false,
        explanation: "对象存储通过 HTTP 接口访问，缺少低延迟随机写与文件锁语义，不适合承载数据库文件系统。",
        difficulty: "medium",
        tags: ["对象存储", "块存储"],
        sourceKey: "az104",
      }
    ),
    ...topicQuestionPair(
      "cloud-db-cache",
      "cloud-storage-data",
      {
        stem: "用户刚提交写入就立刻从只读副本读取，可能遇到什么问题？",
        options: ["连接被拒绝", "读到尚未复制过去的旧数据", "副本自动升为主库", "查询被缓存"],
        answer: "B",
        explanation: "副本存在复制延迟，刚提交的写入未必已同步；对一致性敏感的读必须走主库或采用读写一致策略。",
        difficulty: "medium",
        tags: ["只读副本", "复制延迟"],
        sourceKey: "az104",
      },
      {
        stem: "缓存必须同时设计失效策略，否则会长期返回过期数据。",
        answer: true,
        explanation: "只写不失效的缓存会一直返回旧值；需要过期时间或写入时主动失效，并考虑失效失败时的兜底。",
        difficulty: "easy",
        tags: ["缓存", "失效"],
        sourceKey: "aks-labs",
      }
    ),
    ...topicQuestionPair(
      "cloud-cdn-dns",
      "cloud-storage-data",
      {
        stem: "计划做一次故障切换，提前最应该做什么？",
        options: ["提高缓存命中率", "把 TTL 调小，缩短变更生效时间", "增加回源带宽", "更换证书"],
        answer: "B",
        explanation: "TTL 决定解析缓存多久更新；切换前调小 TTL，才能在切换时让新记录快速生效。",
        difficulty: "medium",
        tags: ["DNS", "TTL"],
        sourceKey: "az104",
      },
      {
        stem: "HTTPS 证书续期应尽量自动化，人工续期容易因疏忽导致过期。",
        answer: true,
        explanation: "自动化续期配合到期告警，可以避免证书过期造成的整站不可访问事故。",
        difficulty: "easy",
        tags: ["证书", "HTTPS"],
        sourceKey: "az104",
      }
    ),
    ...topicQuestionPair(
      "cloud-observability",
      "cloud-reliability",
      {
        stem: "告警设计最应该对齐什么？",
        options: ["内部单个指标阈值", "用户可感知的症状与 SLO", "实例数量变化", "日志条数"],
        answer: "B",
        explanation: "面向用户症状的告警才值得打断值班；对内部指标逐一告警会制造噪声，让真正的故障被淹没。",
        difficulty: "medium",
        tags: ["告警", "SLO"],
        sourceKey: "az104",
      },
      {
        stem: "只看平均延迟会掩盖长尾用户的糟糕体验。",
        answer: true,
        explanation: "平均值会被大量快请求拉低，必须同时观察分位数，才能真正反映慢请求对用户的影响。",
        difficulty: "medium",
        tags: ["延迟", "分位数"],
        sourceKey: "kubernetes",
      }
    ),
    ...topicQuestionPair(
      "cloud-iac",
      "cloud-reliability",
      {
        stem: "有人在控制台手工改了一个资源，会导致什么后果？",
        options: ["立即报错", "代码与环境产生漂移，下次应用可能把它改回去或删除", "资源自动同步回代码", "账单翻倍"],
        answer: "B",
        explanation: "状态漂移会让声明式定义与环境不一致，后续应用变更时可能覆盖手工修改甚至重建资源。",
        difficulty: "medium",
        tags: ["漂移", "IaC"],
        sourceKey: "az104",
      },
      {
        stem: "变更前先查看预览差异，是基础设施即代码流程的必要一步。",
        answer: true,
        explanation: "预览把「将要发生什么」变成可评审的证据，能在应用到环境前发现销毁与替换类破坏性操作。",
        difficulty: "easy",
        tags: ["预览", "变更评审"],
        sourceKey: "az104",
      }
    ),
    ...topicQuestionPair(
      "cloud-cost-security",
      "cloud-reliability",
      {
        stem: "成本治理中，见效最快的动作通常是哪一个？",
        options: ["更换云厂商", "识别并清理闲置资源", "购买更多预留", "缩小所有实例规格"],
        answer: "B",
        explanation: "闲置的未挂载磁盘、过期快照与无人使用的实例没有业务价值，清理即可直接削掉成本且无风险。",
        difficulty: "medium",
        tags: ["成本", "闲置资源"],
        sourceKey: "az104",
      },
      {
        stem: "权限复核应该周期性执行，因为授权往往只增不减。",
        answer: true,
        explanation: "随着人员与项目变动，历史授权会累积成过度权限，定期复核是控制这一风险的主要手段。",
        difficulty: "easy",
        tags: ["权限复核", "审计"],
        sourceKey: "az104",
      }
    ),
  ],
};
