import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

export const databaseTrack: LearningTrack = {
  slug: "database",
  title: "数据库基础",
  category: "数据库",
  level: "入门",
  accent: "#2F6FB3",
  softAccent: "#E9F1FA",
  icon: "server-outline",
  summary: "从关系模型与 SQL 到索引、事务、建模与运维，建立可写、可查、可排障的数据库能力。",
  whyLearn: "业务数据几乎都落在关系数据库上。能不能写出正确且高效的 SQL、能不能讲清索引与事务，直接决定功能是否算对、线上是否稳定。",
  prerequisites: ["能用客户端连接一个数据库并执行语句", "了解表、行、列的基本概念"],
  studyMethod: ["每个查询先在小数据上核对行数与粒度", "索引改动前后都要看执行计划", "用故障场景训练事务、死锁与恢复"],
  estimatedHours: 96,
  featured: true,
  sources: [
    {
      key: "cmu-bustub",
      name: "CMU 15-445 BusTub",
      url: "https://github.com/cmu-db/bustub",
      license: "MIT",
      usage: "import",
      note: "教学数据库引擎：缓冲池、B-Tree 索引与查询执行的实现参考",
    },
    {
      key: "postgresql",
      name: "PostgreSQL",
      url: "https://github.com/postgres/postgres",
      license: "PostgreSQL License",
      usage: "reference",
      note: "官方实现与回归测试，SQL 语义和查询计划的行为依据",
    },
    {
      key: "sqlite",
      name: "SQLite",
      url: "https://github.com/sqlite/sqlite",
      license: "Public Domain (SQLite Blessing)",
      usage: "reference",
      note: "精简 SQL 引擎实现，用于理解 B-Tree 组织与查询计划",
    },
  ],
  stages: [
    {
      key: "db-relational",
      title: "关系模型与 SQL 基础",
      weeks: "第 1-2 周",
      goal: "理解关系模型、约束与集合语义，写出结果可手工核对的基础查询。",
      outcome: "能设计带完整约束的初始表结构，并为每个查询说明预期行数与粒度。",
      topics: [
        {
          key: "db-relational-model",
          title: "表、键与约束",
          summary: "表、主键、外键与约束如何表达业务规则。",
          concepts: ["关系与元组", "主键与唯一约束", "外键与引用完整性", "NOT NULL 与 CHECK"],
          principles: [
            "约束是数据库层的业务规则，不能只靠应用校验",
            "主键表达一行的身份，必须唯一且不允许为空",
            "外键声明引用关系，删除与更新行为必须显式设计",
          ],
          applications: ["订单与订单明细", "用户与角色", "多对多关联表"],
          pitfalls: ["用可能变化的业务字段当主键", "外键列没有索引导致删除变慢", "把 NULL 当成业务默认值使用"],
          method: "先写清实体与标识，再把每条业务规则落到一条具体约束上。",
          exercise: "为用户、订单、明细三张表写出建表语句，标出主键、外键与唯一约束。",
          checkpoint: "能指出每条业务规则由哪条约束保证，并说出违反时的报错信息。",
        },
        {
          key: "db-select-join",
          title: "查询与连接",
          summary: "SELECT 的逻辑执行顺序、各种 JOIN 与集合语义。",
          concepts: ["逻辑执行顺序", "内连接与左连接", "半连接与反连接", "集合运算"],
          principles: [
            "连接前必须确认两侧连接键的粒度一致",
            "LEFT JOIN 保留左表全部行，右表无匹配时相关列为 NULL",
            "右表的过滤条件写在 ON 与写在 WHERE 会得到不同结果",
          ],
          applications: ["报表取数", "数据对账", "存在性判断"],
          pitfalls: ["多对多连接导致行数膨胀", "把右表过滤写在 WHERE 让左连接退化成内连接", "用不等号判断存在性"],
          method: "先确定目标粒度，再为每一步写出预期行数并逐条核对。",
          exercise: "找出有订单但从未支付的用户，写出两种写法并比较执行计划。",
          checkpoint: "任意一个连接查询都能说明结果行数的上界与来源。",
        },
        {
          key: "db-aggregate-window",
          title: "聚合与窗口函数",
          summary: "分组聚合、HAVING 与窗口函数在保留明细的前提下做统计。",
          concepts: ["聚合与分组", "WHERE 与 HAVING", "窗口分区与排序", "排名与偏移函数"],
          principles: [
            "WHERE 在分组前过滤行，HAVING 在分组后过滤组",
            "窗口函数不折叠行，在同一分区内计算并保留明细",
            "排名函数对并列值的处理各不相同，选择取决于业务口径",
          ],
          applications: ["日活与留存", "同期群分析", "取每组最新一条"],
          pitfalls: ["把聚合结果与明细列混在一起使用", "RANK 与 ROW_NUMBER 用错导致序号跳变", "窗口缺少确定的排序导致结果不稳定"],
          method: "先想清楚要不要保留明细行，再决定用聚合还是窗口函数。",
          exercise: "用窗口函数取出每个用户最近一次登录，并统计当日登录排名。",
          checkpoint: "能解释同一条需求用聚合与窗口两种写法的结果差异。",
        },
      ],
      questionKeys: [
        "db-relational-model-single",
        "db-relational-model-judge",
        "db-select-join-single",
        "db-select-join-judge",
        "db-aggregate-window-single",
        "db-aggregate-window-judge",
      ],
    },
    {
      key: "db-index",
      title: "索引与查询性能",
      weeks: "第 3-4 周",
      goal: "理解索引结构与执行计划，能用计划而不是感觉判断性能问题。",
      outcome: "能为给定查询设计索引，并用执行计划证明改造有效。",
      topics: [
        {
          key: "db-index-basics",
          title: "索引结构与选择性",
          summary: "B-Tree 索引的结构、复合索引列顺序与选择性。",
          concepts: ["B-Tree 与顺序存储", "复合索引列顺序", "最左前缀", "覆盖索引"],
          principles: [
            "索引用额外写入与空间换取更短的读取路径",
            "复合索引只有命中左前缀才能用于定位",
            "选择性高的列放在复合索引前面通常更有价值",
          ],
          applications: ["主键与唯一键", "高频过滤条件", "排序与分页"],
          pitfalls: ["为低选择性列单独建索引", "在列上套函数导致索引失效", "索引过多拖慢写入"],
          method: "按查询的过滤与排序列设计复合索引，再用执行计划验证是否被使用。",
          exercise: "为按创建时间倒序分页的查询设计索引，并对比改造前后的计划。",
          checkpoint: "能说明一个索引服务哪些查询，以及为什么不服务另外一些。",
        },
        {
          key: "db-explain",
          title: "执行计划与代价",
          summary: "读执行计划，判断扫描方式、连接算法与行数估算偏差。",
          concepts: ["计划树与节点", "扫描方式", "连接算法", "估算行数与实际行数"],
          principles: [
            "先看扫描方式再谈优化，顺序扫描在小表上未必是问题",
            "估算与实际行数偏差很大时，通常说明统计信息已过期",
            "优化结论必须基于同一份计划输出的前后对比",
          ],
          applications: ["慢查询定位", "索引改造验证", "容量评估"],
          pitfalls: ["只看总耗时不看计划节点", "忽略统计信息更新导致计划漂移", "在小表上过度优化"],
          method: "先拿到计划与真实行数，再判断瓶颈在扫描、连接还是排序。",
          exercise: "对一条慢查询输出执行计划，标出偏差最大的节点并解释原因。",
          checkpoint: "能指认计划中代价最高的节点，并给出下一步的验证方式。",
        },
        {
          key: "db-query-tuning",
          title: "查询改写与调优",
          summary: "用改写、分区裁剪与批处理替代盲目加索引。",
          concepts: ["谓词下推", "分区裁剪", "批量与分批", "避免 N+1 查询"],
          principles: [
            "能减少处理数据量的改写，收益通常大于单纯加索引",
            "分页必须带稳定且唯一的排序键，否则会漏行或重复",
            "批处理要同时考虑事务粒度与内存占用",
          ],
          applications: ["大表分页", "批量导入", "报表优化"],
          pitfalls: ["用大 OFFSET 深分页", "在循环里逐条查询", "一次性把整表加载进内存"],
          method: "先量化要处理的数据量，再选择裁剪、批处理或改写的组合。",
          exercise: "把深分页查询改写为基于游标的分页，并对比两次扫描的行数。",
          checkpoint: "能说出一条查询优化前后的处理数据量差异，而不是只报耗时变化。",
        },
      ],
      questionKeys: [
        "db-index-basics-single",
        "db-index-basics-judge",
        "db-explain-single",
        "db-explain-judge",
        "db-query-tuning-single",
        "db-query-tuning-judge",
      ],
    },
    {
      key: "db-transaction",
      title: "事务与并发",
      weeks: "第 5-6 周",
      goal: "理解事务边界、隔离级别与锁，能设计可重试的并发写路径。",
      outcome: "能为并发场景划定事务边界，并说明隔离级别挡不住时需要补什么。",
      topics: [
        {
          key: "db-acid",
          title: "事务与 ACID",
          summary: "事务边界、原子性与一致性不变量的落地方式。",
          concepts: ["事务边界", "原子性与回滚", "一致性不变量", "持久性与提交"],
          principles: [
            "事务应围绕一个需要保持一致性的业务不变量来划定",
            "提交之后才是持久结果，回滚必须释放全部中间状态",
            "事务越长，持锁时间与回滚代价越高",
          ],
          applications: ["转账与扣减库存", "订单状态流转", "批量写入"],
          pitfalls: ["在事务里调用外部接口形成长事务", "把多个不变量塞进同一个事务", "没有为回滚后的情况设计重试"],
          method: "先写下必须一起成功或一起失败的那一件事，再据此划定事务边界。",
          exercise: "为扣减库存并生成订单设计事务边界，说明回滚时的最终一致性。",
          checkpoint: "能画出事务内每一步的状态，并指出异常发生时数据库停在哪里。",
        },
        {
          key: "db-isolation",
          title: "隔离级别与异常",
          summary: "四种隔离级别与脏读、不可重复读、幻读之间的关系。",
          concepts: ["读已提交", "可重复读", "串行化", "快照读与当前读"],
          principles: [
            "隔离级别交换的是并发度与一致性的平衡",
            "可重复读下快照读不阻塞写入，但当前读仍会产生冲突",
            "串行化不是免费的，序列化失败的重试策略必须一起设计",
          ],
          applications: ["读多写少的报表", "库存扣减", "账户余额"],
          pitfalls: ["以为默认隔离级别能挡住所有异常", "混用快照读与当前读导致判断失效", "在串行化下不处理序列化失败"],
          method: "先列出业务不能容忍的异常，再选能挡住这些异常的隔离级别。",
          exercise: "用两个会话复现不可重复读，再切到可重复读观察行为差异。",
          checkpoint: "能说明当前级别已挡住哪些异常、哪些仍需应用层处理。",
        },
        {
          key: "db-lock-deadlock",
          title: "锁、死锁与重试",
          summary: "锁的类型、加锁顺序与死锁的检测和重试。",
          concepts: ["行锁与表锁", "共享锁与排他锁", "加锁顺序", "死锁检测与重试"],
          principles: [
            "死锁通常来自不同事务的不一致加锁顺序",
            "数据库会检测死锁并牺牲其中一个事务",
            "被牺牲的事务必须在应用层重试，且要带退避",
          ],
          applications: ["并发扣减", "多表更新", "批量任务"],
          pitfalls: ["不做退避地疯狂重试造成雪崩", "长事务持锁等待外部输入", "忽略锁等待超时"],
          method: "统一资源加锁顺序，并为每个可能被牺牲的事务准备退避重试。",
          exercise: "构造一个死锁场景，从数据库日志找出被牺牲的事务，再实现退避重试。",
          checkpoint: "能定位死锁涉及的事务与语句，并说明重试的边界与上限。",
        },
      ],
      questionKeys: [
        "db-acid-single",
        "db-acid-judge",
        "db-isolation-single",
        "db-isolation-judge",
        "db-lock-deadlock-single",
        "db-lock-deadlock-judge",
      ],
    },
    {
      key: "db-modeling-ops",
      title: "建模、迁移与运维",
      weeks: "第 7-8 周",
      goal: "把建模取舍、迁移安全与备份恢复串成可上线的数据库工作流。",
      outcome: "能独立完成一次带回滚方案的迁移，并说清备份与恢复的真实能力。",
      topics: [
        {
          key: "db-normalization",
          title: "范式与建模取舍",
          summary: "范式化与反范式化的边界，以及字段设计的长期成本。",
          concepts: ["函数依赖", "第三范式", "反范式冗余", "宽表与聚合表"],
          principles: [
            "范式化减少更新异常，冗余换取查询效率",
            "每个冗余字段都必须明确由谁维护、何时更新",
            "读写比例决定冗余是否值得，而不是个人偏好",
          ],
          applications: ["业务主表设计", "报表宽表", "标签与统计字段"],
          pitfalls: ["无条件反范式导致数据不一致", "把统计值当成业务事实", "字段类型与长度随手选取"],
          method: "先按范式化建模，再只对确认的高频读路径做有维护方的冗余。",
          exercise: "为课程与报名设计范式化模型，再指出哪些字段可以安全冗余。",
          checkpoint: "能为每个冗余字段指明更新来源与一致性校验方式。",
        },
        {
          key: "db-migration-safe",
          title: "安全迁移与在线变更",
          summary: "让迁移可回滚、可观测，并对线上影响可控。",
          concepts: ["迁移文件与版本", "在线 DDL", "双写与数据回填", "回滚方案"],
          principles: [
            "迁移只追加不修改，已应用的文件不能再改",
            "加列与建索引必须先评估锁与耗时",
            "结构变更与数据回填分成两步，每一步都能重复执行",
          ],
          applications: ["新增字段", "大表加索引", "字段拆分与改名"],
          pitfalls: ["在业务高峰直接改表结构", "迁移里混入不可重复执行的数据修复", "没有准备回滚脚本"],
          method: "把一次上线拆成可独立验证与回滚的小步，每步都能安全重跑。",
          exercise: "为一个大表增加非空字段设计三步迁移，并写出每一步的回滚。",
          checkpoint: "能说明迁移中途失败时数据库停在哪一步、如何继续。",
        },
        {
          key: "db-backup-recovery",
          title: "备份、恢复与容量",
          summary: "备份策略、恢复演练，以及容量与慢查询的持续监控。",
          concepts: ["全量与增量备份", "时间点恢复", "恢复演练", "容量与慢查询监控"],
          principles: [
            "没有演练过的备份不算可用备份",
            "恢复目标决定备份频率与保留策略",
            "容量问题要区分是数据增长还是查询放大",
          ],
          applications: ["灾备", "误删恢复", "容量规划"],
          pitfalls: ["只备份不校验", "在生产库上做恢复演练", "只看磁盘不看连接数与慢查询"],
          method: "先写下可接受的数据丢失时间与恢复时间，再倒推备份与演练方案。",
          exercise: "在演练库写一份恢复步骤，并记录实际恢复耗时与卡点。",
          checkpoint: "能报出最近一次恢复演练的时间与结果，而不是只报备份已开启。",
        },
      ],
      questionKeys: [
        "db-normalization-single",
        "db-normalization-judge",
        "db-migration-safe-single",
        "db-migration-safe-judge",
        "db-backup-recovery-single",
        "db-backup-recovery-judge",
      ],
    },
  ],
  questions: [
    ...topicQuestionPair(
      "db-relational-model",
      "db-relational",
      {
        stem: "订单表用「下单时间 + 用户名」当主键，最主要的风险是什么？",
        options: ["存储占用更大", "业务字段可能变化且不保证唯一，身份不稳定", "无法建立索引", "不能写 SQL 查询"],
        answer: "B",
        explanation: "主键要表达一行的稳定身份；业务字段会变、可能重复，用它当主键会让引用方被迫跟着改。",
        difficulty: "easy",
        tags: ["主键", "约束"],
        sourceKey: "cmu-bustub",
      },
      {
        stem: "把业务规则写成数据库约束，可以让应用层少做一次校验。",
        answer: true,
        explanation: "约束在数据库层兜底，能挡住绕过应用代码的写入路径，是业务规则的最终防线。",
        difficulty: "easy",
        tags: ["约束", "数据完整性"],
        sourceKey: "postgresql",
      }
    ),
    ...topicQuestionPair(
      "db-select-join",
      "db-relational",
      {
        stem: "想保留左表全部用户、只要右表当月的订单，过滤条件应写在哪里？",
        options: ["WHERE 子句", "ON 子句", "HAVING 子句", "ORDER BY 子句"],
        answer: "B",
        explanation: "写在 ON 表示「匹配时只关联当月订单」，左表行仍全部保留；写在 WHERE 会把不匹配的 NULL 行滤掉，退化成内连接。",
        difficulty: "medium",
        tags: ["LEFT JOIN", "过滤位置"],
        sourceKey: "postgresql",
      },
      {
        stem: "两个表只要存在多对多关系，连接后行数就可能远多于任一原表。",
        answer: true,
        explanation: "多对多匹配会为每一组匹配生成一行，因此必须先用唯一键确认粒度，否则统计结果会被放大。",
        difficulty: "easy",
        tags: ["连接", "行数膨胀"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-aggregate-window",
      "db-relational",
      {
        stem: "在保留明细行的同时计算每个分区的排名，应该使用什么？",
        options: ["GROUP BY 聚合", "窗口函数", "DISTINCT", "UNION"],
        answer: "B",
        explanation: "窗口函数在分区内计算但保留每一行明细，聚合会把明细折叠成每组一行。",
        difficulty: "easy",
        tags: ["窗口函数", "排名"],
        sourceKey: "cmu-bustub",
      },
      {
        stem: "过滤分组后的结果要用 HAVING，而不是 WHERE。",
        answer: true,
        explanation: "WHERE 在分组前过滤行，HAVING 在分组与聚合之后过滤结果组，两者作用对象不同。",
        difficulty: "easy",
        tags: ["HAVING", "GROUP BY"],
        sourceKey: "postgresql",
      }
    ),
    ...topicQuestionPair(
      "db-index-basics",
      "db-index",
      {
        stem: "复合索引 (a, b) 通常无法用于只按 b 过滤的查询，原因是什么？",
        options: ["索引太大", "必须命中左前缀才能定位", "b 的选择性一定低", "索引只支持等值查询"],
        answer: "B",
        explanation: "B-Tree 先按第一列排序，只按第二列过滤无法定位区间，因此复合索引的列顺序必须匹配查询模式。",
        difficulty: "medium",
        tags: ["复合索引", "最左前缀"],
        sourceKey: "cmu-bustub",
      },
      {
        stem: "索引越多，写入与更新的成本越高。",
        answer: true,
        explanation: "每条索引都要随写入同步维护，索引数量会直接放大写入放大效应和存储占用。",
        difficulty: "easy",
        tags: ["索引", "写入成本"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-explain",
      "db-index",
      {
        stem: "执行计划里估算行数与实际行数相差一个数量级，最可能的原因是什么？",
        options: ["磁盘满了", "统计信息过期或数据分布倾斜", "SQL 语法错误", "连接数不足"],
        answer: "B",
        explanation: "优化器靠统计信息估算代价；统计过期或严重倾斜时估算失真，进而选出不合适的连接算法。",
        difficulty: "medium",
        tags: ["执行计划", "统计信息"],
        sourceKey: "postgresql",
      },
      {
        stem: "只要出现全表扫描，就一定说明查询需要优化。",
        answer: false,
        explanation: "小表或需要读取大部分数据的查询，顺序扫描往往比走索引更快，判断要结合数据量与计划节点代价。",
        difficulty: "medium",
        tags: ["全表扫描", "优化判断"],
        sourceKey: "postgresql",
      }
    ),
    ...topicQuestionPair(
      "db-query-tuning",
      "db-index",
      {
        stem: "分页查询出现漏行与重复，最常见的原因是什么？",
        options: ["分页大小太小", "排序键不唯一且不稳定", "没有建索引", "数据库版本过低"],
        answer: "B",
        explanation: "排序键存在并列值时行序不确定，跨页查询就可能重复或跳过，必须追加唯一键保证稳定排序。",
        difficulty: "medium",
        tags: ["分页", "排序稳定性"],
        sourceKey: "postgresql",
      },
      {
        stem: "把大 OFFSET 分页改成基于游标的分页，可以显著减少要扫描的行数。",
        answer: true,
        explanation: "游标分页用上一页的最后一行作为起点，避免数据库先扫描并丢弃前面所有行。",
        difficulty: "medium",
        tags: ["深分页", "游标"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-acid",
      "db-transaction",
      {
        stem: "划定事务边界最可靠的做法是什么？",
        options: ["按接口数量划分", "围绕一个必须保持一致性的业务不变量划分", "尽可能把所有操作放进一个事务", "按代码行数划分"],
        answer: "B",
        explanation: "以业务不变量为单位，既能保证正确性又能控制持锁范围；事务过大或过小都会带来问题。",
        difficulty: "medium",
        tags: ["事务边界", "一致性"],
        sourceKey: "cmu-bustub",
      },
      {
        stem: "在事务中调用第三方支付接口等待响应，会加剧锁竞争。",
        answer: true,
        explanation: "外部调用不可控且耗时，会让事务长时间持锁，应把外部交互移到事务之外或改为异步补偿。",
        difficulty: "medium",
        tags: ["长事务", "锁"],
        sourceKey: "postgresql",
      }
    ),
    ...topicQuestionPair(
      "db-isolation",
      "db-transaction",
      {
        stem: "选择隔离级别时，最合理的出发点是哪一项？",
        options: ["统一用最高级别", "先列出业务无法容忍的异常再匹配级别", "沿用上一次项目的配置", "只看性能测试结果"],
        answer: "B",
        explanation: "隔离级别是并发度与一致性的权衡，必须从业务不能接受的异常出发，再决定是否需要降级或补应用层处理。",
        difficulty: "medium",
        tags: ["隔离级别", "异常"],
        sourceKey: "postgresql",
      },
      {
        stem: "在可重复读下，快照读不会阻塞其他事务的写入。",
        answer: true,
        explanation: "快照读读取事务开始时的可见版本，不需要加锁；但当前读仍会与写入产生冲突。",
        difficulty: "hard",
        tags: ["快照读", "MVCC"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-lock-deadlock",
      "db-transaction",
      {
        stem: "被数据库判定为死锁牺牲品的事务，应用层应该怎么做？",
        options: ["直接返回失败给用户", "带退避地重试整个事务", "忽略错误继续执行", "关闭数据库连接"],
        answer: "B",
        explanation: "数据库已回滚该事务，重试是预期恢复路径；但必须加上退避与次数上限，避免重试风暴。",
        difficulty: "medium",
        tags: ["死锁", "重试"],
        sourceKey: "postgresql",
      },
      {
        stem: "让不同事务按同一顺序访问同一批资源，可以显著降低死锁概率。",
        answer: true,
        explanation: "死锁多来自循环等待，统一加锁顺序能打破循环，是最简单有效的预防手段。",
        difficulty: "easy",
        tags: ["加锁顺序", "死锁预防"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-normalization",
      "db-modeling-ops",
      {
        stem: "决定一个冗余统计字段是否可接受，最关键的前提是什么？",
        options: ["字段类型简单", "明确它的更新来源与一致性校验方式", "字段名短", "把它建成索引"],
        answer: "B",
        explanation: "冗余本身不是问题，没有维护方才是问题；必须写清由谁在什么时机更新、如何校验是否漂移。",
        difficulty: "medium",
        tags: ["反范式", "冗余"],
        sourceKey: "cmu-bustub",
      },
      {
        stem: "范式化的主要收益是减少更新异常和数据重复。",
        answer: true,
        explanation: "把事实只存一处可以避免同一信息多处修改不一致，代价是查询可能需要更多连接。",
        difficulty: "easy",
        tags: ["范式", "建模"],
        sourceKey: "postgresql",
      }
    ),
    ...topicQuestionPair(
      "db-migration-safe",
      "db-modeling-ops",
      {
        stem: "已经应用过的迁移文件是否需要回填修改以保持一致？",
        options: ["需要，随时保持最新", "不需要，只追加新迁移文件", "仅在测试环境修改", "视数据库版本决定"],
        answer: "B",
        explanation: "已应用的迁移在别的环境已经执行过，改它会造成环境间结构不一致，只能用新的迁移文件追加修正。",
        difficulty: "medium",
        tags: ["迁移", "只追加"],
        sourceKey: "postgresql",
      },
      {
        stem: "大表加非空字段时，先加可空字段、回填数据、再加约束，是更安全的顺序。",
        answer: true,
        explanation: "分步执行让每一步都能独立验证与重跑，避免一次性长事务锁表和一次性回填失败无法继续。",
        difficulty: "medium",
        tags: ["在线变更", "回填"],
        sourceKey: "cmu-bustub",
      }
    ),
    ...topicQuestionPair(
      "db-backup-recovery",
      "db-modeling-ops",
      {
        stem: "判断备份是否真的可用，唯一可靠的方式是什么？",
        options: ["查看备份文件大小", "实际执行一次恢复到演练环境", "确认定时任务在运行", "检查磁盘剩余空间"],
        answer: "B",
        explanation: "只有真正恢复出来并验证数据可用，才能证明备份链路完整；文件存在不代表可恢复。",
        difficulty: "easy",
        tags: ["恢复演练", "备份"],
        sourceKey: "postgresql",
      },
      {
        stem: "容量规划只需要关注数据文件是否增长。",
        answer: false,
        explanation: "还要关注连接数、慢查询、临时文件与索引膨胀，容量瓶颈常常来自查询放大而非数据增长。",
        difficulty: "medium",
        tags: ["容量", "监控"],
        sourceKey: "cmu-bustub",
      }
    ),
  ],
};
