import type { LearningTrack } from "./types";

export const dataAnalysisTrack: LearningTrack = {
  slug: "data-analysis",
  title: "SQL 与数据分析",
  category: "数据分析",
  level: "进阶",
  accent: "#2FB3A6",
  softAccent: "#E4F7F5",
  icon: "analytics-outline",
  summary: "从关系模型和 SQL 到清洗、统计、可视化与业务结论，形成完整分析闭环。",
  whyLearn: "数据分析的核心不是会画图，而是把业务问题转成可验证的数据问题，并给出可靠结论。",
  prerequisites: ["理解表格和基本统计量", "能使用 Excel 或任意编程语言处理数据"],
  studyMethod: ["每个问题先写指标定义", "SQL 查询按步骤验证行数和粒度", "图表必须回答明确业务问题"],
  estimatedHours: 100,
  featured: true,
  sources: [
    {
      key: "ms-data-science",
      name: "Microsoft Data Science for Beginners",
      url: "https://github.com/microsoft/Data-Science-For-Beginners",
      license: "MIT",
      usage: "import",
      note: "数据生命周期、清洗、统计和可视化课程",
    },
    {
      key: "data-engineering-reference",
      name: "Data Engineering Zoomcamp",
      url: "https://github.com/DataTalksClub/data-engineering-zoomcamp",
      license: "未识别",
      usage: "reference",
      note: "数据工程学习路径参考，首版不直接复制",
    },
    {
      key: "system-design-primer",
      name: "System Design Primer",
      url: "https://github.com/donnemartin/system-design-primer",
      license: "CC BY 4.0",
      usage: "reference",
      note: "数据流和系统边界的设计方法",
    },
  ],
  stages: [
    {
      key: "data-relational",
      title: "关系模型与 SQL 查询",
      weeks: "第 1-3 周",
      goal: "理解表、键、关系以及 SELECT、WHERE、JOIN 的查询逻辑。",
      outcome: "能独立完成多表查询并解释每一行结果的来源。",
      topics: [
        {
          key: "data-relational-model",
          title: "关系模型与数据粒度",
          summary: "主键、外键、一对多、多对多和事实粒度。",
          concepts: ["主键与外键", "实体与关系", "数据粒度", "规范化基础"],
          principles: ["一行代表一个明确业务对象或事件", "连接前先确认两端键的唯一性"],
          applications: ["订单与商品", "用户与行为", "课程与报名"],
          pitfalls: ["把展示表格当作数据表设计", "忽略同一行代表什么"],
          method: "先写出每张表的一行含义，再定义键和关系。",
          exercise: "为课程报名场景设计用户、课程、报名三张表和字段。",
          checkpoint: "能说明每条数据的主键和与其他表的对应关系。",
        },
        {
          key: "data-select-filter",
          title: "查询、过滤与排序",
          summary: "SELECT、WHERE、NULL、排序、去重和条件表达式。",
          concepts: ["过滤顺序", "NULL 三值逻辑", "CASE WHEN", "LIMIT"],
          principles: ["SQL 先确定数据集合，再计算字段和排序", "NULL 不参与普通等值判断"],
          applications: ["筛选活跃用户", "计算状态标签", "分页查询"],
          pitfalls: ["用 = NULL 判断空值", "在 WHERE 中重复使用复杂表达式导致难维护"],
          method: "从最小查询开始，每加一个条件就检查行数和样例。",
          exercise: "查询近 30 天高价值订单并按地区排序。",
          checkpoint: "能预测过滤条件变化对结果行数的影响。",
        },
        {
          key: "data-joins",
          title: "多表连接与聚合",
          summary: "INNER/LEFT JOIN、GROUP BY、HAVING 和连接膨胀。",
          concepts: ["连接键", "左右连接", "分组粒度", "HAVING"],
          principles: ["JOIN 改变结果粒度，聚合把多行压缩为一个分组", "先 WHOLE 行数检查，再看字段"],
          applications: ["订单明细汇总", "用户行为分析", "漏斗计算"],
          pitfalls: ["未去重导致指标翻倍", "把 WHERE 过滤条件放错到 JOIN"],
          method: "连接前后对比行数、键唯一性和空值比例。",
          exercise: "用订单和退款表计算净收入与退款率。",
          checkpoint: "能证明当前查询不会因为连接键重复而抬高指标。",
        },
      ],
      questionKeys: ["data-q1", "data-q2", "data-q3"],
    },
    {
      key: "data-analysis-sql",
      title: "SQL 分析与窗口函数",
      weeks: "第 4-6 周",
      goal: "掌握分组、窗口、CTE、排名、累计和漏斗分析。",
      outcome: "能用一条结构化查询回答一组完整业务指标。",
      topics: [
        {
          key: "data-window",
          title: "窗口函数",
          summary: "ROW_NUMBER、RANK、LAG/LEAD、累计求和与分区。",
          concepts: ["PARTITION BY", "ORDER BY", "窗口帧", "排名与偏移"],
          principles: ["窗口函数在不压缩行的前提下增加分析列", "分区决定每行参与计算的范围"],
          applications: ["连续活跃", "同比环比", "用户路径"],
          pitfalls: ["把 PARTITION BY 当成 GROUP BY", "忽略并列排名规则"],
          method: "先确定结果行粒度，再选择窗口分区与排序。",
          exercise: "计算每个用户每月消费排名和相邻月份变化。",
          checkpoint: "能逐行说明窗口函数每一行使用了哪些输入。",
        },
        {
          key: "data-cte",
          title: "CTE 与查询拆解",
          summary: "WITH、子查询、可读性和逐步验证。",
          concepts: ["CTE 链式步骤", "中间指标", "子查询作用域"],
          principles: ["复杂分析应拆成可命名、可验证的阶段", "中间结果可以独立检查"],
          applications: ["漏斗", "留存", "指标分层"],
          pitfalls: ["把所有逻辑塞进一条不可读的嵌套查询", "CTE 命名含糊"],
          method: "每个 CTE 只完成一件事，并保持输入输出粒度稳定。",
          exercise: "用四步 CTE 完成注册到首单的漏斗。",
          checkpoint: "每一步都能单独运行并解释行数变化。",
        },
        {
          key: "data-funnel-retention",
          title: "漏斗、留存与同期群",
          summary: "事件顺序、时间窗口、留存定义和活跃口径。",
          concepts: ["转化漏斗", "次日/7 日留存", "同期群", "活跃定义"],
          principles: ["留存指标必须先固定用户和日期口径", "事件顺序决定漏斗是否有效"],
          applications: ["拉新分析", "产品激活", "课程完成率"],
          pitfalls: ["不同页面使用不同活跃口径", "只统计发生事件的人而忽略分母"],
          method: "先定义用户、时间、事件三要素，再计算分子分母。",
          exercise: "计算新用户次日留存和 7 日留存。",
          checkpoint: "能解释每个留存率为什么选择这条分母。",
        },
      ],
      questionKeys: ["data-q4", "data-q5", "data-q6"],
    },
    {
      key: "data-cleaning",
      title: "数据清洗与探索",
      weeks: "第 7-9 周",
      goal: "识别缺失、异常、重复和口径不一致，并建立可靠的探索流程。",
      outcome: "能交付一份可追溯的数据质量报告和清洗后的分析数据集。",
      topics: [
        {
          key: "data-quality",
          title: "数据质量与缺失值",
          summary: "完整性、准确性、一致性、时效性和缺失处理。",
          concepts: ["缺失机制", "重复键", "异常值", "清洗日志"],
          principles: ["清洗规则应服务于分析问题，而不是默认删除或填充", "清洗必须可追溯"],
          applications: ["客户资料", "订单状态", "设备日志"],
          pitfalls: ["无差别填充均值", "删除缺失后不比较样本变化"],
          method: "先量化质量问题，再决定修复、标记或排除。",
          exercise: "审核一份设备日志并输出质量问题与处理选择。",
          checkpoint: "每一条清洗规则都有影响范围和处理理由。",
        },
        {
          key: "data-exploration",
          title: "描述统计与异常发现",
          summary: "分布、集中趋势、离散程度和相关关系。",
          concepts: ["均值与中位数", "标准差与分位数", "箱线图", "相关性不等于因果"],
          principles: ["先看分布再看均值", "异常值可能是错误，也可能是最有价值的信息"],
          applications: ["销售波动", "性能监控", "风险识别"],
          pitfalls: ["只看总体平均忽略分层", "把相关关系直接解释为因果"],
          method: "按总体、分组和时间三种视角逐步探索。",
          exercise: "找出销售数据中的异常日期并给出两种解释。",
          checkpoint: "能区分数据错误、真实异常和业务事件。",
        },
        {
          key: "data-experiment",
          title: "指标、实验与因果基础",
          summary: "指标定义、对照组、A/B 测试与常见偏差。",
          concepts: ["北极星指标", "对照组", "样本量", "选择偏差"],
          principles: ["实验设计决定能否比较因果", "指标变化必须与业务动作建立可验证联系"],
          applications: ["功能上线", "推荐策略", "课程优化"],
          pitfalls: ["实验中途只挑显著结果", "忽略季节和渠道差异"],
          method: "先定义假设和成功指标，再决定样本与观察周期。",
          exercise: "设计一个课程练习功能 A/B 实验方案。",
          checkpoint: "实验能回答因果问题，并明确不能回答的范围。",
        },
      ],
      questionKeys: ["data-q7", "data-q8", "data-q9"],
    },
    {
      key: "data-visual-delivery",
      title: "可视化与业务交付",
      weeks: "第 10-12 周",
      goal: "把分析结果组织成可读、可行动、可复现的报告和仪表板。",
      outcome: "完成一份从问题、数据、分析到建议的完整业务报告。",
      topics: [
        {
          key: "data-chart-choice",
          title: "图表选择与表达",
          summary: "比较、趋势、构成、分布和关系五类图形。",
          concepts: ["图形语法", "视觉编码", "颜色与标注", "图表层次"],
          principles: ["图表编码应与问题结构匹配", "减少装饰，突出可比较信息"],
          applications: ["周报", "运营看板", "管理层汇报"],
          pitfalls: ["用饼图表达过多分类", "用颜色替代标签导致阅读负担"],
          method: "先说一句结论，再选择最能支撑它的图形。",
          exercise: "为四个业务问题分别选择图表并写标题结论。",
          checkpoint: "不使用解释也能从图上看出主要趋势和异常。",
        },
        {
          key: "data-dashboard",
          title: "仪表板与信息架构",
          summary: "指标层级、筛选、布局、刷新和口径说明。",
          concepts: ["信息层级", "全局与局部筛选", "图表交互", "数据新鲜度"],
          principles: ["仪表板服务于决策路径，而不是堆积所有指标", "同一指标只能有一个可信口径"],
          applications: ["经营看板", "产品监控", "项目周报"],
          pitfalls: ["指标过多导致无重点", "筛选器互相冲突"],
          method: "先定义页面要回答的三个问题，再安排指标和布局。",
          exercise: "设计一页课程运营仪表板并写指标口径。",
          checkpoint: "用户能在一分钟内找到异常、原因和高优先级行动。",
        },
        {
          key: "data-story",
          title: "分析叙事与交付",
          summary: "结论、证据、限制、建议和复现说明。",
          concepts: ["问题-证据-结论", "限制条件", "行动建议", "复现记录"],
          principles: ["结论强度不能超过数据支持范围", "建议必须指向具体动作和负责人"],
          applications: ["评审汇报", "专题分析", "数据复盘"],
          pitfalls: ["只展示过程不讲结论", "把不确定性省略成确定判断"],
          method: "先写一句话摘要，再逐层补充证据和限制。",
          exercise: "把一次数据分析整理成 5 页汇报。",
          checkpoint: "业务方能在 3 分钟内理解结论、依据和下一步。",
        },
      ],
      questionKeys: ["data-q10", "data-q11", "data-q12"],
    },
  ],
  questions: [
    {
      key: "data-q1",
      stageKey: "data-relational",
      type: "judge",
      stem: "在关系模型中，一张表的一行应代表明确且一致的数据粒度。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "明确每行代表一个用户、订单或事件，是正确连接和聚合指标的前提。",
      difficulty: "easy",
      tags: ["关系模型", "粒度"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q2",
      stageKey: "data-relational",
      type: "single",
      stem: "判断某列是否为空，正确写法是什么？",
      options: [
        { key: "A", text: "column = NULL" },
        { key: "B", text: "column IS NULL" },
        { key: "C", text: "column == NULL" },
        { key: "D", text: "column EMPTY NULL" },
      ],
      answer: ["B"],
      explanation: "NULL 表示未知，不能使用普通等值比较判断，应使用 IS NULL / IS NOT NULL。",
      difficulty: "easy",
      tags: ["SQL", "NULL"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q3",
      stageKey: "data-relational",
      type: "single",
      stem: "连接后指标翻倍，首先应该检查什么？",
      options: [
        { key: "A", text: "连接键是否唯一" },
        { key: "B", text: "列名是否英文" },
        { key: "C", text: "数据库版本" },
        { key: "D", text: "排序方式" },
      ],
      answer: ["A"],
      explanation: "连接键重复会产生多对多匹配并使行数膨胀，进而抬高求和指标。",
      difficulty: "medium",
      tags: ["JOIN", "指标"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q4",
      stageKey: "data-analysis-sql",
      type: "single",
      stem: "窗口函数与 GROUP BY 的核心区别是什么？",
      options: [
        { key: "A", text: "窗口函数不保留原始行" },
        { key: "B", text: "窗口函数在保留行的同时增加分析列" },
        { key: "C", text: "GROUP BY 只能用于日期" },
        { key: "D", text: "窗口函数不能排序" },
      ],
      answer: ["B"],
      explanation: "窗口函数按分区计算，但不会像 GROUP BY 那样把原始行压缩成分组行。",
      difficulty: "medium",
      tags: ["窗口函数", "SQL"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q5",
      stageKey: "data-analysis-sql",
      type: "judge",
      stem: "CTE 的主要价值之一是把复杂查询拆成可命名、可逐段验证的步骤。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "命名中间结果有助于理解粒度、验证行数，并降低嵌套查询的维护成本。",
      difficulty: "easy",
      tags: ["CTE", "可读性"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q6",
      stageKey: "data-analysis-sql",
      type: "single",
      stem: "计算 7 日留存时，最关键的定义不包括下列哪一项？",
      options: [
        { key: "A", text: "新用户口径" },
        { key: "B", text: "活跃事件口径" },
        { key: "C", text: "观察时间窗口" },
        { key: "D", text: "图表颜色" },
      ],
      answer: ["D"],
      explanation: "留存指标必须先固定用户、事件和时间口径；图表颜色不应影响指标定义。",
      difficulty: "medium",
      tags: ["留存", "同期群"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q7",
      stageKey: "data-cleaning",
      type: "single",
      stem: "发现缺失值时，最先应该做什么？",
      options: [
        { key: "A", text: "全部填充为 0" },
        { key: "B", text: "量化缺失比例并分析缺失模式" },
        { key: "C", text: "直接删除所有行" },
        { key: "D", text: "忽略缺失" },
      ],
      answer: ["B"],
      explanation: "先判断缺失是否随机、集中在哪些分组以及影响哪些指标，才能决定处理方式。",
      difficulty: "easy",
      tags: ["缺失值", "数据质量"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q8",
      stageKey: "data-cleaning",
      type: "judge",
      stem: "发现相关关系后可以直接断定一个变量导致另一个变量变化。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "相关不等于因果，还可能存在共同原因、选择偏差或反向因果。",
      difficulty: "easy",
      tags: ["统计", "因果"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q9",
      stageKey: "data-cleaning",
      type: "single",
      stem: "A/B 实验能够支持因果判断的关键条件是什么？",
      options: [
        { key: "A", text: "所有用户都参与" },
        { key: "B", text: "随机分配对照组和实验组" },
        { key: "C", text: "图表使用同一种颜色" },
        { key: "D", text: "只观察一天" },
      ],
      answer: ["B"],
      explanation: "随机分配可以降低组间系统性差异，使结果更有条件支持因果解释。",
      difficulty: "medium",
      tags: ["实验", "A/B"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q10",
      stageKey: "data-visual-delivery",
      type: "single",
      stem: "展示 12 个分类的构成时，通常优先选择什么图？",
      options: [
        { key: "A", text: "12 个扇区的饼图" },
        { key: "B", text: "排序后的条形图" },
        { key: "C", text: "3D 饼图" },
        { key: "D", text: "散点图" },
      ],
      answer: ["B"],
      explanation: "分类较多时，排序条形图比饼图更容易比较大小和读取标签。",
      difficulty: "easy",
      tags: ["可视化", "图表"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q11",
      stageKey: "data-visual-delivery",
      type: "judge",
      stem: "仪表板设计应优先围绕决策问题组织指标，而不是尽可能放更多图表。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "过多指标会稀释重点，好的仪表板应帮助用户快速发现异常并决定下一步行动。",
      difficulty: "easy",
      tags: ["仪表板", "信息架构"],
      sourceKey: "ms-data-science",
    },
    {
      key: "data-q12",
      stageKey: "data-visual-delivery",
      type: "single",
      stem: "数据结论的强度应该满足什么要求？",
      options: [
        { key: "A", text: "永远给出确定因果" },
        { key: "B", text: "不超过数据能够支持的范围" },
        { key: "C", text: "只写正面结果" },
        { key: "D", text: "忽略样本限制" },
      ],
      answer: ["B"],
      explanation: "结论和假设必须与样本、口径和实验设计匹配，并明确限制和不确定性。",
      difficulty: "medium",
      tags: ["结论", "分析叙事"],
      sourceKey: "ms-data-science",
    },
  ],
};

