import { judgeQuestion, singleQuestion } from "./question-builders";
import type { LearningTrack } from "./types";

export const javascriptTrack: LearningTrack = {
  slug: "javascript",
  title: "JavaScript",
  category: "前端开发",
  level: "入门",
  accent: "#B77900",
  softAccent: "#FFF4D6",
  icon: "logo-javascript",
  summary: "从语言核心、异步与浏览器到工程化和现代前端，建立可交付的 JavaScript 能力。",
  whyLearn: "JavaScript 同时连接浏览器、服务端和跨端应用，是现代 Web 产品最通用的交互语言。",
  prerequisites: ["了解变量、函数和条件语句", "能使用浏览器开发者工具查看控制台"],
  studyMethod: ["每个语法都写最小可运行示例", "先理解运行时行为，再记 API", "用测试固定异步和数据转换的边界"],
  estimatedHours: 96,
  featured: true,
  sources: [
    {
      key: "freecodecamp-js",
      name: "freeCodeCamp",
      url: "https://github.com/freeCodeCamp/freeCodeCamp",
      license: "BSD-3-Clause",
      usage: "import",
      note: "JavaScript 基础练习组织、测试驱动学习和项目思路",
    },
    {
      key: "algorithms-javascript",
      name: "TheAlgorithms/JavaScript",
      url: "https://github.com/TheAlgorithms/JavaScript",
      license: "MIT",
      usage: "import",
      note: "数组、对象、算法与数据结构练习",
    },
    {
      key: "mdn-reference",
      name: "MDN Web Docs",
      url: "https://github.com/mdn/content",
      license: "CC BY-SA 2.5",
      usage: "reference",
      note: "浏览器 API、JavaScript 语义与 Web 平台参考，仅保留外链",
    },
  ],
  stages: [
    {
      key: "js-language",
      title: "语言核心与数据建模",
      weeks: "第 1-3 周",
      goal: "掌握值、作用域、函数、数组和对象，并能解释常见运行时行为。",
      outcome: "完成一组无框架的数据转换、统计和小型状态管理工具。",
      topics: [
        {
          key: "js-values-scope",
          title: "值、类型与作用域",
          summary: "原始值、对象引用、类型转换、let/const 与作用域链。",
          concepts: ["原始值与引用值", "严格相等", "词法作用域", "暂时性死区"],
          principles: ["原始值按值比较，对象按引用身份比较", "作用域在代码书写位置决定，而不是运行时调用位置"],
          applications: ["配置合并", "参数校验", "状态隔离"],
          pitfalls: ["混用 == 导致隐式转换", "在声明前访问 let/const 变量"],
          method: "遇到类型问题时先打印值和类型，再追踪引用是否共享。",
          exercise: "实现一个安全的配置合并函数并覆盖嵌套对象和数组。",
          checkpoint: "能预测一段代码的比较结果和变量可见范围。",
        },
        {
          key: "js-functions-closures",
          title: "函数、闭包与 this",
          summary: "函数表达式、箭头函数、闭包、调用方式和 this 绑定。",
          concepts: ["一等函数", "闭包", "调用栈", "this 绑定"],
          principles: ["闭包保留创建时所在词法环境中的变量", "this 由调用方式或箭头函数外层决定"],
          applications: ["事件处理", "防抖节流", "私有状态"],
          pitfalls: ["把回调中的 this 误认为定义对象", "在循环中错误共享闭包变量"],
          method: "先画出函数创建位置和调用位置，再判断捕获变量与 this。",
          exercise: "实现 once、debounce 和带独立计数的任务工厂。",
          checkpoint: "能解释闭包为什么保留变量，以及何时可能造成内存滞留。",
        },
        {
          key: "js-collections",
          title: "数组、对象与现代集合",
          summary: "遍历、变换、Map/Set、浅拷贝和不可变更新。",
          concepts: ["map/filter/reduce", "Map 与 Set", "结构化克隆边界", "浅拷贝"],
          principles: ["转换函数应保持输入不变并返回明确结果", "Map/Set 在键类型和唯一性语义上优于普通对象"],
          applications: ["列表渲染", "去重统计", "索引与缓存"],
          pitfalls: ["误以为展开运算符会深拷贝", "在遍历中修改原数组"],
          method: "先把数据处理写成输入、转换、输出三步，再选择集合 API。",
          exercise: "用 Map 和 reduce 完成订单分组、总额和 Top 3 用户。",
          checkpoint: "能说明每一步是否改变原数据以及复杂度量级。",
        },
      ],
      questionKeys: ["js-q1", "js-q2", "js-q3", "js-q4"],
    },
    {
      key: "js-async-browser",
      title: "异步、浏览器与网络",
      weeks: "第 4-6 周",
      goal: "理解事件循环、Promise、async/await、DOM 事件和网络请求。",
      outcome: "完成一个具有加载、失败、取消和重试状态的浏览器应用。",
      topics: [
        {
          key: "js-event-loop",
          title: "事件循环与任务队列",
          summary: "调用栈、宏任务、微任务、渲染时机和阻塞风险。",
          concepts: ["调用栈", "宏任务", "微任务", "事件循环"],
          principles: ["同步代码先执行，当前任务结束后清空微任务队列", "长时间同步计算会阻塞交互和渲染"],
          applications: ["加载顺序", "状态更新", "性能排查"],
          pitfalls: ["把定时器当成精确时钟", "用忙等待处理异步结果"],
          method: "按调用栈、微任务、宏任务三个队列逐步推演输出顺序。",
          exercise: "预测并运行一段 Promise、setTimeout 和同步代码混合的输出。",
          checkpoint: "能解释为什么某些回调必须等待当前同步任务结束。",
        },
        {
          key: "js-promises",
          title: "Promise 与 async/await",
          summary: "链式调用、错误传播、并发组合、取消和超时。",
          concepts: ["Promise 状态", "then/catch/finally", "all/allSettled", "AbortController"],
          principles: ["Promise 表示未来结果，错误会沿链传播直到被处理", "async 函数始终返回 Promise"],
          applications: ["接口聚合", "并发请求", "失败重试"],
          pitfalls: ["忘记 await 导致拿到 Promise 而非结果", "捕获错误后不保留上下文"],
          method: "先写成功路径，再分别补失败、取消和并发限流。",
          exercise: "实现带超时、取消和部分失败汇总的请求组合器。",
          checkpoint: "能从代码看出错误在哪里被捕获、重试或继续抛出。",
        },
        {
          key: "js-dom-network",
          title: "DOM、事件与网络",
          summary: "查询元素、事件委托、表单、fetch 和响应状态处理。",
          concepts: ["DOM 树", "事件冒泡", "事件委托", "HTTP 状态码"],
          principles: ["事件委托利用冒泡减少监听器数量", "fetch 仅在网络层失败时 reject，HTTP 错误仍需检查状态码"],
          applications: ["交互列表", "表单校验", "分页加载"],
          pitfalls: ["直接拼接不可信 HTML", "忽略非 2xx 响应"],
          method: "先定义事件来源和状态变化，再更新最小 DOM 范围。",
          exercise: "实现可筛选、分页和错误重试的列表页面。",
          checkpoint: "页面有加载、空、失败和成功四种完整状态。",
        },
      ],
      questionKeys: ["js-q5", "js-q6", "js-q7", "js-q8"],
    },
    {
      key: "js-engineering",
      title: "模块、测试与工程化",
      weeks: "第 7-9 周",
      goal: "掌握 ES Modules、包管理、测试、构建和浏览器存储。",
      outcome: "交付一个可构建、可测试、依赖边界清晰的前端项目。",
      topics: [
        {
          key: "js-modules",
          title: "模块与依赖边界",
          summary: "ESM、导入导出、循环依赖和包管理基础。",
          concepts: ["默认导出与命名导出", "模块作用域", "依赖图", "语义化版本"],
          principles: ["模块应围绕稳定职责暴露最小接口", "依赖方向应指向核心业务而不是具体页面"],
          applications: ["工具模块", "API 客户端", "领域模型"],
          pitfalls: ["用桶文件制造隐藏依赖", "让工具模块反向依赖页面状态"],
          method: "先画依赖图，再决定模块边界和公共接口。",
          exercise: "把单文件应用拆成 API、状态、视图和工具四个模块。",
          checkpoint: "任一模块可独立测试，且没有双向依赖。",
        },
        {
          key: "js-testing",
          title: "测试与调试",
          summary: "单元测试、DOM 测试、边界条件、调试器和覆盖率。",
          concepts: ["断言", "测试替身", "回归测试", "覆盖率"],
          principles: ["测试验证行为契约而不是内部实现", "每个失败测试都应能定位一个具体原因"],
          applications: ["数据转换", "组件交互", "网络失败"],
          pitfalls: ["只追求覆盖率不看断言质量", "测试依赖执行顺序"],
          method: "先列正常、边界和失败路径，再按风险从高到低补测试。",
          exercise: "为请求组合器补齐成功、超时、取消和部分失败测试。",
          checkpoint: "重构内部实现后，行为测试仍然通过。",
        },
        {
          key: "js-browser-data",
          title: "存储、性能与可访问性",
          summary: "Cookie、localStorage、缓存、性能指标和键盘操作。",
          concepts: ["同源策略", "持久化存储", "缓存策略", "可访问名称"],
          principles: ["不同存储介质在容量、安全性和生命周期上取舍不同", "性能优化必须先测量真实瓶颈"],
          applications: ["主题偏好", "离线草稿", "列表性能"],
          pitfalls: ["把敏感令牌放入 localStorage", "只依赖鼠标和颜色传递信息"],
          method: "先写数据敏感级别和访问方式，再选择存储与性能策略。",
          exercise: "实现主题持久化、离线草稿和完整键盘导航。",
          checkpoint: "核心流程可键盘完成，刷新后状态能按预期恢复。",
        },
      ],
      questionKeys: ["js-q9", "js-q10", "js-q11", "js-q12"],
    },
    {
      key: "js-modern-frontend",
      title: "现代前端与综合项目",
      weeks: "第 10-12 周",
      goal: "用组件、状态和渲染模型完成可维护的前端应用，并建立性能意识。",
      outcome: "交付一个包含路由、数据流、表单、错误恢复和可访问性的完整前端项目。",
      topics: [
        {
          key: "js-components",
          title: "组件与组合",
          summary: "组件边界、props、插槽式组合和受控表单。",
          concepts: ["纯组件", "props 与 state", "组合", "受控输入"],
          principles: ["组件应围绕单一职责组织，并通过明确接口组合", "状态应放在需要它的最小公共祖先"],
          applications: ["表单", "列表卡片", "布局容器"],
          pitfalls: ["把所有状态提升到全局", "组件同时处理请求、业务和展示"],
          method: "先画组件树和数据流向，再决定状态归属。",
          exercise: "实现一个带筛选、详情和编辑表单的组件化页面。",
          checkpoint: "每个组件有清晰输入和输出，重复状态来源唯一。",
        },
        {
          key: "js-state-render",
          title: "状态、渲染与副作用",
          summary: "单向数据流、不可变更新、派生状态和副作用清理。",
          concepts: ["单向数据流", "不可变更新", "派生值", "副作用清理"],
          principles: ["可推导的数据不重复存储", "副作用必须建立和清理成对出现"],
          applications: ["搜索筛选", "订阅", "定时刷新"],
          pitfalls: ["在渲染期间修改状态", "忘记取消订阅或请求"],
          method: "把状态分成输入、派生和临时交互三类，再写更新路径。",
          exercise: "实现带搜索、分页和自动刷新且不会重复订阅的列表。",
          checkpoint: "状态改变后的渲染结果可预测，且卸载后没有残留任务。",
        },
        {
          key: "js-performance",
          title: "性能与交付质量",
          summary: "渲染成本、懒加载、包体积、错误边界和发布检查。",
          concepts: ["首屏指标", "代码分割", "布局抖动", "错误边界"],
          principles: ["先测量再优化，优化必须给出前后对比", "错误处理目标是限制影响范围并提供恢复路径"],
          applications: ["大列表", "图表页面", "按需加载模块"],
          pitfalls: ["无依据地全面 memo", "只处理日志不处理用户恢复"],
          method: "建立性能与错误基线，每次只改一个变量并复测。",
          exercise: "对一个慢页面完成性能分析、代码分割和错误恢复。",
          checkpoint: "有可复现的性能数据，失败时用户能重试或返回安全状态。",
        },
      ],
      questionKeys: ["js-q13", "js-q14", "js-q15", "js-q16"],
    },
  ],
  questions: [
    singleQuestion({
      key: "js-q1",
      stageKey: "js-language",
      stem: "比较两个值且不希望发生隐式类型转换时，优先使用什么？",
      options: ["==", "===", "！=", "typeof"],
      answer: "B",
      explanation: "严格相等 === 先比较类型，再比较值，能避免多数隐式转换带来的意外结果。",
      difficulty: "easy",
      tags: ["严格相等", "类型"],
      sourceKey: "freecodecamp-js",
    }),
    judgeQuestion({
      key: "js-q2",
      stageKey: "js-language",
      stem: "两个内容完全相同的对象字面量使用 === 比较时一定为 true。",
      answer: false,
      explanation: "对象按引用身份比较，内容相同并不代表它们指向同一个对象。",
      difficulty: "easy",
      tags: ["对象", "引用"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q3",
      stageKey: "js-language",
      stem: "闭包能够访问什么变量？",
      options: ["只能访问全局变量", "创建函数时所在词法环境中的变量", "只能访问参数", "只能访问 this"],
      answer: "B",
      explanation: "闭包保留函数创建时的词法环境，因此可以继续访问外层作用域变量。",
      difficulty: "medium",
      tags: ["闭包", "作用域"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q4",
      stageKey: "js-language",
      stem: "要把数组中的每个元素转换为新值并得到同长度数组，通常使用什么？",
      options: ["filter", "map", "reduce", "sort"],
      answer: "B",
      explanation: "map 对每个元素执行转换并返回新的同长度数组，适合纯数据映射。",
      difficulty: "easy",
      tags: ["数组", "map"],
      sourceKey: "algorithms-javascript",
    }),
    singleQuestion({
      key: "js-q5",
      stageKey: "js-async-browser",
      stem: "当前同步任务结束后，Promise 回调通常进入哪个队列优先执行？",
      options: ["微任务队列", "宏任务队列", "渲染队列", "系统队列"],
      answer: "A",
      explanation: "当前调用栈清空后，运行时先清空微任务队列，再处理下一个宏任务。",
      difficulty: "medium",
      tags: ["事件循环", "微任务"],
      sourceKey: "mdn-reference",
    }),
    judgeQuestion({
      key: "js-q6",
      stageKey: "js-async-browser",
      stem: "async 函数无论内部是否显式返回 Promise，调用后都会得到 Promise。",
      answer: true,
      explanation: "async 函数会把返回值包装为 Promise，抛出错误则会得到 rejected Promise。",
      difficulty: "easy",
      tags: ["async", "Promise"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q7",
      stageKey: "js-async-browser",
      stem: "希望取消一个进行中的 fetch 请求，优先配合使用什么？",
      options: ["setInterval", "AbortController", "localStorage", "MutationObserver"],
      answer: "B",
      explanation: "AbortController 的 signal 可以传给 fetch，通过 abort 结束请求。",
      difficulty: "medium",
      tags: ["fetch", "取消"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q8",
      stageKey: "js-async-browser",
      stem: "长列表使用事件委托的主要优势是什么？",
      options: ["自动修改数据", "减少为每个子项绑定监听器", "保证网络更快", "替代状态管理"],
      answer: "B",
      explanation: "事件从子元素冒泡到共同父元素，父元素可统一识别触发来源，减少监听器数量。",
      difficulty: "easy",
      tags: ["DOM", "事件委托"],
      sourceKey: "freecodecamp-js",
    }),
    judgeQuestion({
      key: "js-q9",
      stageKey: "js-engineering",
      stem: "ES Modules 的静态导入关系有助于构建工具分析依赖图。",
      answer: true,
      explanation: "静态 import 在解析阶段就能确定依赖关系，便于打包、裁剪和循环依赖检查。",
      difficulty: "easy",
      tags: ["ESM", "依赖"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q10",
      stageKey: "js-engineering",
      stem: "高质量测试最应该优先保护什么？",
      options: ["内部变量名称", "可观察行为契约", "文件行数", "代码注释数量"],
      answer: "B",
      explanation: "行为契约在重构时保持稳定，能验证功能正确性而不锁死实现细节。",
      difficulty: "easy",
      tags: ["测试", "契约"],
      sourceKey: "freecodecamp-js",
    }),
    singleQuestion({
      key: "js-q11",
      stageKey: "js-engineering",
      stem: "以下哪类数据通常不应长期存放在 localStorage？",
      options: ["主题偏好", "公开缓存", "长期有效的敏感令牌", "离线草稿"],
      answer: "C",
      explanation: "localStorage 可被同源脚本读取，不适合长期保存高价值敏感凭据。",
      difficulty: "medium",
      tags: ["存储", "安全"],
      sourceKey: "mdn-reference",
    }),
    judgeQuestion({
      key: "js-q12",
      stageKey: "js-engineering",
      stem: "fetch 收到 404 响应时会自动 reject，因此不需要检查 response.ok。",
      answer: false,
      explanation: "fetch 通常只在网络层失败时 reject，404、500 等 HTTP 错误仍会 resolve，必须检查状态。",
      difficulty: "medium",
      tags: ["fetch", "HTTP"],
      sourceKey: "mdn-reference",
    }),
    singleQuestion({
      key: "js-q13",
      stageKey: "js-modern-frontend",
      stem: "多个组件需要读取同一份可变业务状态时，状态通常应放在哪里？",
      options: ["每个组件各存一份", "需要它的最小公共祖先", "随机全局变量", "CSS 文件"],
      answer: "B",
      explanation: "把状态提升到最小公共祖先可保持单一事实源，同时避免过度全局化。",
      difficulty: "medium",
      tags: ["组件", "状态"],
      sourceKey: "freecodecamp-js",
    }),
    singleQuestion({
      key: "js-q14",
      stageKey: "js-modern-frontend",
      stem: "渲染列表时，稳定 key 的主要作用是什么？",
      options: ["改变样式", "帮助运行时识别项目身份并复用节点", "压缩数据", "自动排序"],
      answer: "B",
      explanation: "稳定 key 让协调算法在插入、删除和排序时正确匹配项目，避免状态错位。",
      difficulty: "medium",
      tags: ["列表", "渲染"],
      sourceKey: "freecodecamp-js",
    }),
    judgeQuestion({
      key: "js-q15",
      stageKey: "js-modern-frontend",
      stem: "订阅、计时器和请求等副作用在组件卸载时通常需要清理。",
      answer: true,
      explanation: "清理可避免重复订阅、卸载后更新和资源泄漏，是副作用生命周期的一部分。",
      difficulty: "easy",
      tags: ["副作用", "生命周期"],
      sourceKey: "freecodecamp-js",
    }),
    singleQuestion({
      key: "js-q16",
      stageKey: "js-modern-frontend",
      stem: "性能优化最合理的第一步是什么？",
      options: ["全面增加缓存", "测量并定位真实瓶颈", "把组件都改成 memo", "删除测试"],
      answer: "B",
      explanation: "没有基线的优化可能增加复杂度却没有收益，应先测量并验证瓶颈位置。",
      difficulty: "easy",
      tags: ["性能", "测量"],
      sourceKey: "freecodecamp-js",
    }),
  ],
};
