import type { LearningTrack } from "./types";

export const javaTrack: LearningTrack = {
  slug: "java",
  title: "Java",
  category: "后端开发",
  level: "入门",
  accent: "#C74634",
  softAccent: "#FBE9E6",
  icon: "cafe-outline",
  summary: "从语法、集合、并发到设计模式，建立面向企业级后端开发的 Java 能力。",
  whyLearn: "Java 拥有稳定的类型系统、成熟的工程生态和大量企业级岗位，适合构建长期维护的后端服务。",
  prerequisites: ["了解变量、条件和循环", "能使用命令行或 IDE 运行程序"],
  studyMethod: ["先读懂类型和对象关系，再写可运行代码", "每章都做集合、异常和测试练习", "用一个小服务串联语言与工程知识"],
  estimatedHours: 120,
  featured: true,
  sources: [
    {
      key: "algorithms-java",
      name: "TheAlgorithms/Java",
      url: "https://github.com/TheAlgorithms/Java",
      license: "MIT",
      usage: "import",
      note: "算法、集合和数据结构练习",
    },
    {
      key: "java-patterns",
      name: "Java Design Patterns",
      url: "https://github.com/iluwatar/java-design-patterns",
      license: "MIT",
      usage: "import",
      note: "设计模式、重构与对象协作",
    },
    {
      key: "tech-interview-handbook",
      name: "Tech Interview Handbook",
      url: "https://github.com/yangshun/tech-interview-handbook",
      license: "MIT",
      usage: "import",
      note: "算法与工程面试问题组织方式",
    },
    {
      key: "advanced-java-reference",
      name: "advanced-java",
      url: "https://github.com/doocs/advanced-java",
      license: "CC BY-SA 4.0",
      usage: "reference",
      note: "后端进阶主题索引，首版仅作为延伸阅读",
    },
  ],
  stages: [
    {
      key: "java-foundation",
      title: "语言基础与面向对象",
      weeks: "第 1-3 周",
      goal: "理解类型、控制流、方法、类和接口，写出结构清晰的 Java 程序。",
      outcome: "完成一个包含多个类、接口和异常处理的命令行应用。",
      topics: [
        {
          key: "java-types-control",
          title: "类型与控制流",
          summary: "基本类型、引用类型、分支、循环、方法和重载。",
          concepts: ["基本类型与包装类型", "自动装箱", "方法签名与重载", "作用域"],
          principles: ["Java 是静态类型语言，编译期即检查类型兼容性", "方法重载由参数列表决定，不只看返回类型"],
          applications: ["输入解析", "规则判断", "结果计算"],
          pitfalls: ["整数除法丢失小数", "自动装箱后错误使用 =="],
          method: "先写类型签名，再完成控制流，最后用边界输入验证。",
          exercise: "实现一个成绩统计器，处理缺考、非法输入和等级计算。",
          checkpoint: "能解释基本类型与包装类型的区别及适用场景。",
        },
        {
          key: "java-oop",
          title: "类、接口与继承",
          summary: "封装、继承、多态、抽象类和接口。",
          concepts: ["构造器", "访问控制", "接口契约", "运行时多态"],
          principles: ["封装限制状态修改入口", "接口定义能力，实现类负责具体行为"],
          applications: ["支付渠道", "任务处理器", "领域模型"],
          pitfalls: ["滥用继承导致强耦合", "接口设计过宽导致实现类被迫空实现"],
          method: "从行为契约开始设计接口，再用组合和继承实现。",
          exercise: "实现多种通知渠道，并让调用方只依赖统一接口。",
          checkpoint: "能说明为什么替换具体实现时调用方不需要改变。",
        },
        {
          key: "java-exceptions",
          title: "异常与资源管理",
          summary: "异常层次、受检异常、try-with-resources 和日志。",
          concepts: ["checked/unchecked exception", "异常传播", "AutoCloseable", "日志上下文"],
          principles: ["异常用于表达无法继续执行的状态", "资源释放应绑定到明确作用域"],
          applications: ["文件处理", "数据库操作", "外部接口调用"],
          pitfalls: ["吞掉异常后继续执行", "finally 中重复关闭资源"],
          method: "区分可恢复错误与程序缺陷，只用捕获处理真正能恢复的情况。",
          exercise: "实现安全的配置文件读取和错误日志。",
          checkpoint: "能根据异常来源和恢复策略选择抛出、包装或处理。",
        },
      ],
      questionKeys: ["java-q1", "java-q2", "java-q3"],
    },
    {
      key: "java-collections",
      title: "集合、泛型与函数式",
      weeks: "第 4-6 周",
      goal: "熟练选择集合类型，理解泛型、Lambda、Stream 和函数式接口。",
      outcome: "能够完成一组可测试的数据聚合、分组和转换任务。",
      topics: [
        {
          key: "java-collections",
          title: "集合框架",
          summary: "List、Set、Map、队列与迭代器。",
          concepts: ["集合层次", "哈希与顺序", "equals/hashCode", "并发修改"],
          principles: ["集合选择取决于访问模式、顺序和唯一性要求", "HashMap 的键依赖 equals 和 hashCode 契约"],
          applications: ["去重", "索引", "任务队列"],
          pitfalls: ["遍历时直接修改集合", "只重写 equals 不重写 hashCode"],
          method: "先确定查询模式，再选择集合，并写测试验证重复和顺序。",
          exercise: "统计日志中独立用户、出现次数和 Top N 操作。",
          checkpoint: "能说明某个集合选择在时间和空间上的代价。",
        },
        {
          key: "java-generics",
          title: "泛型与类型边界",
          summary: "泛型类、通配符、PECS 和类型擦除。",
          concepts: ["类型参数", "extends/super", "泛型方法", "类型擦除"],
          principles: ["泛型在编译期提供类型安全，运行时存在类型擦除", "生产者使用 extends，消费者使用 super"],
          applications: ["仓库接口", "结果包装", "集合工具"],
          pitfalls: ["使用原始类型破坏类型安全", "试图在运行时直接获得泛型参数类型"],
          method: "先定义输入和输出角色，再决定通配符方向。",
          exercise: "实现类型安全的 Repository<T> 和结果容器。",
          checkpoint: "能解释 PECS 规则在某段代码中的具体作用。",
        },
        {
          key: "java-stream",
          title: "Lambda、Stream 与 Optional",
          summary: "函数式接口、流式管道、惰性执行和空值表达。",
          concepts: ["Lambda", "map/filter/reduce", "惰性求值", "Optional"],
          principles: ["Stream 是数据管道，不负责存储数据", "中间操作惰性执行，终止操作触发计算"],
          applications: ["数据转换", "分组统计", "批量校验"],
          pitfalls: ["复用已消耗的 Stream", "用 Optional 替代所有空值处理"],
          method: "先判断数据规模和副作用，再决定是否使用流式表达。",
          exercise: "用 Stream 完成订单分组、总价和超时检测。",
          checkpoint: "能区分中间操作与终止操作，并解释不会重复遍历的资源。",
        },
      ],
      questionKeys: ["java-q4", "java-q5", "java-q6"],
    },
    {
      key: "java-concurrency",
      title: "并发、JVM 与性能",
      weeks: "第 7-9 周",
      goal: "理解线程安全、并发工具、JVM 内存和基本性能分析。",
      outcome: "能定位常见并发问题，并使用合适工具保证共享状态安全。",
      topics: [
        {
          key: "java-threads",
          title: "线程与并发工具",
          summary: "线程生命周期、同步、锁、线程池和并发集合。",
          concepts: ["原子性、可见性、有序性", "synchronized", "ExecutorService", "ConcurrentHashMap"],
          principles: ["共享可变状态需要同步策略", "线程池通过复用线程控制资源上限"],
          applications: ["后台任务", "批量请求", "缓存"],
          pitfalls: ["在锁中执行慢操作", "直接依赖 HashMap 的并发读写"],
          method: "先定义共享状态和线程边界，再选择最小同步策略。",
          exercise: "实现限流的并发任务处理器并验证结果一致性。",
          checkpoint: "能指出代码中共享状态、竞争窗口和同步点。",
        },
        {
          key: "java-jvm",
          title: "JVM 内存与垃圾回收",
          summary: "类加载、堆栈、对象生命周期、GC 和诊断基础。",
          concepts: ["堆与栈", "类加载", "GC Roots", "分代回收"],
          principles: ["对象是否可回收取决于可达性，而非引用计数", "内存问题需要结合分配速率和存活对象分析"],
          applications: ["内存泄漏排查", "GC 日志", "启动性能"],
          pitfalls: ["把 GC 次数多直接等同于内存泄漏", "只看堆大小不看对象生命周期"],
          method: "先建立基线，再用线程、堆和 GC 三个视角定位问题。",
          exercise: "构造并定位一个缓存导致的持续内存增长问题。",
          checkpoint: "能用证据说明对象为何无法回收。",
        },
        {
          key: "java-performance",
          title: "性能与可观测性",
          summary: "基准测试、日志、指标、缓存和连接池。",
          concepts: ["JMH", "p95/p99", "缓存命中率", "连接池"],
          principles: ["没有测量就没有性能优化", "平均值会掩盖尾延迟"],
          applications: ["接口优化", "数据库访问", "缓存策略"],
          pitfalls: ["凭感觉做微优化", "忽略连接池和下游超时"],
          method: "先测量瓶颈，再改一个变量，最后用同一基准验证收益。",
          exercise: "为一个慢接口建立基准、指标和缓存优化方案。",
          checkpoint: "优化前后有可复现数据，并说明收益与代价。",
        },
      ],
      questionKeys: ["java-q7", "java-q8", "java-q9"],
    },
    {
      key: "java-engineering",
      title: "工程实践与设计模式",
      weeks: "第 10-12 周",
      goal: "掌握依赖管理、测试、设计模式和服务分层。",
      outcome: "完成一个可测试、可配置、边界清晰的 Java 服务。",
      topics: [
        {
          key: "java-build",
          title: "构建、依赖与测试",
          summary: "Maven/Gradle、依赖边界、JUnit 和测试替身。",
          concepts: ["坐标与依赖树", "构建生命周期", "单元测试", "Mock 与 Stub"],
          principles: ["构建工具负责依赖解析和可重复构建", "测试应隔离外部副作用并验证行为契约"],
          applications: ["服务构建", "CI 检查", "依赖冲突处理"],
          pitfalls: ["盲目排除依赖解决冲突", "测试真实调用外部服务"],
          method: "先让构建和测试可重复，再扩展功能。",
          exercise: "为服务模块配置构建、测试和依赖版本管理。",
          checkpoint: "换机器后能一条命令构建并运行全部测试。",
        },
        {
          key: "java-patterns",
          title: "常用设计模式",
          summary: "创建型、结构型和行为型模式的适用边界。",
          concepts: ["策略、工厂、适配器", "观察者、责任链", "依赖倒置"],
          principles: ["模式是解决重复设计问题的共同语言，不是到处套模板", "优先识别变化点，再把变化隔离"],
          applications: ["支付策略", "消息处理链", "外部系统适配"],
          pitfalls: ["为了模式增加无意义抽象", "把简单条件判断硬拆成多个类"],
          method: "先写出朴素实现，再根据变化和重复引入最小模式。",
          exercise: "把一段复杂条件分支重构为策略和责任链。",
          checkpoint: "重构后行为不变，扩展新分支时无需大面积修改已有代码。",
        },
        {
          key: "java-service",
          title: "服务分层与综合项目",
          summary: "控制器、应用服务、领域逻辑和基础设施边界。",
          concepts: ["DTO 与领域对象", "依赖注入", "事务边界", "错误模型"],
          principles: ["业务规则不应依赖 HTTP 或数据库细节", "事务边界应围绕一个业务不变量"],
          applications: ["任务 API", "订单服务", "后台管理系统"],
          pitfalls: ["所有逻辑写在 Controller", "在领域对象中直接访问数据库"],
          method: "先定义业务用例和事务边界，再向接口和基础设施适配。",
          exercise: "实现任务服务：创建、查询、更新状态、错误处理和测试。",
          checkpoint: "接口层、业务层和存储层可以独立替换与测试。",
        },
      ],
      questionKeys: ["java-q10", "java-q11", "java-q12"],
    },
  ],
  questions: [
    {
    key: "java-q1",
    stageKey: "java-foundation",
    topicKey: "java-types-control",
      type: "judge",
      stem: "Java 方法重载可以只通过不同的返回类型区分。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "方法重载由方法名和参数列表共同决定，返回类型不能单独用于区分重载。",
      difficulty: "easy",
      tags: ["方法", "重载"],
      sourceKey: "algorithms-java",
    },
    {
    key: "java-q2",
    stageKey: "java-foundation",
    topicKey: "java-oop",
      type: "single",
      stem: "面向对象设计中，封装最核心的目的是什么？",
      options: [
        { key: "A", text: "让字段全部公开" },
        { key: "B", text: "限制状态修改入口并维护不变量" },
        { key: "C", text: "增加继承层数" },
        { key: "D", text: "避免编写构造器" },
      ],
      answer: ["B"],
      explanation: "封装通过受控访问保护对象内部状态，让不变量只能通过明确方法改变。",
      difficulty: "easy",
      tags: ["封装", "OOP"],
      sourceKey: "java-patterns",
    },
    {
    key: "java-q3",
    stageKey: "java-foundation",
    topicKey: "java-exceptions",
      type: "single",
      stem: "读取文件后必须可靠关闭资源，优先使用哪种结构？",
      options: [
        { key: "A", text: "try-with-resources" },
        { key: "B", text: "无限循环" },
        { key: "C", text: "静态变量保存流" },
        { key: "D", text: "忽略关闭操作" },
      ],
      answer: ["A"],
      explanation: "try-with-resources 会在作用域结束时自动关闭实现 AutoCloseable 的资源，即使发生异常也能释放。",
      difficulty: "easy",
      tags: ["异常", "资源"],
      sourceKey: "algorithms-java",
    },
    {
    key: "java-q4",
    stageKey: "java-collections",
    topicKey: "java-collections",
      type: "single",
      stem: "需要在 HashMap 中把自定义对象作为键，通常必须正确实现什么？",
      options: [
        { key: "A", text: "toString 和 clone" },
        { key: "B", text: "equals 和 hashCode" },
        { key: "C", text: "finalize 和 wait" },
        { key: "D", text: "只有 getter" },
      ],
      answer: ["B"],
      explanation: "HashMap 依赖 hashCode 定位桶，并用 equals 判断键是否相等；两者必须遵守同一契约。",
      difficulty: "medium",
      tags: ["Map", "equals", "hashCode"],
      sourceKey: "algorithms-java",
    },
    {
    key: "java-q5",
    stageKey: "java-collections",
    topicKey: "java-generics",
      type: "single",
      stem: "PECS 原则中的 “Producer extends” 表示什么？",
      options: [
        { key: "A", text: "只读取数据的生产者使用 extends" },
        { key: "B", text: "所有泛型都必须使用 extends" },
        { key: "C", text: "只写数据的消费者使用 extends" },
        { key: "D", text: "extends 可以消除类型擦除" },
      ],
      answer: ["A"],
      explanation: "如果集合主要向外提供数据，它是生产者，使用 extends；主要接收数据时使用 super。",
      difficulty: "hard",
      tags: ["泛型", "PECS"],
      sourceKey: "algorithms-java",
    },
    {
    key: "java-q6",
    stageKey: "java-collections",
    topicKey: "java-stream",
      type: "judge",
      stem: "Stream 的中间操作在没有终止操作时通常不会执行。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "Stream 中间操作是惰性的，只有遇到终止操作时才真正触发管道计算。",
      difficulty: "medium",
      tags: ["Stream", "惰性求值"],
      sourceKey: "algorithms-java",
    },
    {
    key: "java-q7",
    stageKey: "java-concurrency",
    topicKey: "java-threads",
      type: "single",
      stem: "多个线程同时读写普通 HashMap 的主要风险是什么？",
      options: [
        { key: "A", text: "编译失败" },
        { key: "B", text: "数据竞争和结构损坏" },
        { key: "C", text: "自动变成只读" },
        { key: "D", text: "自动加锁" },
      ],
      answer: ["B"],
      explanation: "HashMap 不保证并发安全，并发写入可能导致丢失更新、错误读取或内部结构异常。",
      difficulty: "medium",
      tags: ["并发", "HashMap"],
      sourceKey: "advanced-java-reference",
    },
    {
    key: "java-q8",
    stageKey: "java-concurrency",
    topicKey: "java-jvm",
      type: "judge",
      stem: "JVM 只要发现对象没有被任何直接变量引用，就一定会立即回收该对象。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "JVM 通过可达性分析判断对象是否仍能从 GC Roots 到达；不可达只代表具备回收条件，回收时机由垃圾收集器决定。",
      difficulty: "medium",
      tags: ["JVM", "GC"],
      sourceKey: "advanced-java-reference",
    },
    {
    key: "java-q9",
    stageKey: "java-concurrency",
    topicKey: "java-performance",
      type: "single",
      stem: "评估接口性能时，为什么不能只看平均响应时间？",
      options: [
        { key: "A", text: "平均值无法展示尾延迟" },
        { key: "B", text: "平均值总是错误的" },
        { key: "C", text: "平均值只能整数" },
        { key: "D", text: "平均值代表吞吐量" },
      ],
      answer: ["A"],
      explanation: "少量极慢请求可能被平均值掩盖，因此还要关注 p95、p99 和错误率。",
      difficulty: "easy",
      tags: ["性能", "指标"],
      sourceKey: "tech-interview-handbook",
    },
    {
    key: "java-q10",
    stageKey: "java-engineering",
    topicKey: "java-build",
      type: "single",
      stem: "构建工具最重要的可复现能力之一是？",
      options: [
        { key: "A", text: "固定依赖解析并明确构建步骤" },
        { key: "B", text: "让每个开发机安装不同版本" },
        { key: "C", text: "跳过测试" },
        { key: "D", text: "只生成 IDE 文件" },
      ],
      answer: ["A"],
      explanation: "明确的依赖和构建生命周期能让本地、CI 和发布环境得到一致结果。",
      difficulty: "easy",
      tags: ["Maven", "Gradle", "CI"],
      sourceKey: "tech-interview-handbook",
    },
    {
    key: "java-q11",
    stageKey: "java-engineering",
    topicKey: "java-patterns",
      type: "judge",
      stem: "设计模式应优先于简单实现，只要项目变大就必须全部使用。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "模式解决具体变化和重复问题，过早套模式会增加抽象成本和维护难度。",
      difficulty: "medium",
      tags: ["设计模式", "重构"],
      sourceKey: "java-patterns",
    },
    {
    key: "java-q12",
    stageKey: "java-engineering",
    topicKey: "java-service",
      type: "single",
      stem: "服务分层设计中，业务规则最适合放在哪里？",
      options: [
        { key: "A", text: "Controller 的请求处理代码里" },
        { key: "B", text: "独立于 HTTP 和数据库细节的业务层" },
        { key: "C", text: "日志格式化器中" },
        { key: "D", text: "随机工具类中" },
      ],
      answer: ["B"],
      explanation: "业务规则应独立于展示和存储细节，才能在接口变化时保持稳定并便于测试。",
      difficulty: "medium",
      tags: ["分层", "服务设计"],
      sourceKey: "java-patterns",
    },
  ],
};
