import { judgeQuestion, singleQuestion } from "./question-builders";
import type { LearningTrack } from "./types";

export const linuxTrack: LearningTrack = {
  slug: "linux",
  title: "Linux 运维",
  category: "操作系统",
  level: "入门",
  accent: "#4D6B3C",
  softAccent: "#EEF5E8",
  icon: "terminal-outline",
  summary: "从命令行、文件和进程到网络、存储、服务管理与自动化，建立可靠的 Linux 运维基础。",
  whyLearn: "Linux 是服务器、云平台、容器和自动化系统共同的基础环境，排障能力直接影响交付稳定性。",
  prerequisites: ["了解文件与目录概念", "能在终端输入命令并阅读输出"],
  studyMethod: ["先在实验环境验证命令，再用于生产", "每条命令都记录输入、输出和影响范围", "用故障场景训练查看日志与证据链"],
  estimatedHours: 88,
  featured: false,
  sources: [
    {
      key: "algorithms-shell",
      name: "TheAlgorithms/Shell",
      url: "https://github.com/TheAlgorithms/Shell",
      license: "MIT",
      usage: "import",
      note: "Shell 脚本片段、文本处理与自动化练习",
    },
    {
      key: "command-line-reference",
      name: "The Art of Command Line",
      url: "https://github.com/jlevy/the-art-of-command-line",
      license: "CC BY-NC-SA 4.0",
      usage: "reference",
      note: "命令行工作流与排障方法参考，不直接复制正文",
    },
    {
      key: "linux-system-reference",
      name: "System Design Primer",
      url: "https://github.com/donnemartin/system-design-primer",
      license: "CC BY 4.0",
      usage: "reference",
      note: "系统边界、可靠性和性能分析方法",
    },
  ],
  stages: [
    {
      key: "linux-shell-files",
      title: "命令行、文件与文本处理",
      weeks: "第 1-3 周",
      goal: "熟练浏览文件系统、处理权限、组合管道并完成文本分析。",
      outcome: "能独立完成日志筛选、字段统计和文件批量整理。",
      topics: [
        {
          key: "linux-filesystem",
          title: "文件系统与路径",
          summary: "目录结构、路径、链接、查找和权限基础。",
          concepts: ["绝对与相对路径", "inode", "软链接与硬链接", "文件权限"],
          principles: ["Linux 用单一目录树组织所有文件系统", "链接类型决定目标删除后的行为"],
          applications: ["定位配置", "整理日志", "迁移文件"],
          pitfalls: ["在错误目录执行删除命令", "混淆软链接和硬链接"],
          method: "先确认当前目录和目标路径，再执行查找或修改操作。",
          exercise: "整理一组多层目录日志并按日期归档。",
          checkpoint: "能解释路径指向的真实文件以及权限允许的操作。",
        },
        {
          key: "linux-permissions",
          title: "用户、组与权限",
          summary: "rwx、chmod、chown、umask、sudo 和最小权限。",
          concepts: ["所有者/组/其他人", "八进制权限", "umask", "sudo"],
          principles: ["权限由身份和操作共同决定", "服务应以完成工作所需的最小权限运行"],
          applications: ["共享目录", "服务账号", "敏感配置"],
          pitfalls: ["用 777 粗暴解决权限问题", "让服务长期以 root 运行"],
          method: "先写清谁需要什么操作，再给最小权限并验证。",
          exercise: "为应用组配置只读配置和可写日志目录。",
          checkpoint: "不同用户测试结果符合权限设计，且没有额外授权。",
        },
        {
          key: "linux-text-pipeline",
          title: "文本与管道",
          summary: "grep、sed、awk、sort、uniq、xargs 和重定向。",
          concepts: ["标准输入输出错误", "管道", "正则表达式", "字段处理"],
          principles: ["小工具通过文本流组合完成复杂任务", "标准错误与标准输出分离便于诊断"],
          applications: ["日志统计", "批处理", "配置提取"],
          pitfalls: ["忽略特殊字符转义", "把未经校验的输入直接传给删除命令"],
          method: "每一步管道都先输出少量样例，确认后再扩大处理范围。",
          exercise: "统计访问日志状态码 Top 10 和异常来源。",
          checkpoint: "能从命令链说明每个中间结果和最终统计口径。",
        },
      ],
      questionKeys: ["linux-q1", "linux-q2", "linux-q3", "linux-q4"],
    },
    {
      key: "linux-process-system",
      title: "进程、服务与日志",
      weeks: "第 4-6 周",
      goal: "掌握进程管理、资源观察、systemd 服务和日志定位。",
      outcome: "能排查一个服务启动失败、资源异常或日志中断问题。",
      topics: [
        {
          key: "linux-processes",
          title: "进程与资源",
          summary: "进程树、信号、前后台任务、CPU 和内存观察。",
          concepts: ["PID/PPID", "信号", "前台后台", "负载与内存"],
          principles: ["进程状态变化由调度、等待和信号共同驱动", "负载必须结合 CPU 核数和等待类型解释"],
          applications: ["终止失控任务", "定位高占用进程", "服务重启"],
          pitfalls: ["直接用 kill -9 跳过清理", "只看内存总量不看可用与缓存"],
          method: "先观察进程树和资源趋势，再选择信号和处理顺序。",
          exercise: "定位一个持续占用 CPU 的任务并安全终止。",
          checkpoint: "能说明进程为什么异常以及终结操作的副作用。",
        },
        {
          key: "linux-systemd",
          title: "systemd 与服务管理",
          summary: "unit、依赖、启动、重启策略和开机自启。",
          concepts: ["service unit", "依赖关系", "restart 策略", "target"],
          principles: ["服务管理应声明依赖和重启策略，而不是依赖人工脚本顺序", "状态查询与日志查询是不同证据来源"],
          applications: ["应用服务", "定时任务", "基础组件"],
          pitfalls: ["修改 unit 后忘记 reload", "无限快速重启掩盖配置错误"],
          method: "从 unit 定义、运行状态和日志三个层面依次排查。",
          exercise: "为脚本创建 systemd 服务并验证失败自动重启。",
          checkpoint: "服务可重复启动、停止、查看状态和追踪日志。",
        },
        {
          key: "linux-logs",
          title: "日志与故障证据",
          summary: "journalctl、日志轮转、时间范围、关联请求和根因链。",
          concepts: ["journal", "日志级别", "时间窗口", "轮转"],
          principles: ["排障要从最早异常向前追踪，而不是只看最后一条错误", "日志需要时间、对象和上下文才能形成证据"],
          applications: ["服务启动失败", "认证异常", "磁盘写满"],
          pitfalls: ["只搜索 error 忽略 warning 和上游错误", "日志无限增长占满磁盘"],
          method: "固定问题时间段，再按服务、进程和关键字交叉过滤。",
          exercise: "从 journal 中还原一次数据库连接失败的时间线。",
          checkpoint: "能给出触发事件、影响范围和验证修复的证据。",
        },
      ],
      questionKeys: ["linux-q5", "linux-q6", "linux-q7", "linux-q8"],
    },
    {
      key: "linux-network-storage",
      title: "网络、SSH 与存储",
      weeks: "第 7-9 周",
      goal: "掌握网络诊断、远程访问安全、磁盘空间和文件系统检查。",
      outcome: "能定位常见连通性、端口、SSH 和磁盘空间问题。",
      topics: [
        {
          key: "linux-network",
          title: "网络诊断",
          summary: "IP、路由、DNS、端口、连通性和抓包基础。",
          concepts: ["地址与掩码", "路由表", "DNS", "TCP 端口"],
          principles: ["网络问题应按本机地址、路由、DNS、端口和对端逐层验证", "监听端口与防火墙放行是两个独立条件"],
          applications: ["服务不可达", "DNS 异常", "跨网段访问"],
          pitfalls: ["只 ping 通就认为服务正常", "忽略 DNS 缓存和防火墙规则"],
          method: "从本机到对端逐跳采集证据，避免同时修改多个变量。",
          exercise: "排查一个端口未开放的跨主机访问问题。",
          checkpoint: "能指出失败发生在哪一层，并给出对应验证命令。",
        },
        {
          key: "linux-ssh",
          title: "SSH 与访问安全",
          summary: "密钥认证、配置、端口转发、文件传输和最小暴露。",
          concepts: ["公钥认证", "authorized_keys", "known_hosts", "端口转发"],
          principles: ["密钥认证比共享密码更适合自动化访问", "远程访问应限制来源和可执行权限"],
          applications: ["服务器登录", "部署", "安全隧道"],
          pitfalls: ["私钥权限过宽", "允许 root 密码直接登录"],
          method: "先验证密钥与身份，再收紧密码、来源和权限。",
          exercise: "配置仅密钥登录的部署账号并测试 scp/rsync。",
          checkpoint: "账号只能访问授权资源，私钥不会暴露给其他用户。",
        },
        {
          key: "linux-storage",
          title: "磁盘与文件系统",
          summary: "容量、inode、挂载、日志占用、扩容和备份基础。",
          concepts: ["块设备", "挂载点", "inode", "日志文件"],
          principles: ["磁盘可用空间和 inode 都可能成为容量瓶颈", "删除已打开文件未必立即释放空间"],
          applications: ["磁盘告警", "日志清理", "挂载迁移"],
          pitfalls: ["大范围删除不确定文件", "忽略被进程占用的已删除文件"],
          method: "先定位占用层级和 inode，再决定清理、轮转或扩容。",
          exercise: "定位一次磁盘满告警并制定安全清理方案。",
          checkpoint: "清理前后空间变化有记录，业务文件未被误删。",
        },
      ],
      questionKeys: ["linux-q9", "linux-q10", "linux-q11", "linux-q12"],
    },
    {
      key: "linux-automation-ops",
      title: "Shell 自动化与生产运维",
      weeks: "第 10-12 周",
      goal: "编写可靠脚本、定时任务、备份巡检和故障恢复流程。",
      outcome: "交付一套带日志、校验、失败退出和回滚说明的自动化脚本。",
      topics: [
        {
          key: "linux-bash",
          title: "可靠 Shell 脚本",
          summary: "参数、变量、错误处理、函数和可重入设计。",
          concepts: ["set -euo pipefail", "退出码", "trap", "幂等"],
          principles: ["脚本应明确失败条件并尽早退出", "自动化必须考虑重复执行和部分完成"],
          applications: ["部署脚本", "巡检", "数据备份"],
          pitfalls: ["默认继续执行失败命令", "没有引号包变量导致分词"],
          method: "先定义输入、输出和失败规则，再实现步骤与日志。",
          exercise: "实现可重复执行的发布准备脚本并补齐退出码。",
          checkpoint: "重复执行不破坏数据，任一步失败都有明确记录。",
        },
        {
          key: "linux-scheduling",
          title: "定时任务与编排",
          summary: "cron、systemd timer、并发锁、重试和通知。",
          concepts: ["cron 表达式", "systemd timer", "锁文件", "重试"],
          principles: ["定时任务要控制重叠执行和失败可见性", "计划时间不代表任务一定按时完成"],
          applications: ["备份", "清理", "报表同步"],
          pitfalls: ["任务重叠造成数据竞争", "失败后无人收到通知"],
          method: "定义频率、最长执行时间和冲突策略，再选择调度器。",
          exercise: "为备份任务增加互斥锁、超时和告警。",
          checkpoint: "任务不会重叠，失败可查、可重试、可停止。",
        },
        {
          key: "linux-troubleshooting",
          title: "故障排查与备份恢复",
          summary: "分层排障、变更记录、备份校验和恢复演练。",
          concepts: ["现象与根因", "变更窗口", "RPO/RTO", "恢复演练"],
          principles: ["先止血再定位，任何变更都应可回滚", "没有验证过恢复的备份不算可靠备份"],
          applications: ["服务中断", "配置损坏", "数据误删"],
          pitfalls: ["在同一会话中连续改多个参数", "只看备份任务成功不看恢复结果"],
          method: "按现象、证据、假设、验证、修复五步记录排障过程。",
          exercise: "完成一次配置误删的恢复演练并记录时间线。",
          checkpoint: "恢复过程可复现，关键数据完整且耗时符合目标。",
        },
      ],
      questionKeys: ["linux-q13", "linux-q14", "linux-q15", "linux-q16"],
    },
  ],
  questions: [
    singleQuestion({
    key: "linux-q1",
    stageKey: "linux-shell-files",
    topicKey: "linux-filesystem",
      stem: "Linux 中所有已挂载文件系统统一从哪里开始组织？",
      options: ["C:\\", "/", "/home", "/mnt"],
      answer: "B",
      explanation: "Linux 使用以根目录 / 开始的单一目录树，其他文件系统挂载到树中的目录。",
      difficulty: "easy",
      tags: ["文件系统", "根目录"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q2",
    stageKey: "linux-shell-files",
    topicKey: "linux-permissions",
      stem: "把权限设置为 644 时，通常表示什么？",
      options: ["所有用户可写", "所有者可读写，组和其他人只读", "只有 root 可访问", "所有用户可执行"],
      answer: "B",
      explanation: "6 表示所有者读写，4 表示组只读，4 表示其他人只读。",
      difficulty: "medium",
      tags: ["权限", "chmod"],
      sourceKey: "command-line-reference",
    }),
    judgeQuestion({
    key: "linux-q3",
    stageKey: "linux-shell-files",
    topicKey: "linux-text-pipeline",
      stem: "管道可以把前一个命令的标准输出作为后一个命令的标准输入。",
      answer: true,
      explanation: "管道连接进程的数据流，让多个小工具组合完成复杂文本处理。",
      difficulty: "easy",
      tags: ["管道", "标准流"],
      sourceKey: "algorithms-shell",
    }),
    singleQuestion({
    key: "linux-q4",
    stageKey: "linux-shell-files",
    topicKey: "linux-text-pipeline",
      stem: "批量处理文件名前，最安全的习惯是什么？",
      options: ["直接执行 rm", "先用 echo 或 ls 检查匹配结果", "关闭错误输出", "使用 root 运行"],
      answer: "B",
      explanation: "先预览匹配集合，可以避免通配符或空格导致误删、误改。",
      difficulty: "easy",
      tags: ["批量操作", "安全"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q5",
    stageKey: "linux-process-system",
    topicKey: "linux-processes",
      stem: "系统负载较高但 CPU 使用率不高，可能还需要重点检查什么？",
      options: ["磁盘或网络等待", "字体设置", "桌面主题", "文件颜色"],
      answer: "A",
      explanation: "负载包含可运行和不可中断等待任务，I/O 等阻塞也会显著抬高负载。",
      difficulty: "medium",
      tags: ["进程", "负载"],
      sourceKey: "linux-system-reference",
    }),
    judgeQuestion({
    key: "linux-q6",
    stageKey: "linux-process-system",
    topicKey: "linux-processes",
      stem: "kill -9 应作为结束进程的首选手段，因为它总会立即生效。",
      answer: false,
      explanation: "SIGKILL 无法被清理逻辑捕获，可能留下锁文件或未完成写入，通常应先尝试温和终止。",
      difficulty: "medium",
      tags: ["信号", "进程"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q7",
    stageKey: "linux-process-system",
    topicKey: "linux-systemd",
      stem: "修改 systemd unit 文件后，通常需要先执行什么？",
      options: ["reboot", "systemctl daemon-reload", "rm -rf", "chmod 777"],
      answer: "B",
      explanation: "daemon-reload 让 systemd 重新读取 unit 定义，再进行重启或重新加载服务。",
      difficulty: "medium",
      tags: ["systemd", "服务"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q8",
    stageKey: "linux-process-system",
    topicKey: "linux-logs",
      stem: "排查服务启动失败时，哪组证据最有价值？",
      options: ["主题、壁纸、字体", "unit 状态、完整时间和关联日志", "文件名、大小、颜色", "网速测试"] ,
      answer: "B",
      explanation: "unit 定义、服务状态和最早关联错误能还原触发链，形成有效证据。",
      difficulty: "medium",
      tags: ["日志", "排障"],
      sourceKey: "linux-system-reference",
    }),
    singleQuestion({
    key: "linux-q9",
    stageKey: "linux-network-storage",
    topicKey: "linux-network",
      stem: "远程服务端口无法访问时，以下哪项需要独立确认？",
      options: ["服务是否监听且防火墙是否放行", "字体是否安装", "用户桌面背景", "编辑器主题"],
      answer: "A",
      explanation: "进程监听和网络放行是两个独立条件，任一未满足都会导致不可达。",
      difficulty: "medium",
      tags: ["网络", "端口"],
      sourceKey: "linux-system-reference",
    }),
    judgeQuestion({
    key: "linux-q10",
    stageKey: "linux-network-storage",
    topicKey: "linux-ssh",
      stem: "SSH 私钥文件应避免被同机其他用户读取。",
      answer: true,
      explanation: "私钥泄露等同于身份泄露，应设置严格权限并优先使用密钥代理或受控部署账号。",
      difficulty: "easy",
      tags: ["SSH", "密钥"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q11",
    stageKey: "linux-network-storage",
    topicKey: "linux-storage",
      stem: "df 显示有空间但创建文件失败，还应该检查什么？",
      options: ["inode 是否耗尽", "显卡驱动", "鼠标速度", "浏览器缓存"],
      answer: "A",
      explanation: "大量小文件可能耗尽 inode，即使块空间仍显示可用也无法创建新文件。",
      difficulty: "medium",
      tags: ["磁盘", "inode"],
      sourceKey: "linux-system-reference",
    }),
    judgeQuestion({
    key: "linux-q12",
    stageKey: "linux-network-storage",
    topicKey: "linux-storage",
      stem: "删除仍被进程打开的大文件后，磁盘空间可能不会立即释放。",
      answer: true,
      explanation: "只要文件仍被打开，inode 和磁盘块就可能继续占用，需重启或重新打开相关进程。",
      difficulty: "hard",
      tags: ["磁盘", "文件句柄"],
      sourceKey: "command-line-reference",
    }),
    singleQuestion({
    key: "linux-q13",
    stageKey: "linux-automation-ops",
    topicKey: "linux-bash",
      stem: "可靠 Shell 脚本通常应尽早启用什么？",
      options: ["set -euo pipefail", "set +e", "history -c", "chmod 777"],
      answer: "A",
      explanation: "该组合能在命令失败、未定义变量和管道失败时及时暴露问题。",
      difficulty: "medium",
      tags: ["Shell", "错误处理"],
      sourceKey: "algorithms-shell",
    }),
    singleQuestion({
    key: "linux-q14",
    stageKey: "linux-automation-ops",
    topicKey: "linux-scheduling",
      stem: "两个定时备份任务可能重叠执行时，最基本的保护是什么？",
      options: ["增加互斥锁", "改名字体", "关闭日志", "增加动画"],
      answer: "A",
      explanation: "互斥锁可以避免同一任务并发运行造成文件竞争、重复写入或资源争用。",
      difficulty: "medium",
      tags: ["定时任务", "并发"],
      sourceKey: "algorithms-shell",
    }),
    judgeQuestion({
    key: "linux-q15",
    stageKey: "linux-automation-ops",
    topicKey: "linux-troubleshooting",
      stem: "备份任务执行成功就代表备份一定可以恢复。",
      answer: false,
      explanation: "只有经过校验和恢复演练的备份才具备可信恢复能力，成功退出码不是充分证据。",
      difficulty: "medium",
      tags: ["备份", "恢复"],
      sourceKey: "linux-system-reference",
    }),
    singleQuestion({
    key: "linux-q16",
    stageKey: "linux-automation-ops",
    topicKey: "linux-troubleshooting",
      stem: "生产排障时，连续修改多个参数的主要风险是什么？",
      options: ["无法判断哪个变更真正起作用", "命令自动变短", "日志变多", "用户数增加"],
      answer: "A",
      explanation: "一次只改一个变量并记录结果，才能建立变更与现象之间的可靠因果关系。",
      difficulty: "easy",
      tags: ["排障", "变更"],
      sourceKey: "linux-system-reference",
    }),
  ],
};
