import { topicQuestionPair } from "./topic-question-builders";
import type { LearningTrack } from "./types";

export const networkEngineeringTrack: LearningTrack = {
  slug: "network-engineering",
  title: "网络工程",
  category: "网络工程",
  level: "入门",
  accent: "#C0562F",
  softAccent: "#FBEDE7",
  icon: "git-network-outline",
  summary: "从分层模型、编址与交换路由到安全互联、自动化与排障，建立能落地的网络工程能力。",
  whyLearn: "几乎所有「服务不可用」最终都要落到网络上看证据。能分层定位、能读懂抓包、能把配置纳入自动化，才算具备可交付的网络能力。",
  prerequisites: ["了解二进制与十进制转换", "能使用命令行查看本机地址与连通性"],
  studyMethod: ["每个结论都要落到具体报文字段或设备输出", "排障先分层再缩小范围，不猜", "配置变更前先备份并设计回退"],
  estimatedHours: 88,
  featured: false,
  sources: [
    {
      key: "tailscale",
      name: "Tailscale",
      url: "https://github.com/tailscale/tailscale",
      license: "BSD-3-Clause",
      usage: "import",
      note: "WireGuard 组网与密钥管理的工程实现参考",
    },
    {
      key: "napalm",
      name: "NAPALM",
      url: "https://github.com/napalm-automation/napalm",
      license: "Apache-2.0",
      usage: "reference",
      note: "多厂商设备自动化抽象层参考，只保留外链",
    },
    {
      key: "wireshark",
      name: "Wireshark",
      url: "https://github.com/wireshark/wireshark",
      license: "GPL-2.0",
      usage: "reference",
      note: "抓包与协议解析参考，不复制正文",
    },
  ],
  stages: [
    {
      key: "net-foundation",
      title: "网络基础与模型",
      weeks: "第 1-2 周",
      goal: "建立分层与封装的直觉，能读懂地址、掩码与端口的实际含义。",
      outcome: "能给出一台主机的地址规划，并说明一次通信在各层发生什么。",
      topics: [
        {
          key: "net-osi-tcpip",
          title: "分层模型与封装",
          summary: "OSI 与 TCP/IP 分层、封装解封装与各层职责。",
          concepts: ["分层与职责", "封装与解封装", "协议数据单元", "层间依赖"],
          principles: [
            "每层只解决自己的问题，并依赖下层提供的服务",
            "封装逐层加上头部，解封装逐层剥离，任一层出错都要在本层找证据",
            "分层是排障工具：定位到层，就把搜索范围缩小了一个数量级",
          ],
          applications: ["故障分层定位", "抓包分析", "设备职责划分"],
          pitfalls: ["跨层猜测原因（用应用报错直接断定链路问题）", "把二层与三层概念混用", "忽略 MTU 与分片"],
          method: "遇到问题先回答「在哪一层」，再决定看什么证据。",
          exercise: "描述一次网页访问在各层分别发生了什么，并指出每层可用的排障命令。",
          checkpoint: "能针对一个现象说出应该先看哪一层的什么证据。",
        },
        {
          key: "net-ip-addressing",
          title: "IP 编址与子网",
          summary: "地址分类、掩码、网段与地址规划的常见做法。",
          concepts: ["地址与掩码", "网络地址与广播地址", "VLSM 与规划", "私有地址范围"],
          principles: [
            "掩码决定网络位长度，也就决定了同一网段内可用的主机数",
            "网络地址与广播地址不可分配给主机，规划时必须先扣除",
            "地址规划应按用途分区预留，避免把管理、业务与互联地址混在一个网段",
          ],
          applications: ["园区网规划", "互联地址分配", "地址容量评估"],
          pitfalls: ["掩码写错导致同网段主机不互通", "把网关地址占用主机可用区间", "没有预留扩展空间"],
          method: "先按用途划分区块并留出扩展余量，再逐块细分掩码。",
          exercise: "把一个网段划分给管理、业务与互联三类用途，写出每个子网的地址范围与可用主机数。",
          checkpoint: "能验算任一子网的网络地址、广播地址与可用范围。",
        },
        {
          key: "net-tcp-udp",
          title: "TCP/UDP 与端口",
          summary: "连接建立与断开、可靠传输机制与端口语义。",
          concepts: ["三次握手与四次挥手", "序列号与确认", "重传与窗口", "端口与监听"],
          principles: [
            "TCP 用确认与重传换可靠，UDP 用放弃可靠性换低开销",
            "握手失败与连接被拒反映不同问题：前者通常是路径或策略拦截，后者是端口没有监听",
            "TIME_WAIT 是正常状态，不应为了让统计好看而随意缩短",
          ],
          applications: ["服务端口规划", "连接类故障定位", "性能与延迟分析"],
          pitfalls: ["把所有连接失败都归因于防火墙", "忽略重传导致的慢而不是断", "长时间保持大量半开连接"],
          method: "先区分是「连不上」还是「连上了但慢」，再选对应的排查手段。",
          exercise: "用抓包或状态命令观察一次成功的握手与一次被拒绝的连接，比较两者证据差异。",
          checkpoint: "能根据现象判断问题出在握手阶段还是数据传输阶段。",
        },
      ],
      questionKeys: [
        "net-osi-tcpip-single",
        "net-osi-tcpip-judge",
        "net-ip-addressing-single",
        "net-ip-addressing-judge",
        "net-tcp-udp-single",
        "net-tcp-udp-judge",
      ],
    },
    {
      key: "net-lan",
      title: "交换与园区网",
      weeks: "第 3-4 周",
      goal: "掌握二层隔离、三层转发与地址服务，能设计一个可分区的园区网络。",
      outcome: "能给出带 VLAN 划分、路由与地址服务的园区方案并说明流量路径。",
      topics: [
        {
          key: "net-ethernet-vlan",
          title: "以太网与 VLAN",
          summary: "MAC 寻址、交换机转发与 VLAN 隔离。",
          concepts: ["MAC 与转发表", "广播域", "VLAN 与标签", "Trunk 与 Access"],
          principles: [
            "交换机按目的 MAC 转发，未知单播会在广播域内泛洪",
            "VLAN 把一个物理网络切成多个广播域，是二层隔离的基本手段",
            "Trunk 链路承载多 VLAN 标签，两端标签处理方式必须一致",
          ],
          applications: ["部门隔离", "访客网络", "二层环路防护"],
          pitfalls: ["VLAN 未做中继导致跨交换机不通", "Trunk 两端允许列表不一致", "放通全部 VLAN 造成隔离失效"],
          method: "先按隔离需求分 VLAN，再设计 Trunk 与 Access 端口并明确允许列表。",
          exercise: "为三个部门设计 VLAN 划分与交换机端口配置，说明跨交换机的标签处理。",
          checkpoint: "能画出广播域边界，并说明哪些流量不会跨 VLAN。",
        },
        {
          key: "net-routing",
          title: "路由与网关",
          summary: "路由表、最长前缀匹配与静态/动态路由取舍。",
          concepts: ["路由表与下一跳", "最长前缀匹配", "静态路由", "动态路由与邻居"],
          principles: [
            "转发按最长前缀匹配，掩码更精确的路由优先",
            "静态路由简单可控但不自愈，动态路由能收敛但引入复杂度",
            "默认路由是最后手段，指向错误会造成黑洞",
          ],
          applications: ["区域互联", "出口选路", "多路径冗余"],
          pitfalls: ["静态路由指向的下一跳不可达造成黑洞", "掩码写错导致路由覆盖范围异常", "未规划回程路由"],
          method: "先画清区域与流量方向，再决定哪些用静态、哪些交给动态协议。",
          exercise: "为三个区域设计路由方案，写出每个设备的路由表条目并说明选路结果。",
          checkpoint: "能说明去程与回程各自经过哪条路由，并验证对称性。",
        },
        {
          key: "net-nat-dhcp",
          title: "NAT、DHCP 与地址服务",
          summary: "地址转换、动态分配与中继的基本机制。",
          concepts: ["源地址转换", "端口复用", "DHCP 分配流程", "DHCP 中继"],
          principles: [
            "NAT 改写地址与端口来复用公网地址，代价是外部无法主动发起连接",
            "DHCP 分配需要地址池、租期与网关信息三件套",
            "跨网段的地址分配必须依赖中继，否则广播无法穿越三层边界",
          ],
          applications: ["出口共享", "终端自动配置", "访客接入"],
          pitfalls: ["地址池小于并发终端数导致获取失败", "中继未配置导致跨网段拿不到地址", "NAT 会话表占满造成新连接失败"],
          method: "先算并发终端数量与地址池容量，再设计租期与中继位置。",
          exercise: "为一个 200 终端的办公区设计地址池与租期，并说明跨网段如何分配。",
          checkpoint: "能说明终端获取地址的完整过程与失败时的定位点。",
        },
      ],
      questionKeys: [
        "net-ethernet-vlan-single",
        "net-ethernet-vlan-judge",
        "net-routing-single",
        "net-routing-judge",
        "net-nat-dhcp-single",
        "net-nat-dhcp-judge",
      ],
    },
    {
      key: "net-security",
      title: "安全与互联",
      weeks: "第 5-6 周",
      goal: "用策略和互联技术控制访问范围，让必要的流量通过、其余默认拒绝。",
      outcome: "能设计一套分区策略与站点互联方案，并说明每条规则的依据。",
      topics: [
        {
          key: "net-firewall-acl",
          title: "防火墙与 ACL",
          summary: "规则匹配顺序、状态检测与策略设计方法。",
          concepts: ["规则匹配顺序", "状态检测", "默认策略", "策略与对象"],
          principles: [
            "规则自上而下匹配，命中即生效，因此顺序本身就是逻辑",
            "状态检测让回程流量自动放通，无需显式写反向规则",
            "默认拒绝是安全基线，放通规则必须写明依据与有效期",
          ],
          applications: ["区域隔离", "对外服务发布", "临时排障放通"],
          pitfalls: ["宽泛规则写在精确规则之前导致后者失效", "临时放通忘记回收", "策略无注释导致无人敢改"],
          method: "先按区域画出必要的流量矩阵，再把矩阵翻译成有序规则。",
          exercise: "为互联网区、应用区与数据区写出流量矩阵，并转成带顺序的规则清单。",
          checkpoint: "能说明每条规则对应的流量需求，以及删除它的影响。",
        },
        {
          key: "net-vpn-site",
          title: "站点互联与 VPN",
          summary: "隧道、密钥与路由如何在站点之间建立可达性。",
          concepts: ["隧道与封装", "预共享密钥与证书", "感兴趣流", "路由注入"],
          principles: [
            "VPN 只负责把包安全送到对端，可达性仍要靠路由与策略配合",
            "两端参数（加密算法、密钥、感兴趣流）必须完全一致才能协商成功",
            "路由注入决定哪些网段走隧道，漏配会造成单向可达",
          ],
          applications: ["分支互联", "远程接入", "跨云打通"],
          pitfalls: ["两端感兴趣流不匹配导致协商不起来", "只注入去程路由导致单向通", "密钥强度不足或长期不轮换"],
          method: "先把两端参数逐项对齐，再确认路由双向注入。",
          exercise: "写出两端隧道参数对照表与路由注入清单，并说明验证连通性的步骤。",
          checkpoint: "能通过协商状态与路由表判断隧道是否真正可用。",
        },
        {
          key: "net-wireless",
          title: "无线与接入控制",
          summary: "无线覆盖、认证方式与访客隔离的设计要点。",
          concepts: ["频段与信道", "认证与加密", "漫游", "访客隔离"],
          principles: [
            "相邻接入点信道重叠会造成同频干扰，覆盖规划必须先做信道分配",
            "企业级认证应绑定身份系统，而不是共用一个长期密码",
            "访客网络必须与内网隔离，避免访客设备成为进入内网的跳板",
          ],
          applications: ["办公无线", "访客接入", "会议室高密度覆盖"],
          pitfalls: ["信道全用默认值造成互相干扰", "访客与办公共用一个 SSID", "只看信号强度不看实际吞吐"],
          method: "先做覆盖与信道规划，再设计认证方式与网络隔离。",
          exercise: "为一个两层办公区规划接入点位置与信道，并设计访客网络隔离方案。",
          checkpoint: "能说明无线问题的判断依据是干扰、覆盖还是认证。",
        },
      ],
      questionKeys: [
        "net-firewall-acl-single",
        "net-firewall-acl-judge",
        "net-vpn-site-single",
        "net-vpn-site-judge",
        "net-wireless-single",
        "net-wireless-judge",
      ],
    },
    {
      key: "net-automation",
      title: "自动化与排障",
      weeks: "第 7-8 周",
      goal: "把抓包、配置自动化与分层排障串成可复用的工作方法。",
      outcome: "能用证据链定位一次真实网络故障，并把配置纳入备份与自动化流程。",
      topics: [
        {
          key: "net-monitor-capture",
          title: "抓包与流量分析",
          summary: "抓包点选择、过滤器与关键字段解读。",
          concepts: ["抓包点选择", "捕获与显示过滤", "关键字段", "重传与乱序"],
          principles: [
            "抓包点决定你看到的是原始流量还是转换后的流量，选错会得出相反结论",
            "先缩小范围再抓：按主机、端口或协议过滤，避免被海量无关包淹没",
            "重传、乱序与零窗口分别指向丢包、路径变化与接收端处理不过来",
          ],
          applications: ["慢请求定位", "连接失败分析", "策略是否生效验证"],
          pitfalls: ["抓包点选在 NAT 之后导致地址判断错误", "不带过滤抓全量导致分析成本极高", "抓到包就下结论而不对照时间线"],
          method: "先确定要证明什么，再选抓包点与过滤器，最后对照时间线解读。",
          exercise: "为一次「连接被拒绝」的报障选择抓包点与过滤器，并列出要观察的字段。",
          checkpoint: "能根据抓包结果区分丢包、策略拦截与端口未监听。",
        },
        {
          key: "net-config-automation",
          title: "配置自动化与备份",
          summary: "批量下发、配置模板与变更回退。",
          concepts: ["配置模板与变量", "批量执行与并发", "配置备份与比对", "变更回退"],
          principles: [
            "变更前必须留存当前配置，否则回退只能靠记忆",
            "模板把差异集中到变量，避免为每台设备单独维护一份配置",
            "批量下发要控制并发并逐台校验结果，不能只看命令是否返回成功",
          ],
          applications: ["批量开局", "配置巡检", "合规比对"],
          pitfalls: ["无备份直接改配置", "一次性对全部设备并发下发导致同时失联", "只看返回码不核对实际生效结果"],
          method: "先备份并生成差异，再小批量试点，最后分批推广并逐台校验。",
          exercise: "写出一份变更流程：备份、生成差异、试点、分批下发、逐台校验、回退条件。",
          checkpoint: "能说明变更失败时如何恢复到变更前状态。",
        },
        {
          key: "net-troubleshoot",
          title: "分层排障方法",
          summary: "从现象到根因的结构化排障流程与证据链。",
          concepts: ["现象与范围", "自下而上与自上而下", "分段验证", "证据链与复盘"],
          principles: [
            "先确定影响范围：一台还是全部、一个方向还是双向，范围直接决定根因位置",
            "分段验证把长路径切成小段，逐段确认可达性，避免在整条链路上猜",
            "每个结论都要有对应证据，没有证据的「应该没问题」不算结论",
          ],
          applications: ["业务不通排障", "性能下降定位", "变更后回归验证"],
          pitfalls: ["从最复杂的原因开始假设", "同时修改多个变量导致无法归因", "解决问题但不复盘根因"],
          method: "先定范围、再分段、每段留证据，最后复盘并补监控。",
          exercise: "为一个「部分用户无法访问」的场景写出分段验证步骤与每步的判定标准。",
          checkpoint: "能给出完整证据链，指向单一根因而不是一串可能性。",
        },
      ],
      questionKeys: [
        "net-monitor-capture-single",
        "net-monitor-capture-judge",
        "net-config-automation-single",
        "net-config-automation-judge",
        "net-troubleshoot-single",
        "net-troubleshoot-judge",
      ],
    },
  ],
  questions: [
    ...topicQuestionPair(
      "net-osi-tcpip",
      "net-foundation",
      {
        stem: "应用报「连接超时」，按分层方法最先应该确认什么？",
        options: ["应用代码是否有 bug", "网络层与传输层是否可达、端口是否可达", "数据库索引是否缺失", "服务器内存是否充足"],
        answer: "B",
        explanation: "超时意味着包没有正常到达或没有回应，应先确认连通性与端口可达性，把范围收窄到具体层次再深入。",
        difficulty: "medium",
        tags: ["分层排障", "超时"],
        sourceKey: "wireshark",
      },
      {
        stem: "封装过程中每层都会加上自己的头部，解封装时逐层剥离。",
        answer: true,
        explanation: "分层封装让各层独立演进，排障时也能按层定位：在哪一层中断，问题就在那一层或其下层。",
        difficulty: "easy",
        tags: ["封装", "分层"],
        sourceKey: "wireshark",
      }
    ),
    ...topicQuestionPair(
      "net-ip-addressing",
      "net-foundation",
      {
        stem: "一个 /24 子网中，可分配给主机的地址个数是多少？",
        options: ["256", "255", "254", "128"],
        answer: "C",
        explanation: "总地址 256 个，扣除网络地址与广播地址后剩 254 个可分配给主机。",
        difficulty: "easy",
        tags: ["子网", "可用地址"],
        sourceKey: "napalm",
      },
      {
        stem: "两台主机掩码不一致时，即使地址看起来在同一网段也可能无法通信。",
        answer: true,
        explanation: "主机用自己的掩码判断目标是否同网段，判断结果不同就会走不同的转发路径，导致单向或双向不通。",
        difficulty: "medium",
        tags: ["掩码", "同网段判断"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-tcp-udp",
      "net-foundation",
      {
        stem: "「连接被拒绝」与「连接超时」的区别说明了什么？",
        options: ["完全相同", "被拒绝说明对端可达但端口未监听，超时通常指路径或策略阻断", "被拒绝说明链路中断", "超时说明端口未监听"],
        answer: "B",
        explanation: "收到拒绝说明包已到达对端且有响应，问题在端口；超时说明包未被回应，问题更可能在路径、策略或对端沉默丢弃。",
        difficulty: "medium",
        tags: ["TCP", "连接失败"],
        sourceKey: "wireshark",
      },
      {
        stem: "TIME_WAIT 是 TCP 的正常状态，不应为了统计好看随意缩短。",
        answer: true,
        explanation: "TIME_WAIT 保证旧连接的延迟报文不会污染新连接；随意缩短会引入难以定位的异常。",
        difficulty: "medium",
        tags: ["TIME_WAIT", "TCP 状态"],
        sourceKey: "tailscale",
      }
    ),
    ...topicQuestionPair(
      "net-ethernet-vlan",
      "net-lan",
      {
        stem: "跨交换机通信时，承载多个 VLAN 的链路应配置成什么？",
        options: ["Access 端口", "Trunk 端口", "镜像端口", "未配置端口"],
        answer: "B",
        explanation: "Trunk 链路用标签区分 VLAN，两端允许列表必须一致，否则部分 VLAN 的流量会被丢弃。",
        difficulty: "easy",
        tags: ["VLAN", "Trunk"],
        sourceKey: "napalm",
      },
      {
        stem: "不同 VLAN 的主机默认可以直接二层互通。",
        answer: false,
        explanation: "VLAN 划分的就是广播域，跨 VLAN 通信必须经过三层设备做路由转发。",
        difficulty: "easy",
        tags: ["VLAN", "二层隔离"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-routing",
      "net-lan",
      {
        stem: "路由表中同时存在 /16 与 /24 两条可达路由时，转发会选哪条？",
        options: ["/16", "/24", "随机选择", "两条都发"],
        answer: "B",
        explanation: "转发按最长前缀匹配，掩码更精确的路由优先，因为它描述的目标范围更小。",
        difficulty: "medium",
        tags: ["路由", "最长前缀匹配"],
        sourceKey: "napalm",
      },
      {
        stem: "只要配置了去程路由，业务就一定可以正常通信。",
        answer: false,
        explanation: "通信需要双向可达；回程路由缺失会造成请求到达但响应回不来，表现为单向不通。",
        difficulty: "medium",
        tags: ["回程路由", "双向可达"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-nat-dhcp",
      "net-lan",
      {
        stem: "跨网段的终端无法自动获取地址，最可能缺少什么配置？",
        options: ["更长的租期", "DHCP 中继", "更多地址池", "更大的掩码"],
        answer: "B",
        explanation: "DHCP 请求是广播，不能穿越三层边界；跨网段分配必须由中继把请求转发到服务器。",
        difficulty: "medium",
        tags: ["DHCP", "中继"],
        sourceKey: "napalm",
      },
      {
        stem: "使用地址转换后，外部网络通常无法主动向内部主机发起连接。",
        answer: true,
        explanation: "地址转换依赖内部发起的会话表项；没有表项时外部主动连接无法映射到内部主机，需要显式端口映射。",
        difficulty: "medium",
        tags: ["NAT", "会话表"],
        sourceKey: "tailscale",
      }
    ),
    ...topicQuestionPair(
      "net-firewall-acl",
      "net-security",
      {
        stem: "一条宽泛的放通规则写在精确规则之前，会造成什么后果？",
        options: ["规则被自动重排", "精确规则永远不生效", "设备报错重启", "两条规则同时生效"],
        answer: "B",
        explanation: "规则自上而下匹配，命中即停止，因此宽泛规则在前会让后面的精确规则形同虚设。",
        difficulty: "medium",
        tags: ["ACL", "规则顺序"],
        sourceKey: "napalm",
      },
      {
        stem: "启用状态检测后，回程流量通常无需再显式编写反向放通规则。",
        answer: true,
        explanation: "状态检测记录已建立的会话，属于该会话的回程包自动放通，减少规则数量与出错概率。",
        difficulty: "medium",
        tags: ["状态检测", "防火墙"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-vpn-site",
      "net-security",
      {
        stem: "两端隧道参数不一致最直接的表现是什么？",
        options: ["隧道能建立但速度慢", "协商无法完成，隧道建立不起来", "路由自动修正", "加密强度下降"],
        answer: "B",
        explanation: "加密算法、密钥与感兴趣流必须完全匹配，任一项不一致都会导致协商失败，隧道无法进入可用状态。",
        difficulty: "medium",
        tags: ["VPN", "协商"],
        sourceKey: "tailscale",
      },
      {
        stem: "隧道建立成功就说明两端网段一定可以互相访问。",
        answer: false,
        explanation: "隧道只提供安全通道，可达性还需要两端正确注入路由并放通策略，漏配就会单向不通。",
        difficulty: "medium",
        tags: ["VPN", "路由注入"],
        sourceKey: "tailscale",
      }
    ),
    ...topicQuestionPair(
      "net-wireless",
      "net-security",
      {
        stem: "高密度会议室无线体验差，最应该先检查什么？",
        options: ["终端品牌", "信道分配与同频干扰", "SSID 名称长度", "密码复杂度"],
        answer: "B",
        explanation: "高密度场景的首要问题是相邻接入点信道重叠造成的同频干扰，先做信道与功率规划再看容量。",
        difficulty: "medium",
        tags: ["无线", "信道"],
        sourceKey: "tailscale",
      },
      {
        stem: "访客网络应与内网隔离，避免访客设备成为进入内网的跳板。",
        answer: true,
        explanation: "访客设备不受企业终端管理约束，必须通过独立 VLAN 与策略与内网隔离。",
        difficulty: "easy",
        tags: ["访客网络", "隔离"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-monitor-capture",
      "net-automation",
      {
        stem: "在地址转换之后的链路上抓包，最可能带来什么误判？",
        options: ["抓不到任何包", "看到的地址不是终端原始地址，导致判断错对象", "包内容被解密", "时间戳全为 0"],
        answer: "B",
        explanation: "抓包点看到的地址取决于所处位置，转换之后的地址已被改写，会让人误判是谁在通信。",
        difficulty: "medium",
        tags: ["抓包点", "地址转换"],
        sourceKey: "wireshark",
      },
      {
        stem: "抓包时先按主机或端口过滤，可以显著降低分析成本。",
        answer: true,
        explanation: "先缩小范围能把海量无关报文排除在外，让关键交互及其时间线更容易被看清。",
        difficulty: "easy",
        tags: ["过滤器", "抓包"],
        sourceKey: "wireshark",
      }
    ),
    ...topicQuestionPair(
      "net-config-automation",
      "net-automation",
      {
        stem: "批量下发配置前最重要的准备动作是什么？",
        options: ["提高并发数", "先备份当前配置并准备回退方案", "缩短命令长度", "关闭日志"],
        answer: "B",
        explanation: "没有备份就只能靠记忆恢复；备份与回退方案是批量变更能够安全进行的前提。",
        difficulty: "easy",
        tags: ["配置备份", "回退"],
        sourceKey: "napalm",
      },
      {
        stem: "批量下发时命令返回成功，就说明配置已经正确生效。",
        answer: false,
        explanation: "设备接受命令不等于配置生效，必须回读实际配置或校验状态，逐台确认结果。",
        difficulty: "medium",
        tags: ["批量变更", "校验"],
        sourceKey: "napalm",
      }
    ),
    ...topicQuestionPair(
      "net-troubleshoot",
      "net-automation",
      {
        stem: "排障时先确定影响范围的价值是什么？",
        options: ["满足流程要求", "范围直接决定根因大致位置，能大幅缩小搜索空间", "便于写报告", "可以跳过验证"],
        answer: "B",
        explanation: "「一台还是全部」「一个方向还是双向」这类信息能把根因锁定在共享环节还是个体环节，是最省时间的判断。",
        difficulty: "medium",
        tags: ["排障方法", "影响范围"],
        sourceKey: "wireshark",
      },
      {
        stem: "一次只改一个变量，是让排障结论可归因的关键纪律。",
        answer: true,
        explanation: "同时改动多个变量后即使问题消失，也无法知道是哪一处修复起作用，下次遇到同类问题仍无经验可复用。",
        difficulty: "easy",
        tags: ["排障纪律", "可归因"],
        sourceKey: "napalm",
      }
    ),
  ],
};
