import type { LearningTrack } from "./types";

export const powerBiTrack: LearningTrack = {
  slug: "power-bi",
  title: "Power BI",
  category: "商业智能",
  level: "进阶",
  accent: "#D99000",
  softAccent: "#FCF3DF",
  icon: "bar-chart-outline",
  summary: "从数据获取、Power Query、语义模型到 DAX、报表、安全与发布，覆盖完整 BI 交付链。",
  whyLearn: "Power BI 能把分散数据转换为可持续更新的业务语义和决策界面，是数据分析岗位的重要工具。",
  prerequisites: ["理解表格、关系和基础 SQL", "知道维度、指标和数据粒度"],
  studyMethod: ["先设计模型，再写 DAX", "每个度量值都验证筛选上下文", "报表先讲业务问题再考虑视觉样式"],
  estimatedHours: 84,
  featured: true,
  sources: [
    {
      key: "pl300",
      name: "Microsoft PL-300 Power BI Data Analyst",
      url: "https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst",
      license: "MIT",
      usage: "import",
      note: "微软官方 12 个实验室模块与考试知识结构",
    },
    {
      key: "powerbi-samples",
      name: "Power BI Desktop Samples",
      url: "https://github.com/microsoft/powerbi-desktop-samples",
      license: "MIT",
      usage: "import",
      note: "月度示例文件和真实业务模型素材",
    },
  ],
  stages: [
    {
      key: "powerbi-ingest",
      title: "数据获取与 Power Query",
      weeks: "第 1-2 周",
      goal: "连接常见数据源，理解查询步骤、数据类型和结构化转换。",
      outcome: "能构建可刷新、可追踪、用途明确的数据准备查询。",
      topics: [
        {
          key: "powerbi-connect",
          title: "数据源与连接模式",
          summary: "文件、数据库、Web 数据源以及 Import/DirectQuery 差异。",
          concepts: ["数据源凭据", "导入模式", "DirectQuery", "增量刷新"],
          principles: ["连接模式决定数据新鲜度、性能和模型能力", "先明确刷新需求再选择模式"],
          applications: ["Excel 报表", "数据库分析", "云服务数据源"],
          pitfalls: ["默认导入所有列", "未检查数据刷新边界"],
          method: "从数据规模、刷新频率和计算需求三个维度选择连接模式。",
          exercise: "连接一个订单数据源并说明选择当前模式的原因。",
          checkpoint: "能解释刷新后数据、性能和模型限制的权衡。",
        },
        {
          key: "powerbi-power-query",
          title: "Power Query 转换",
          summary: "步骤、数据类型、合并、追加、透视和分组。",
          concepts: ["Applied Steps", "M 语言", "列质量", "合并与追加"],
          principles: ["查询步骤应可读、可回退、可解释", "类型和粒度错误越早修复成本越低"],
          applications: ["清洗 Excel", "合并多表", "构建维度表"],
          pitfalls: ["在源查询中做展示性修改", "删除步骤后依赖断裂"],
          method: "先整理字段和类型，再处理重复、缺失和关系键。",
          exercise: "清洗销售表、产品表和日期表，输出可建模查询。",
          checkpoint: "每一步转换都有业务含义，且刷新后结果稳定。",
        },
        {
          key: "powerbi-parameters",
          title: "参数与可复用查询",
          summary: "参数、函数、模板查询和错误处理。",
          concepts: ["参数", "自定义函数", "查询复用", "错误处理"],
          principles: ["重复逻辑应作为参数或函数集中维护", "错误处理要保留失败上下文"],
          applications: ["切换环境", "批量表处理", "动态路径"],
          pitfalls: ["硬编码路径", "函数过度抽象导致调试困难"],
          method: "识别重复步骤和变量，再决定使用参数还是函数。",
          exercise: "把日期表生成逻辑封装为可复用查询。",
          checkpoint: "更换文件或环境时只需调整参数，无需改每条查询。",
        },
      ],
      questionKeys: ["pbi-q1", "pbi-q2", "pbi-q3"],
    },
    {
      key: "powerbi-model",
      title: "语义模型与关系",
      weeks: "第 3-4 周",
      goal: "建立星型模型、关系、层次结构和日期表。",
      outcome: "完成一个粒度一致、关系正确、可扩展的 Power BI 语义模型。",
      topics: [
        {
          key: "powerbi-star-schema",
          title: "星型模型与粒度",
          summary: "事实表、维度表、代理键和关系基数。",
          concepts: ["事实与维度", "粒度", "主键/外键", "星型与雪花"],
          principles: ["事实表记录业务事件，维度表描述分析上下文", "模型中的关系必须保持唯一且可解释"],
          applications: ["销售分析", "课程运营", "服务监控"],
          pitfalls: ["在同一事实表中混入多个粒度", "使用低质量业务键关联"],
          method: "先定义事实粒度，再为每个分析维度建立唯一键。",
          exercise: "为销售数据设计事实表与产品、客户、日期维度表。",
          checkpoint: "每个事实指标都能通过对唯一维度的筛选解释。",
        },
        {
          key: "powerbi-relationships",
          title: "关系与筛选传播",
          summary: "一对多、多对多、双向筛选和无效关系。",
          concepts: ["关系方向", "筛选传播", "桥接表", "活动关系"],
          principles: ["筛选通常从一对多中的一端流向多端", "双向筛选会增加歧义和性能成本"],
          applications: ["多对多标签", "角色维度", "日期关系"],
          pitfalls: ["无脑开启双向关系", "关系指向错误键导致结果错误"],
          method: "先画关系图，再验证每个维度对指标的筛选效果。",
          exercise: "修复一个因多对多关系导致指标翻倍的模型。",
          checkpoint: "能通过查看关系图解释任一筛选如何影响事实表。",
        },
        {
          key: "powerbi-date-table",
          title: "日期表与模型可用性",
          summary: "连续日期、标记日期表、层次和模型元数据。",
          concepts: ["日期主键", "连续日期", "日期层次", "模型元数据"],
          principles: ["时间智能依赖连续且标记正确的日期表", "日期维度应独立于事实日期列"],
          applications: ["同比环比", "月累计", "财年分析"],
          pitfalls: ["直接使用事实表日期列", "日期表存在断档"],
          method: "先重建连续日期表并建立一对多关系。",
          exercise: "为订单模型添加日期表和年月层次。",
          checkpoint: "时间智能函数返回稳定结果，切片器可正确筛选。",
        },
      ],
      questionKeys: ["pbi-q4", "pbi-q5", "pbi-q6"],
    },
    {
      key: "powerbi-dax",
      title: "DAX、筛选上下文与时间智能",
      weeks: "第 5-7 周",
      goal: "掌握计算列、度量值、筛选上下文、CALCULATE 和时间智能。",
      outcome: "能写出可验证、可复用、性能合理的业务指标。",
      topics: [
        {
          key: "powerbi-dax-basics",
          title: "DAX 基础与上下文",
          summary: "行上下文、筛选上下文、计算列与度量值。",
          concepts: ["行上下文", "筛选上下文", "聚合函数", "迭代函数"],
          principles: ["计算列在刷新时逐行计算，度量值在查询时响应筛选上下文", "上下文决定同一表达式为何产生不同结果"],
          applications: ["销售额", "利润率", "客户数"],
          pitfalls: ["把计算列当成动态指标", "忽略迭代函数的行上下文转换"],
          method: "先说明用户当前筛选，再推导度量值计算范围。",
          exercise: "实现销售额、订单数和客单价三个基础度量值。",
          checkpoint: "切换切片器时能解释每个指标为何变化。",
        },
        {
          key: "powerbi-calculate",
          title: "CALCULATE 与上下文转换",
          summary: "筛选器、关系、ALL、REMOVEFILTERS 和变量。",
          concepts: ["CALCULATE", "KEEPFILTERS", "ALL", "VAR"],
          principles: ["CALCULATE 修改筛选上下文后再计算表达式", "变量只计算一次并保留计算时上下文"],
          applications: ["占比", "目标对比", "排名"],
          pitfalls: ["不理解筛选覆盖导致重复计数", "变量中引用错误上下文"],
          method: "把每个筛选修改写出“原来是什么、改成什么、为什么”。",
          exercise: "实现各类产品销售额占全部销售额的比例。",
          checkpoint: "能逐步还原 CALCULATE 在某一行的筛选上下文。",
        },
        {
          key: "powerbi-time-intelligence",
          title: "时间智能与时间对比",
          summary: "同比、环比、累计、移动平均和财政年度。",
          concepts: ["DATEADD", "SAMEPERIODLASTYEAR", "YTD", "移动窗口"],
          principles: ["时间智能依赖标记日期表并自动处理完整日期范围", "同比与累计必须明确时间粒度和起点"],
          applications: ["月度趋势", "年度目标", "滚动 7 日指标"],
          pitfalls: ["日期表不准导致同比为空", "在无日期上下文中错误使用时间智能"],
          method: "先验证日期连续性和关系，再实现单指标基线。",
          exercise: "实现销售额同比、环比和 YTD。",
          checkpoint: "至少能用三个月数据手工核对结果。",
        },
      ],
      questionKeys: ["pbi-q7", "pbi-q8", "pbi-q9"],
    },
    {
      key: "powerbi-report",
      title: "报表、分析、安全与发布",
      weeks: "第 8-10 周",
      goal: "完成报表信息架构、分析交互、RLS、发布和刷新管理。",
      outcome: "交付一套可从移动端访问、按角色授权并持续刷新的 Power BI 报表。",
      topics: [
        {
          key: "powerbi-report-design",
          title: "报表设计与交互",
          summary: "视觉对象、书签、钻取、工具提示和可访问性。",
          concepts: ["信息层级", "书签", "钻取", "可访问性"],
          principles: ["报表应围绕决策路径组织，而不是平均摆放图表", "交互必须可预测、可返回、有明确焦点"],
          applications: ["销售驾驶舱", "运营分析", "管理汇报"],
          pitfalls: ["装饰过度导致重要指标不突出", "筛选器互相冲突"],
          method: "先画信息层级，再选择视觉对象和交互。",
          exercise: "制作包含总览、钻取和明细工具提示的两页报表。",
          checkpoint: "陌生用户能在 1 分钟内完成主要分析任务。",
        },
        {
          key: "powerbi-analytics",
          title: "分析功能与高级计算",
          summary: "分组、聚类、异常检测、AI 视觉对象和 What-if。",
          concepts: ["分析面板", "异常检测", "What-if 参数", "分组"],
          principles: ["自动分析结果必须回到业务解释", "What-if 参数用于探索假设，不直接代表预测"],
          applications: ["销售异常", "预算模拟", "客户分群"],
          pitfalls: ["把模型自动结论当成事实", "没有说明参数假设"],
          method: "先建立基线，再使用分析能力提出可验证问题。",
          exercise: "在销售报表中增加异常检测和价格调整模拟。",
          checkpoint: "分析结果能落到具体业务动作，而非只展示模型输出。",
        },
        {
          key: "powerbi-security-service",
          title: "RLS、发布与刷新",
          summary: "行级安全、工作区、网关、刷新、敏感标签和运维。",
          concepts: ["RLS", "角色与成员", "网关", "刷新计划", "数据保护"],
          principles: ["权限应在数据模型层和数据源层双重考虑", "发布后仍需监控刷新与使用情况"],
          applications: ["区域销售权限", "部门报表", "客户隔离"],
          pitfalls: ["默认给所有人工作区管理员", "只在上层报表做视觉筛选"],
          method: "先定义角色和数据范围，再进行最小权限测试。",
          exercise: "为区域销售报表实现 RLS 并测试两个角色。",
          checkpoint: "用户只能看到授权数据，发布和刷新流程可恢复。",
        },
      ],
      questionKeys: ["pbi-q10", "pbi-q11", "pbi-q12"],
    },
  ],
  questions: [
    {
    key: "pbi-q1",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-connect",
      type: "single",
      stem: "选择 Import 还是 DirectQuery 时，最应优先考虑什么？",
      options: [
        { key: "A", text: "图表颜色" },
        { key: "B", text: "数据新鲜度、性能和模型能力" },
        { key: "C", text: "报表页数" },
        { key: "D", text: "文件名称" },
      ],
      answer: ["B"],
      explanation: "连接模式直接影响刷新时效、查询性能、离线能力和支持的 DAX 功能，需共同权衡。",
      difficulty: "medium",
      tags: ["连接模式", "Power BI"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q2",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-power-query",
      type: "judge",
      stem: "Power Query 中的每一步转换都应该能被读懂、验证和回退。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "可读的 Applied Steps 能让数据准备过程可审计、可复现，并方便定位刷新错误。",
      difficulty: "easy",
      tags: ["Power Query", "数据准备"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q3",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-parameters",
      type: "single",
      stem: "同一套查询需要频繁切换环境路径，最适合使用什么？",
      options: [
        { key: "A", text: "硬编码路径" },
        { key: "B", text: "参数" },
        { key: "C", text: "更多视觉对象" },
        { key: "D", text: "复制报表" },
      ],
      answer: ["B"],
      explanation: "参数把环境差异集中到一个位置，调整一次即可影响所有引用它的查询。",
      difficulty: "easy",
      tags: ["参数", "Power Query"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q4",
    stageKey: "powerbi-model",
    topicKey: "powerbi-star-schema",
      type: "single",
      stem: "星型模型中，事实表最典型地记录什么？",
      options: [
        { key: "A", text: "业务事件及其度量" },
        { key: "B", text: "所有文本说明" },
        { key: "C", text: "页面布局" },
        { key: "D", text: "用户密码" },
      ],
      answer: ["A"],
      explanation: "事实表通常记录订单、销售、访问等业务事件，维度表提供分析上下文。",
      difficulty: "easy",
      tags: ["星型模型", "事实表"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q5",
    stageKey: "powerbi-model",
    topicKey: "powerbi-relationships",
      type: "judge",
      stem: "为了解决问题，可以默认把所有关系设置为双向筛选。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "双向筛选可能产生歧义路径、错误结果和性能问题，只能在明确需要且验证后使用。",
      difficulty: "medium",
      tags: ["关系", "筛选传播"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q6",
    stageKey: "powerbi-model",
    topicKey: "powerbi-date-table",
      type: "single",
      stem: "时间智能稳定工作的关键前提是什么？",
      options: [
        { key: "A", text: "使用连续且标记为日期表的日期表" },
        { key: "B", text: "日期列放在事实表即可" },
        { key: "C", text: "所有日期使用文本" },
        { key: "D", text: "关闭自动日期" },
      ],
      answer: ["A"],
      explanation: "连续并标记为日期表的维度能提供稳定日期范围和正确筛选，避免时间智能出现空白。",
      difficulty: "medium",
      tags: ["日期表", "时间智能"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q7",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-dax-basics",
      type: "single",
      stem: "计算列与度量值的关键区别是什么？",
      options: [
        { key: "A", text: "计算列刷新时计算，度量值查询时按上下文计算" },
        { key: "B", text: "计算列一定更快" },
        { key: "C", text: "度量值只能在卡片中使用" },
        { key: "D", text: "两者完全一样" },
      ],
      answer: ["A"],
      explanation: "计算列为每行存储结果；度量值根据用户当前筛选动态计算，更适合业务指标。",
      difficulty: "medium",
      tags: ["DAX", "度量值"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q8",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-calculate",
      type: "judge",
      stem: "CALCULATE 的本质之一是修改筛选上下文后再计算表达式。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "CALCULATE 通过筛选器参数修改上下文，因此能实现占比、目标对比和上下文移除。",
      difficulty: "medium",
      tags: ["CALCULATE", "筛选上下文"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q9",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-time-intelligence",
      type: "single",
      stem: "同比计算返回空值，最先检查什么？",
      options: [
        { key: "A", text: "日期表是否连续并与事实表正确关联" },
        { key: "B", text: "卡片圆角" },
        { key: "C", text: "主题颜色" },
        { key: "D", text: "页面数量" },
      ],
      answer: ["A"],
      explanation: "时间智能依赖完整连续日期和正确关系，日期缺失会直接导致同比上下文为空。",
      difficulty: "medium",
      tags: ["时间智能", "同比"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q10",
    stageKey: "powerbi-report",
    topicKey: "powerbi-report-design",
      type: "single",
      stem: "报表设计的第一步应是什么？",
      options: [
        { key: "A", text: "先确定要回答的业务问题和决策路径" },
        { key: "B", text: "先选尽量多的图表" },
        { key: "C", text: "先加动画" },
        { key: "D", text: "先把所有颜色都用上" },
      ],
      answer: ["A"],
      explanation: "报表服务于具体决策，明确问题和层级后才能选择指标、视觉对象和交互。",
      difficulty: "easy",
      tags: ["报表", "信息架构"],
      sourceKey: "pl300",
    },
    {
    key: "pbi-q11",
    stageKey: "powerbi-report",
    topicKey: "powerbi-analytics",
      type: "judge",
      stem: "自动化异常检测的输出应结合业务解释，不能直接当作最终事实。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "模型输出只是候选异常，仍需检查数据、业务事件和假设，才能形成可靠结论。",
      difficulty: "medium",
      tags: ["分析", "异常检测"],
      sourceKey: "powerbi-samples",
    },
    {
    key: "pbi-q12",
    stageKey: "powerbi-report",
    topicKey: "powerbi-security-service",
      type: "single",
      stem: "Power BI 中实现按区域限制数据访问，优先使用什么？",
      options: [
        { key: "A", text: "在报表页面上隐藏图表" },
        { key: "B", text: "行级安全 RLS" },
        { key: "C", text: "改文件名" },
        { key: "D", text: "复制整个工作区" },
      ],
      answer: ["B"],
      explanation: "RLS 在语义模型层限制用户可见数据，并能在服务中统一管理和测试。",
      difficulty: "medium",
      tags: ["RLS", "安全"],
      sourceKey: "pl300",
    },
  ],
};
