import type { LearningTrack } from "./types";

export const pythonTrack: LearningTrack = {
  slug: "python",
  title: "Python",
  category: "编程语言",
  level: "入门",
  accent: "#2F74C0",
  softAccent: "#E8F3FD",
  icon: "logo-python",
  summary: "从语法、数据结构到工程化与数据分析，建立可独立完成项目的能力。",
  whyLearn: "Python 语法清晰、生态成熟，是自动化、数据分析、后端服务和 AI 应用的基础语言。",
  prerequisites: ["会使用文件与终端", "理解基本的变量和函数概念"],
  studyMethod: ["先运行示例，再修改参数观察差异", "每个主题至少完成一个独立练习", "用项目验收代替只看教程"],
  estimatedHours: 96,
  featured: true,
  sources: [
    {
      key: "exercism-python",
      name: "Exercism Python",
      url: "https://github.com/exercism/python",
      license: "MIT",
      usage: "import",
      note: "练习结构、测试驱动与概念学习方式",
    },
    {
      key: "algorithms-python",
      name: "TheAlgorithms/Python",
      url: "https://github.com/TheAlgorithms/Python",
      license: "MIT",
      usage: "import",
      note: "算法、数据结构与代码示例",
    },
    {
      key: "ms-data-science",
      name: "Microsoft Data Science for Beginners",
      url: "https://github.com/microsoft/Data-Science-For-Beginners",
      license: "MIT",
      usage: "import",
      note: "Pandas、数据清洗、可视化与项目结构",
    },
  ],
  stages: [
    {
      key: "python-foundation",
      title: "语言基础与程序思维",
      weeks: "第 1-2 周",
      goal: "掌握变量、分支、循环、函数和调试的基本方法。",
      outcome: "独立写出 100 行左右的命令行程序，并能定位常见语法和逻辑错误。",
      topics: [
        {
          key: "python-values-control",
          title: "值与控制流",
          summary: "变量、基本类型、条件判断、循环与输入输出。",
          concepts: ["整数、浮点数、字符串、布尔值", "if/elif/else 分支", "for 与 while 循环"],
          principles: ["Python 是动态类型语言，运行时根据对象决定可用操作", "分支负责选择路径，循环负责重复执行"],
          applications: ["成绩判断", "菜单选择", "批量处理字符串"],
          pitfalls: ["把赋值与相等判断混淆", "循环边界写错导致少一次或多一次"],
          method: "先用伪代码写清判断和循环，再逐行转成 Python。",
          exercise: "实现一个猜数字程序，支持次数提示与重新开始。",
          checkpoint: "能解释一段带嵌套循环的代码为什么产生当前输出。",
        },
        {
          key: "python-functions",
          title: "函数与模块",
          summary: "参数、返回值、作用域、导入与标准库。",
          concepts: ["位置参数与关键字参数", "返回值与 None", "模块、包与导入"],
          principles: ["函数把输入、处理和输出封装为稳定接口", "模块让代码按职责拆分并可复用"],
          applications: ["数据校验函数", "命令行工具", "工具模块复用"],
          pitfalls: ["函数修改外部变量造成隐藏依赖", "返回值与打印混为一谈"],
          method: "每个函数只承担一个明确任务，用返回值和测试验证行为。",
          exercise: "拆分一个单文件脚本为三个模块并补充输入校验。",
          checkpoint: "能用一句话说明每个函数的输入、输出和失败条件。",
        },
        {
          key: "python-debug",
          title: "错误与调试",
          summary: "异常、traceback、断言和日志。",
          concepts: ["异常类型与 traceback", "try/except/finally", "assert 与 logging"],
          principles: ["异常用于表达无法继续的正常控制流", "traceback 应从最后一行向上定位调用来源"],
          applications: ["读取不存在的文件", "网络请求失败", "记录程序关键步骤"],
          pitfalls: ["捕获所有异常后静默忽略", "用异常处理掩盖真正的逻辑错误"],
          method: "先复现问题，再看 traceback，最后写最小修复和回归测试。",
          exercise: "为一个文件读取程序补齐异常处理和日志。",
          checkpoint: "遇到异常时能指出错误类型、触发位置和修复依据。",
        },
      ],
      questionKeys: ["py-q1", "py-q2", "py-q3"],
    },
    {
      key: "python-data-structures",
      title: "数据结构与工程基础",
      weeks: "第 3-5 周",
      goal: "熟练使用容器、文件、虚拟环境和测试组织程序。",
      outcome: "完成一个可安装、可测试、能从文件读写数据的 Python 小项目。",
      topics: [
        {
          key: "python-collections",
          title: "列表、字典与集合",
          summary: "容器的选择、遍历、推导式与复杂度直觉。",
          concepts: ["list、tuple、dict、set", "推导式", "时间复杂度"],
          principles: ["不同容器以查找、顺序和去重能力做权衡", "哈希结构通常提供接近常数时间的查找"],
          applications: ["统计数据", "建立索引", "去重与集合运算"],
          pitfalls: ["遍历列表时直接删除元素", "把可变对象作为字典键"],
          method: "先写清数据形状，再选择容器，最后评估查找和更新次数。",
          exercise: "用字典和集合统计日志中的独立用户与高频操作。",
          checkpoint: "能根据访问模式说明为什么选择 list、dict 或 set。",
        },
        {
          key: "python-files",
          title: "文件、JSON 与环境",
          summary: "路径、文本编码、JSON、虚拟环境和依赖。",
          concepts: ["with 上下文管理器", "UTF-8 与路径", "venv 与 requirements"],
          principles: ["上下文管理器保证资源及时释放", "虚拟环境隔离项目依赖"],
          applications: ["配置读取", "数据导入导出", "项目依赖复现"],
          pitfalls: ["依赖当前工作目录拼接路径", "忽略编码导致中文乱码"],
          method: "统一使用 pathlib 处理路径，读写 JSON 后用结构校验。",
          exercise: "制作一个可读写配置文件的命令行待办工具。",
          checkpoint: "换一台机器后能按 README 重建并运行项目。",
        },
        {
          key: "python-testing",
          title: "测试与代码质量",
          summary: "pytest、边界条件、重构与格式化。",
          concepts: ["单元测试", "测试夹具", "边界与异常测试"],
          principles: ["测试固定行为契约，重构不应改变契约", "覆盖正常、边界和失败三类路径"],
          applications: ["工具函数", "数据转换", "接口响应解析"],
          pitfalls: ["只测试正常输入", "测试依赖执行顺序"],
          method: "先写一个失败测试，再实现最小代码，最后重构并保持测试通过。",
          exercise: "为解析器补齐正常、空输入和非法格式测试。",
          checkpoint: "能说明每个测试保护了哪一条具体行为。",
        },
      ],
      questionKeys: ["py-q4", "py-q5", "py-q6"],
    },
    {
      key: "python-oop-typing",
      title: "面向对象与类型系统",
      weeks: "第 6-8 周",
      goal: "掌握类、数据模型、类型标注和可维护的接口设计。",
      outcome: "设计一个小型领域模型，并让类型检查和测试共同守住边界。",
      topics: [
        {
          key: "python-classes",
          title: "类与对象模型",
          summary: "类、实例、继承、组合、魔术方法。",
          concepts: ["实例属性与类属性", "继承与组合", "repr、eq、dataclass"],
          principles: ["对象把状态和行为绑定在同一职责边界", "优先组合可减少继承层级耦合"],
          applications: ["订单与商品模型", "任务状态机", "插件接口"],
          pitfalls: ["为了复用随意建立继承关系", "在多个位置修改共享可变类属性"],
          method: "先画状态和职责，再决定类之间的组合与依赖方向。",
          exercise: "实现任务、标签和任务列表三个对象并补测试。",
          checkpoint: "能解释对象间依赖为何这样组织，而非只描述字段。",
        },
        {
          key: "python-typing",
          title: "类型标注与协议",
          summary: "基础标注、泛型、Protocol 与静态检查。",
          concepts: ["list[str] 等泛型", "Optional 与 Union", "Protocol 结构化接口"],
          principles: ["类型标注描述接口契约，不替代运行时校验", "Protocol 以行为而非继承建立可替换性"],
          applications: ["服务接口", "仓库抽象", "第三方数据解析"],
          pitfalls: ["用 Any 绕过所有问题", "标注与真实返回不一致"],
          method: "从公共函数边界开始标注，再逐步向内部传播。",
          exercise: "为数据仓库接口写 Protocol，并实现内存与文件两种版本。",
          checkpoint: "类型检查通过，且替换实现时调用方无需修改。",
        },
        {
          key: "python-context",
          title: "迭代、生成器与上下文",
          summary: "迭代协议、生成器、上下文管理器和装饰器。",
          concepts: ["iter/next", "yield", "contextmanager", "装饰器"],
          principles: ["生成器按需产出数据，降低内存峰值", "上下文管理器把进入和清理逻辑配对"],
          applications: ["流式读取大文件", "数据库事务", "计时与重试"],
          pitfalls: ["过早优化成复杂生成器", "装饰器丢失原函数元信息"],
          method: "先判断是否真的需要惰性处理，再用最小抽象实现。",
          exercise: "实现流式日志读取器和事务上下文管理器。",
          checkpoint: "能说明抽象解决了哪种重复或资源问题。",
        },
      ],
      questionKeys: ["py-q7", "py-q8", "py-q9"],
    },
    {
      key: "python-data-project",
      title: "数据分析与综合项目",
      weeks: "第 9-12 周",
      goal: "使用 Pandas 完成数据清洗、探索、可视化与结果交付。",
      outcome: "交付一份结构清晰的数据分析报告和一个可复现项目。",
      topics: [
        {
          key: "python-pandas",
          title: "Pandas 数据处理",
          summary: "Series、DataFrame、缺失值、合并与分组。",
          concepts: ["索引与列选择", "缺失值处理", "merge、groupby、pivot"],
          principles: ["先确认数据粒度，再进行聚合和连接", "每个转换步骤都应可验证"],
          applications: ["销售分析", "用户留存", "运营周报"],
          pitfalls: ["未检查连接键导致行数膨胀", "直接删除缺失值造成样本偏差"],
          method: "每一步输出 shape、样例和关键指标，避免黑箱式链式调用。",
          exercise: "清洗一份含缺失和重复的订单数据并输出日销售额。",
          checkpoint: "能解释清洗前后每项指标变化的原因。",
        },
        {
          key: "python-visualization",
          title: "探索与可视化",
          summary: "描述统计、分布、趋势和图表表达。",
          concepts: ["均值、中位数、分位数", "分布与异常值", "趋势和对比图"],
          principles: ["图表首先回答具体问题，再决定图形", "坐标轴和基准线会显著影响结论"],
          applications: ["异常检测", "趋势报告", "多维对比"],
          pitfalls: ["截断纵轴放大差异", "用平均值掩盖双峰分布"],
          method: "先写问题，再选指标和图型，最后用文字给出结论与限制。",
          exercise: "针对一份销售数据完成四个业务问题并各配一张图。",
          checkpoint: "每张图都能回答一个问题，并说明不能回答什么。",
        },
        {
          key: "python-capstone",
          title: "综合项目与交付",
          summary: "需求拆解、模块设计、测试、文档和复盘。",
          concepts: ["需求与验收", "项目结构", "README 与复盘"],
          principles: ["先定义可演示结果，再控制实现范围", "可复现性属于交付质量的一部分"],
          applications: ["自动化报告", "数据工具", "小型 API"],
          pitfalls: ["功能越做越多但没有验收", "没有记录数据来源和版本"],
          method: "按最小可演示版本推进，每周交付一次可运行增量。",
          exercise: "完成数据分析工具：读取、清洗、统计、导出、测试、文档。",
          checkpoint: "项目可在新环境一键运行，且结果能追溯到原始数据。",
        },
      ],
      questionKeys: ["py-q10", "py-q11", "py-q12"],
    },
  ],
  questions: [
    {
    key: "py-q1",
    stageKey: "python-foundation",
    topicKey: "python-values-control",
      type: "single",
      stem: "下面哪一项最适合表示“是否完成任务”的状态？",
      options: [
        { key: "A", text: "字符串 \"true\"" },
        { key: "B", text: "布尔值 True" },
        { key: "C", text: "浮点数 1.0" },
        { key: "D", text: "列表 [1]" },
      ],
      answer: ["B"],
      explanation: "布尔值直接表达真假两种状态，语义最清晰，也最适合用于条件判断。",
      difficulty: "easy",
      tags: ["变量", "数据类型"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q2",
    stageKey: "python-foundation",
    topicKey: "python-functions",
      type: "judge",
      stem: "函数没有显式 return 时，调用结果默认是 None。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "Python 函数执行到末尾没有 return 时会隐式返回 None。",
      difficulty: "easy",
      tags: ["函数", "返回值"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q3",
    stageKey: "python-foundation",
    topicKey: "python-debug",
      type: "single",
      stem: "遇到 traceback 时，最有效的第一步是什么？",
      options: [
        { key: "A", text: "随机修改代码直到不报错" },
        { key: "B", text: "从最后一行向上定位触发位置" },
        { key: "C", text: "删除所有异常处理" },
        { key: "D", text: "直接改成捕获所有异常" },
      ],
      answer: ["B"],
      explanation: "traceback 的最后一行通常包含异常类型和直接触发点，向上可以追到调用链。",
      difficulty: "easy",
      tags: ["异常", "调试"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q4",
    stageKey: "python-data-structures",
    topicKey: "python-collections",
      type: "single",
      stem: "需要频繁按用户 ID 查找记录时，首选哪种结构？",
      options: [
        { key: "A", text: "list" },
        { key: "B", text: "dict" },
        { key: "C", text: "tuple" },
        { key: "D", text: "字符串" },
      ],
      answer: ["B"],
      explanation: "dict 以键进行哈希查找，适合按唯一 ID 建立索引。",
      difficulty: "easy",
      tags: ["字典", "复杂度"],
      sourceKey: "algorithms-python",
    },
    {
    key: "py-q5",
    stageKey: "python-data-structures",
    topicKey: "python-collections",
      type: "judge",
      stem: "遍历列表时直接删除元素一定会安全保持所有元素的遍历顺序。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "删除会改变列表长度和后续索引，常见结果是漏掉元素。应构建新列表或倒序处理。",
      difficulty: "medium",
      tags: ["列表", "遍历"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q6",
    stageKey: "python-data-structures",
    topicKey: "python-files",
      type: "single",
      stem: "虚拟环境最重要的作用是什么？",
      options: [
        { key: "A", text: "自动提升运行速度" },
        { key: "B", text: "隔离当前项目的依赖版本" },
        { key: "C", text: "替代所有测试" },
        { key: "D", text: "把 Python 代码编译为 Java" },
      ],
      answer: ["B"],
      explanation: "虚拟环境让不同项目使用各自的依赖版本，减少全局环境污染和版本冲突。",
      difficulty: "easy",
      tags: ["venv", "依赖"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q7",
    stageKey: "python-oop-typing",
    topicKey: "python-classes",
      type: "single",
      stem: "以下哪种做法通常更利于降低耦合？",
      options: [
        { key: "A", text: "加深继承层级" },
        { key: "B", text: "优先使用组合" },
        { key: "C", text: "让所有对象共享全局变量" },
        { key: "D", text: "把多个职责塞进一个类" },
      ],
      answer: ["B"],
      explanation: "组合通过明确的对象依赖表达职责，通常比多层继承更灵活、更容易测试。",
      difficulty: "medium",
      tags: ["面向对象", "组合"],
      sourceKey: "algorithms-python",
    },
    {
    key: "py-q8",
    stageKey: "python-oop-typing",
    topicKey: "python-typing",
      type: "judge",
      stem: "静态类型标注可以完全替代运行时数据校验。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["B"],
      explanation: "类型标注帮助静态检查，但外部输入仍可能在运行时不符合预期，关键边界仍需校验。",
      difficulty: "medium",
      tags: ["类型标注", "接口"],
      sourceKey: "exercism-python",
    },
    {
    key: "py-q9",
    stageKey: "python-oop-typing",
    topicKey: "python-context",
      type: "single",
      stem: "生成器最适合下面哪种场景？",
      options: [
        { key: "A", text: "按需流式处理大文件" },
        { key: "B", text: "同时运行多个 CPU 密集任务" },
        { key: "C", text: "保证所有数据只读" },
        { key: "D", text: "替代数据库事务" },
      ],
      answer: ["A"],
      explanation: "生成器一次只产生一个值，适合大文件或流式数据的惰性处理。",
      difficulty: "medium",
      tags: ["生成器", "迭代"],
      sourceKey: "algorithms-python",
    },
    {
    key: "py-q10",
    stageKey: "python-data-project",
    topicKey: "python-pandas",
      type: "single",
      stem: "合并两个表后行数突然暴涨，最可能的原因是什么？",
      options: [
        { key: "A", text: "连接键存在重复值" },
        { key: "B", text: "索引不是整数" },
        { key: "C", text: "列名太长" },
        { key: "D", text: "使用了 groupby" },
      ],
      answer: ["A"],
      explanation: "连接键重复会产生多对多组合，导致行数膨胀。连接前应检查键的唯一性。",
      difficulty: "medium",
      tags: ["Pandas", "merge"],
      sourceKey: "ms-data-science",
    },
    {
    key: "py-q11",
    stageKey: "python-data-project",
    topicKey: "python-visualization",
      type: "judge",
      stem: "分析图表的纵轴从非零值开始时，仍可能误导读者高估差异。",
      options: [
        { key: "A", text: "正确" },
        { key: "B", text: "错误" },
      ],
      answer: ["A"],
      explanation: "截断纵轴会放大视觉差异，除非明确说明并提供完整尺度，否则容易造成误读。",
      difficulty: "medium",
      tags: ["可视化", "图表"],
      sourceKey: "ms-data-science",
    },
    {
    key: "py-q12",
    stageKey: "python-data-project",
    topicKey: "python-capstone",
      type: "single",
      stem: "数据项目要保证可复现，最少需要记录什么？",
      options: [
        { key: "A", text: "数据来源、处理步骤和依赖版本" },
        { key: "B", text: "只记录最终图表" },
        { key: "C", text: "只记录 Python 版本" },
        { key: "D", text: "只记录电脑型号" },
      ],
      answer: ["A"],
      explanation: "数据来源、转换步骤和依赖版本共同决定结果能否被重新生成。",
      difficulty: "easy",
      tags: ["项目", "复现"],
      sourceKey: "ms-data-science",
    },
  ],
};
