import { judgeQuestion, singleQuestion } from "./question-builders";
import { stageLessons, topicLessons } from "./lessons";
import { topicQuestionPacks } from "./topic-question-packs";
import type { LearningQuestion, LearningTrack } from "./types";

const pythonExpansion: LearningQuestion[] = [
  singleQuestion({
    key: "py-q13",
    stageKey: "python-foundation",
    topicKey: "python-values-control",
    stem: "Python 中变量赋值最准确的理解是什么？",
    options: ["把值复制到固定盒子", "让名称绑定到一个对象", "每次创建新类型", "编译时决定全部类型"],
    answer: "B",
    explanation: "Python 名称绑定对象，多个名称可以指向同一个可变对象。",
    difficulty: "easy",
    tags: ["变量", "对象"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q14",
    stageKey: "python-foundation",
    topicKey: "python-functions",
    stem: "函数默认参数使用可变对象时的主要风险是什么？",
    options: ["函数无法调用", "多次调用共享同一个可变对象", "参数自动复制", "返回值变为字符串"],
    answer: "B",
    explanation: "默认值在函数定义时创建一次，可变默认值会在多次调用间保留修改。",
    difficulty: "medium",
    tags: ["函数", "默认参数"],
    sourceKey: "algorithms-python",
  }),
  judgeQuestion({
    key: "py-q15",
    stageKey: "python-foundation",
    topicKey: "python-debug",
    stem: "try/except 捕获异常后，至少应保留可诊断的错误上下文。",
    answer: true,
    explanation: "静默吞掉异常会隐藏根因；至少应记录异常类型、消息和必要的调用上下文。",
    difficulty: "easy",
    tags: ["异常", "调试"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q16",
    stageKey: "python-foundation",
    topicKey: "python-debug",
    stem: "定位复杂 traceback 时，第一原则是什么？",
    options: ["只看最后一行", "从触发点沿调用链找到真正源头", "删除报错代码", "关闭日志"],
    answer: "B",
    explanation: "最后一行显示异常类型，真正根因可能位于更早的业务调用或数据边界的。",
    difficulty: "medium",
    tags: ["traceback", "调试"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q17",
    stageKey: "python-data-structures",
    topicKey: "python-collections",
    stem: "需要频繁按唯一键查找值，通常优先选择什么结构？",
    options: ["list", "dict", "tuple", "set"],
    answer: "B",
    explanation: "dict 以哈希表提供按键快速查找，适合建立索引和映射。",
    difficulty: "easy",
    tags: ["dict", "查找"],
    sourceKey: "algorithms-python",
  }),
  singleQuestion({
    key: "py-q18",
    stageKey: "python-data-structures",
    topicKey: "python-files",
    stem: "读写文件时使用 with 的主要价值是什么？",
    options: ["自动增加编码", "确保资源在作用域结束时释放", "让文件更小", "自动修复内容"],
    answer: "B",
    explanation: "上下文管理器保证正常或异常路径都能关闭文件、网络连接等资源。",
    difficulty: "easy",
    tags: ["with", "资源"],
    sourceKey: "exercism-python",
  }),
  judgeQuestion({
    key: "py-q19",
    stageKey: "python-data-structures",
    topicKey: "python-testing",
    stem: "pytest 只需要覆盖成功路径，异常和边界输入可以省略。",
    answer: false,
    explanation: "边界、空输入和失败路径通常最容易出现回归，是测试契约的重要部分。",
    difficulty: "easy",
    tags: ["pytest", "边界"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q20",
    stageKey: "python-data-structures",
    topicKey: "python-files",
    stem: "项目依赖应通过什么方式保证可复现？",
    options: ["口头说明", "锁定版本并记录在项目依赖文件中", "依赖全局环境", "每次重装不同版本"],
    answer: "B",
    explanation: "明确锁定和记录依赖能让本地、CI 与部署环境得到可重复的安装结果。",
    difficulty: "easy",
    tags: ["venv", "依赖"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "py-q21",
    stageKey: "python-oop-typing",
    topicKey: "python-classes",
    stem: "类之间优先使用组合而非继承，通常是为了什么？",
    options: ["增加层级", "降低耦合并让职责边界更清晰", "隐藏所有方法", "减少对象数量"],
    answer: "B",
    explanation: "组合通过明确对象协作降低继承层级带来的强耦合和脆弱基类问题。",
    difficulty: "medium",
    tags: ["组合", "OOP"],
    sourceKey: "algorithms-python",
  }),
  judgeQuestion({
    key: "py-q22",
    stageKey: "python-oop-typing",
    topicKey: "python-typing",
    stem: "Python 类型标注会在运行时自动阻止所有错误类型调用。",
    answer: false,
    explanation: "类型标注主要由静态检查器使用，运行时通常不会自动强制类型。",
    difficulty: "medium",
    tags: ["类型标注", "运行时"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q23",
    stageKey: "python-oop-typing",
    topicKey: "python-context",
    stem: "生成器相比一次返回完整列表，最直接的优势是什么？",
    options: ["一定更快", "按需产出并降低峰值内存", "自动并行", "避免异常"],
    answer: "B",
    explanation: "生成器惰性产出，适合流式处理或数据量较大的场景。",
    difficulty: "medium",
    tags: ["生成器", "内存"],
    sourceKey: "algorithms-python",
  }),
  singleQuestion({
    key: "py-q24",
    stageKey: "python-oop-typing",
    topicKey: "python-context",
    stem: "上下文管理器最适合封装哪类逻辑？",
    options: ["纯字符串拼接", "成对出现的建立与清理操作", "颜色计算", "静态常量"],
    answer: "B",
    explanation: "进入时获取资源，退出时释放，上下文管理器适合锁、事务、文件和连接。",
    difficulty: "easy",
    tags: ["上下文管理器", "资源"],
    sourceKey: "exercism-python",
  }),
  singleQuestion({
    key: "py-q25",
    stageKey: "python-data-project",
    topicKey: "python-pandas",
    stem: "Pandas 中合并后行数异常增加，首先检查什么？",
    options: ["连接键是否重复", "列名颜色", "图表尺寸", "Python 版本"],
    answer: "A",
    explanation: "连接键重复会形成多对多匹配，导致行数和求和指标膨胀。",
    difficulty: "medium",
    tags: ["Pandas", "merge"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "py-q26",
    stageKey: "python-data-project",
    topicKey: "python-pandas",
    stem: "分析过程中删除缺失值前，应比较删除前后的样本结构。",
    answer: true,
    explanation: "缺失可能集中在特定组群，直接删除会引入样本偏差和错误结论。",
    difficulty: "medium",
    tags: ["缺失值", "偏差"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "py-q27",
    stageKey: "python-data-project",
    topicKey: "python-visualization",
    stem: "选择可视化图型前，最先要明确什么？",
    options: ["图要回答的问题", "颜色数量", "图表动画", "字体大小"],
    answer: "A",
    explanation: "问题决定比较、趋势、分布或关系，再据此选择合适视觉编码。",
    difficulty: "easy",
    tags: ["可视化", "问题"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "py-q28",
    stageKey: "python-data-project",
    topicKey: "python-capstone",
    stem: "数据分析项目可复现交付至少应记录什么？",
    options: ["随机截图", "数据版本、处理步骤和运行方式", "只写结论", "文件颜色"],
    answer: "B",
    explanation: "数据来源、处理逻辑、依赖和运行命令共同决定结果能否被重现。",
    difficulty: "medium",
    tags: ["复现", "交付"],
    sourceKey: "ms-data-science",
  }),
];

const javaExpansion: LearningQuestion[] = [
  singleQuestion({
    key: "java-q13",
    stageKey: "java-foundation",
    topicKey: "java-oop",
    stem: "比较两个对象内容是否相等，通常应调用什么？",
    options: ["==", "equals", "hashCode", "toString"],
    answer: "B",
    explanation: "== 比较引用身份，类正确实现 equals 后才能表达内容相等。",
    difficulty: "easy",
    tags: ["equals", "对象"],
    sourceKey: "algorithms-java",
  }),
  judgeQuestion({
    key: "java-q14",
    stageKey: "java-foundation",
    topicKey: "java-oop",
    stem: "接口适合定义能力契约，抽象类更适合共享部分实现和状态。",
    answer: true,
    explanation: "接口强调可替换能力，抽象类可提供基础实现，但设计时仍应避免过深继承。",
    difficulty: "medium",
    tags: ["接口", "抽象类"],
    sourceKey: "java-patterns",
  }),
  singleQuestion({
    key: "java-q15",
    stageKey: "java-foundation",
    topicKey: "java-exceptions",
    stem: "受检异常通常要求调用方做什么？",
    options: ["忽略", "在编译期处理或声明抛出", "自动转成断言", "变成警告"],
    answer: "B",
    explanation: "受检异常要求调用方显式捕获或继续声明，从而把恢复责任放进类型契约。",
    difficulty: "medium",
    tags: ["异常", "编译期"],
    sourceKey: "algorithms-java",
  }),
  judgeQuestion({
    key: "java-q16",
    stageKey: "java-foundation",
    topicKey: "java-exceptions",
    stem: "捕获异常后记录日志并原样继续执行，通常比保留并向上抛出更安全。",
    answer: false,
    explanation: "如果当前层无法恢复，静默继续会让错误扩散；应保留上下文并交给能处理的层。",
    difficulty: "medium",
    tags: ["异常", "恢复"],
    sourceKey: "java-patterns",
  }),
  singleQuestion({
    key: "java-q17",
    stageKey: "java-collections",
    topicKey: "java-collections",
    stem: "需要频繁在两端插入删除，通常优先考虑什么集合？",
    options: ["ArrayList", "LinkedList", "HashSet", "TreeMap"],
    answer: "B",
    explanation: "LinkedList 的双向链式结构适合频繁两端操作，但随机访问成本较高。",
    difficulty: "medium",
    tags: ["集合", "LinkedList"],
    sourceKey: "algorithms-java",
  }),
  judgeQuestion({
    key: "java-q18",
    stageKey: "java-collections",
    topicKey: "java-generics",
    stem: "Java 泛型信息通常会经历类型擦除，不能把所有泛型参数当运行时类型使用。",
    answer: true,
    explanation: "类型擦除会让部分泛型信息在运行时不可直接获取，应通过类型 token 或边界设计补偿。",
    difficulty: "hard",
    tags: ["泛型", "类型擦除"],
    sourceKey: "algorithms-java",
  }),
  singleQuestion({
    key: "java-q19",
    stageKey: "java-collections",
    topicKey: "java-stream",
    stem: "同一个 Stream 被终止操作消费后再次使用会遇到什么问题？",
    options: ["自动重置", "抛出 IllegalStateException", "变成并行流", "自动缓存"],
    answer: "B",
    explanation: "Stream 是一次性管道，已被消费后不能重复使用，应为每次计算创建新流。",
    difficulty: "medium",
    tags: ["Stream", "生命周期"],
    sourceKey: "algorithms-java",
  }),
  singleQuestion({
    key: "java-q20",
    stageKey: "java-collections",
    topicKey: "java-stream",
    stem: "使用 Stream 时，最重要的工程判断之一是什么？",
    options: ["是否让代码更短", "是否产生副作用以及数据规模是否合适", "是否使用更多方法", "是否增加字符串"],
    answer: "B",
    explanation: "流式表达不适合隐藏复杂副作用；大数据和高频路径还要评估装箱和内存成本。",
    difficulty: "medium",
    tags: ["Stream", "工程"],
    sourceKey: "tech-interview-handbook",
  }),
  singleQuestion({
    key: "java-q21",
    stageKey: "java-concurrency",
    topicKey: "java-threads",
    stem: "volatile 主要能保证什么？",
    options: ["原子复合操作", "变量可见性和一定有序性", "自动加锁", "线程池扩容"],
    answer: "B",
    explanation: "volatile 保证写入对其他线程可见并限制部分重排，但不能自动让复合操作原子化。",
    difficulty: "hard",
    tags: ["并发", "volatile"],
    sourceKey: "advanced-java-reference",
  }),
  judgeQuestion({
    key: "java-q22",
    stageKey: "java-concurrency",
    topicKey: "java-threads",
    stem: "线程池使用后应明确关闭策略，避免进程无法退出或任务持续积压。",
    answer: true,
    explanation: "ExecutorService 的生命周期应受应用管理，结合拒绝策略、超时和优雅关闭。",
    difficulty: "medium",
    tags: ["线程池", "生命周期"],
    sourceKey: "tech-interview-handbook",
  }),
  singleQuestion({
    key: "java-q23",
    stageKey: "java-concurrency",
    topicKey: "java-jvm",
    stem: "定位疑似内存泄漏时，哪种证据最直接？",
    options: ["堆转储中持续增长且不可回收的对象链", "代码行数", "接口名称", "日志颜色"],
    answer: "A",
    explanation: "堆转储和支配树可显示对象为何仍被 GC Roots 可达，从而定位持有链。",
    difficulty: "hard",
    tags: ["JVM", "堆转储"],
    sourceKey: "advanced-java-reference",
  }),
  singleQuestion({
    key: "java-q24",
    stageKey: "java-concurrency",
    topicKey: "java-performance",
    stem: "性能优化为什么要使用同一套基准复测？",
    options: ["为了增加变量", "为了比较同一条件下的前后差异", "为了让结果更好看", "为了跳过测试"],
    answer: "B",
    explanation: "相同输入、环境和指标才能让优化收益可归因，并发现是否只是测量噪声。",
    difficulty: "easy",
    tags: ["性能", "基准"],
    sourceKey: "tech-interview-handbook",
  }),
  singleQuestion({
    key: "java-q25",
    stageKey: "java-engineering",
    topicKey: "java-build",
    stem: "处理依赖冲突时，最可靠的第一步是什么？",
    options: ["盲目排除所有版本", "查看依赖树并确认冲突来源", "删除测试", "升级全部依赖"],
    answer: "B",
    explanation: "依赖树能定位传递依赖和版本优先级，再选择统一版本或明确排除。",
    difficulty: "medium",
    tags: ["Maven", "依赖冲突"],
    sourceKey: "tech-interview-handbook",
  }),
  singleQuestion({
    key: "java-q26",
    stageKey: "java-engineering",
    topicKey: "java-patterns",
    stem: "策略模式最适合隔离什么变化？",
    options: ["可变算法或规则", "字体大小", "CPU 核数", "日志时间"],
    answer: "A",
    explanation: "策略模式把可替换算法封装为独立实现，让调用方依赖统一契约。",
    difficulty: "easy",
    tags: ["设计模式", "策略"],
    sourceKey: "java-patterns",
  }),
  judgeQuestion({
    key: "java-q27",
    stageKey: "java-engineering",
    topicKey: "java-patterns",
    stem: "事务边界应尽量围绕一个需要保持一致性的业务不变量。",
    answer: true,
    explanation: "围绕业务不变量设计事务能减少锁范围，避免跨网络和长时间事务。",
    difficulty: "medium",
    tags: ["事务", "服务设计"],
    sourceKey: "java-patterns",
  }),
  singleQuestion({
    key: "java-q28",
    stageKey: "java-engineering",
    topicKey: "java-service",
    stem: "服务层返回错误模型的主要目标是什么？",
    options: ["隐藏所有错误", "让调用方稳定区分错误类型和恢复方式", "增加状态码数量", "替换日志"],
    answer: "B",
    explanation: "稳定错误模型有助于接口适配、重试判断、用户提示和可观测性。",
    difficulty: "medium",
    tags: ["错误模型", "API"],
    sourceKey: "tech-interview-handbook",
  }),
];

const dataAnalysisExpansion: LearningQuestion[] = [
  singleQuestion({
    key: "data-q13",
    stageKey: "data-relational",
    topicKey: "data-relational-model",
    stem: "表的主键最核心的性质是什么？",
    options: ["必须为数字", "唯一标识一行且不能为空", "只能包含一列", "必须自动增长"],
    answer: "B",
    explanation: "主键用于唯一标识记录，通常要求唯一且非空；可以是一列或多列组合。",
    difficulty: "easy",
    tags: ["主键", "关系模型"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q14",
    stageKey: "data-relational",
    topicKey: "data-joins",
    stem: "聚合后筛选分组结果应使用哪个子句？",
    options: ["WHERE", "HAVING", "ORDER BY", "LIMIT"],
    answer: "B",
    explanation: "WHERE 在分组前过滤行，HAVING 在分组和聚合后过滤结果组。",
    difficulty: "medium",
    tags: ["HAVING", "GROUP BY"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "data-q15",
    stageKey: "data-relational",
    topicKey: "data-joins",
    stem: "LEFT JOIN 中保留左表全部行，即使右表没有匹配记录。",
    answer: true,
    explanation: "LEFT JOIN 保留左表每一行，右表无匹配时相关列为 NULL。",
    difficulty: "easy",
    tags: ["JOIN", "LEFT JOIN"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "data-q16",
    stageKey: "data-relational",
    topicKey: "data-joins",
    stem: "只要列名相同，两个表就可以安全地直接连接。",
    answer: false,
    explanation: "连接键必须表达相同业务身份和粒度，仅列名相同不足以保证关系正确。",
    difficulty: "easy",
    tags: ["连接键", "粒度"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q17",
    stageKey: "data-analysis-sql",
    topicKey: "data-window",
    stem: "ROW_NUMBER 与 RANK 在并列值上的关键区别是什么？",
    options: ["ROW_NUMBER 并列后产生相同序号", "RANK 并列后可能跳号", "两者完全相同", "RANK 不能排序"],
    answer: "B",
    explanation: "ROW_NUMBER 始终产生连续唯一序号；RANK 给并列值相同排名并跳过后续序号。",
    difficulty: "medium",
    tags: ["窗口函数", "排名"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q18",
    stageKey: "data-analysis-sql",
    topicKey: "data-window",
    stem: "窗口函数 LAG 主要用于什么？",
    options: ["读取同一分区中的前一行", "删除一行", "创建表", "修改排序"],
    answer: "A",
    explanation: "LAG 按窗口顺序读取前一行值，常用于环比、时间差和状态变化。",
    difficulty: "medium",
    tags: ["LAG", "窗口函数"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "data-q19",
    stageKey: "data-analysis-sql",
    topicKey: "data-cte",
    stem: "CTE 中的每一步都应尽量保持明确的输入输出粒度。",
    answer: true,
    explanation: "稳定的中间粒度让每步可验证、可复用，也更容易发现行数膨胀问题。",
    difficulty: "medium",
    tags: ["CTE", "粒度"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q20",
    stageKey: "data-analysis-sql",
    topicKey: "data-funnel-retention",
    stem: "留存分析的分子通常是什么？",
    options: ["所有用户数", "初始同期群中在指定后续时间活跃的用户数", "页面数量", "事件总数"],
    answer: "B",
    explanation: "留存需要固定初始同期群，再统计其中在目标时间窗口内活跃的用户。",
    difficulty: "medium",
    tags: ["留存", "同期群"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q21",
    stageKey: "data-cleaning",
    topicKey: "data-exploration",
    stem: "发现极端值时，最先应该做什么？",
    options: ["立即删除", "检查是否来自输入错误、业务事件或真实长尾", "统一替换为均值", "隐藏图表"],
    answer: "B",
    explanation: "异常来源不同，处理方式不同；不能默认删除所有离群点。",
    difficulty: "medium",
    tags: ["异常值", "探索"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "data-q22",
    stageKey: "data-cleaning",
    topicKey: "data-quality",
    stem: "数据清洗规则应记录影响范围和决策依据。",
    answer: true,
    explanation: "可追溯规则有助于复现、审计和评估清洗对指标与样本的影响。",
    difficulty: "easy",
    tags: ["清洗", "可追溯"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q23",
    stageKey: "data-cleaning",
    topicKey: "data-experiment",
    stem: "A/B 实验中的对照组代表什么？",
    options: ["接受新策略的用户", "保持原策略或基线的用户", "被删除的样本", "只在高价值用户中的样本"],
    answer: "B",
    explanation: "对照组提供基线，用于与实验组比较随机分配后的策略差异。",
    difficulty: "easy",
    tags: ["A/B", "对照组"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q24",
    stageKey: "data-cleaning",
    topicKey: "data-experiment",
    stem: "实验看到显著提升后，仍需要检查什么？",
    options: ["样本偏差、指标口径和实际业务影响", "只检查颜色", "只看平均值", "立即停止观察"],
    answer: "A",
    explanation: "统计显著不等于业务重要，还要检查偏差、口径、副作用和长期影响。",
    difficulty: "medium",
    tags: ["实验", "解释"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q25",
    stageKey: "data-visual-delivery",
    topicKey: "data-chart-choice",
    stem: "比较多个类别的大小时，条形图通常比饼图更适合，因为什么？",
    options: ["更短", "长度更容易精确比较", "颜色更多", "不需要标签"],
    answer: "B",
    explanation: "人眼比较长度比比较扇形角度更准确，分类较多时尤其明显。",
    difficulty: "easy",
    tags: ["可视化", "条形图"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q26",
    stageKey: "data-visual-delivery",
    topicKey: "data-dashboard",
    stem: "仪表板最重要的结构原则是什么？",
    options: ["图表越多越好", "围绕决策路径组织层级和重点", "所有指标同等大小", "只用一种图形"],
    answer: "B",
    explanation: "仪表板应帮助用户按决策顺序找到状态、原因和行动，而不是堆叠指标。",
    difficulty: "easy",
    tags: ["仪表板", "信息架构"],
    sourceKey: "ms-data-science",
  }),
  judgeQuestion({
    key: "data-q27",
    stageKey: "data-visual-delivery",
    topicKey: "data-story",
    stem: "分析结论可以省略数据来源和限制条件，只要表达更有说服力。",
    answer: false,
    explanation: "来源和限制决定结论可信边界，省略会误导决策并让结果不可复现。",
    difficulty: "easy",
    tags: ["结论", "限制"],
    sourceKey: "ms-data-science",
  }),
  singleQuestion({
    key: "data-q28",
    stageKey: "data-visual-delivery",
    topicKey: "data-story",
    stem: "给业务方的行动建议应具备什么特征？",
    options: ["抽象且宏观", "对应具体动作、负责人和预期影响", "只描述算法", "隐藏风险"],
    answer: "B",
    explanation: "可执行建议要说明做什么、谁来做、预期影响、风险和验证方式。",
    difficulty: "medium",
    tags: ["行动建议", "交付"],
    sourceKey: "ms-data-science",
  }),
];

const powerBiExpansion: LearningQuestion[] = [
  singleQuestion({
    key: "pbi-q13",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-connect",
    stem: "DirectQuery 相比 Import 的典型优势是什么？",
    options: ["支持全部 DAX", "更接近数据源实时状态", "查询通常更快", "不需要权限"],
    answer: "B",
    explanation: "DirectQuery 查询上游数据源，新鲜度更高，但性能和部分建模能力受到限制。",
    difficulty: "medium",
    tags: ["DirectQuery", "连接模式"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q14",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-power-query",
    stem: "Power Query 查询折叠的主要价值是什么？",
    options: ["让源系统执行更多转换以提升刷新效率", "改变报表颜色", "自动创建关系", "跳过数据校验"],
    answer: "A",
    explanation: "查询折叠把转换下推到数据源执行，可减少本地处理并提升刷新性能。",
    difficulty: "hard",
    tags: ["查询折叠", "Power Query"],
    sourceKey: "pl300",
  }),
  judgeQuestion({
    key: "pbi-q15",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-power-query",
    stem: "在 Power Query 中提前统一数据类型和字段名称，有助于后续关系与 DAX 稳定。",
    answer: true,
    explanation: "稳定的类型和命名能减少关系错误、刷新失败和度量值结果的歧义。",
    difficulty: "easy",
    tags: ["Power Query", "数据质量"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q16",
    stageKey: "powerbi-ingest",
    topicKey: "powerbi-power-query",
    stem: "刷新失败后，应该优先查看什么？",
    options: ["图表动画", "具体查询步骤、源错误和凭据状态", "报表页数", "主题颜色"],
    answer: "B",
    explanation: "查询步骤和源错误能定位失败发生在连接、权限、类型还是引用阶段。",
    difficulty: "medium",
    tags: ["刷新", "排障"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q17",
    stageKey: "powerbi-model",
    topicKey: "powerbi-star-schema",
    stem: "星型模型中将维度与事实连接的主要目的之一是什么？",
    options: ["减少筛选传播歧义", "增加文本列", "隐藏所有键", "替代数据源"],
    answer: "A",
    explanation: "清晰的一对多关系让筛选从维度传播到事实，降低复杂多路径关系带来的歧义。",
    difficulty: "medium",
    tags: ["星型模型", "关系"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q18",
    stageKey: "powerbi-model",
    topicKey: "powerbi-star-schema",
    stem: "事实表粒度不一致会导致什么问题？",
    options: ["指标难以正确聚合和解释", "字体变小", "关系自动删除", "页面无法保存"],
    answer: "A",
    explanation: "不同粒度事件混在一张事实表会让求和、计数和时间比较产生歧义。",
    difficulty: "medium",
    tags: ["粒度", "事实表"],
    sourceKey: "pl300",
  }),
  judgeQuestion({
    key: "pbi-q19",
    stageKey: "powerbi-model",
    topicKey: "powerbi-date-table",
    stem: "日期表应连续并独立于事实表，才能稳定支持时间智能。",
    answer: true,
    explanation: "连续、标记为日期表并建立一对多关系的日期维度是时间智能的稳定基础。",
    difficulty: "medium",
    tags: ["日期表", "时间智能"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q20",
    stageKey: "powerbi-model",
    topicKey: "powerbi-relationships",
    stem: "多对多关系增加复杂性时，常见处理方式是什么？",
    options: ["使用桥接表并明确筛选路径", "所有关系都改双向", "删除维度表", "把键改成文本"],
    answer: "A",
    explanation: "桥接表能显式表达多对多映射，但必须验证筛选传播和指标唯一性。",
    difficulty: "hard",
    tags: ["多对多", "桥接表"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q21",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-dax-basics",
    stem: "DAX 中 VAR 的一个重要作用是什么？",
    options: ["保存一次计算结果并提升可读性", "自动创建关系", "修改数据源", "替代所有筛选器"],
    answer: "A",
    explanation: "变量记录计算时上下文中的结果，避免重复表达式并让推导更清晰。",
    difficulty: "medium",
    tags: ["DAX", "VAR"],
    sourceKey: "pl300",
  }),
  judgeQuestion({
    key: "pbi-q22",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-calculate",
    stem: "KEEPFILTERS 会影响 CALCULATE 中筛选器对已有筛选上下文的处理方式。",
    answer: true,
    explanation: "KEEPFILTERS 保留已有筛选并与新筛选交集，而不是默认覆盖。",
    difficulty: "hard",
    tags: ["CALCULATE", "KEEPFILTERS"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q23",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-calculate",
    stem: "验证占比度量值最直接的方法是什么？",
    options: ["手工核对一个筛选组合下的分子分母", "只看图表颜色", "增加页面", "删除日期表"],
    answer: "A",
    explanation: "选取一个具体筛选上下文，手工计算分子和分母，可以快速发现筛选覆盖或关系错误。",
    difficulty: "medium",
    tags: ["占比", "验证"],
    sourceKey: "pl300",
  }),
  judgeQuestion({
    key: "pbi-q24",
    stageKey: "powerbi-dax",
    topicKey: "powerbi-time-intelligence",
    stem: "同一时间智能度量值在正确的日期表和错误日期表下可能得到完全不同的结果。",
    answer: true,
    explanation: "时间智能依赖日期关系、连续性和当前筛选，日期维度错误会直接改变结果。",
    difficulty: "medium",
    tags: ["时间智能", "日期表"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q25",
    stageKey: "powerbi-report",
    topicKey: "powerbi-report-design",
    stem: "报表页面最重要指标通常放在哪里？",
    options: ["视觉层级最高的位置", "页面最底部隐藏起来", "多个重复位置", "工具提示里"],
    answer: "A",
    explanation: "重要指标应在首要视觉区域形成明确焦点，减少用户寻找成本。",
    difficulty: "easy",
    tags: ["报表设计", "层级"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q26",
    stageKey: "powerbi-report",
    topicKey: "powerbi-report-design",
    stem: "钻取交互应保证什么？",
    options: ["用户能明确返回上一级", "隐藏当前筛选", "强制放大字体", "自动改变业务口径"],
    answer: "A",
    explanation: "可预测的钻取需要清晰上下文和返回路径，避免用户迷失在层级中。",
    difficulty: "medium",
    tags: ["钻取", "交互"],
    sourceKey: "pl300",
  }),
  judgeQuestion({
    key: "pbi-q27",
    stageKey: "powerbi-report",
    topicKey: "powerbi-security-service",
    stem: "RLS 应由服务端模型统一执行，不能只依赖前端隐藏图表。",
    answer: true,
    explanation: "视觉隐藏不能阻止数据访问，权限必须在模型和数据源层执行。",
    difficulty: "medium",
    tags: ["RLS", "安全"],
    sourceKey: "pl300",
  }),
  singleQuestion({
    key: "pbi-q28",
    stageKey: "powerbi-report",
    topicKey: "powerbi-security-service",
    stem: "报表发布上线后仍需要持续监控什么？",
    options: ["刷新状态、权限和使用反馈", "页面背景", "鼠标大小", "文件名长度"],
    answer: "A",
    explanation: "刷新失败、权限错误和低使用路径都会影响业务价值，需要持续运维和迭代。",
    difficulty: "easy",
    tags: ["发布", "运维"],
    sourceKey: "pl300",
  }),
];

export const learningQuestionExpansions: Record<string, LearningQuestion[]> = {
  python: pythonExpansion,
  java: javaExpansion,
  "data-analysis": dataAnalysisExpansion,
  "power-bi": powerBiExpansion,
};

export function expandLearningTrack(track: LearningTrack): LearningTrack {
  const topicAdditions = topicQuestionPacks.filter((question) =>
    track.stages.some((stage) => stage.key === question.stageKey)
  );
  const withLessons: LearningTrack = {
    ...track,
    stages: track.stages.map((stage) => ({
      ...stage,
      lesson: stage.lesson ?? stageLessons[stage.key],
      topics: stage.topics.map((topic) => ({
        ...topic,
        lesson: topic.lesson ?? topicLessons[topic.key],
      })),
    })),
  };
  const additions = learningQuestionExpansions[track.slug];
  const allAdditions = [...topicAdditions, ...(additions ?? [])];
  if (allAdditions.length === 0) return withLessons;

  return {
    ...withLessons,
    stages: withLessons.stages.map((stage) => ({
      ...stage,
      questionKeys: [
        ...stage.questionKeys,
        ...allAdditions.filter((question) => question.stageKey === stage.key).map((question) => question.key),
      ],
    })),
    questions: [...withLessons.questions, ...allAdditions],
  };
}
