-- ============================================================================
-- 014 种子数据：skill_taxonomy 初始技能库（基于招花实际岗位 tags 抽取）
-- 幂等：ON CONFLICT (name) DO NOTHING，可重复执行
-- ============================================================================
INSERT INTO skill_taxonomy (name, aliases, category) VALUES
  ('python', '["Python","Python3"]', 'backend'),
  ('java', '["Java","JavaSE"]', 'backend'),
  ('go', '["Go","Golang"]', 'backend'),
  ('nodejs', '["Node.js","Node","NodeJS"]', 'backend'),
  ('php', '["PHP"]', 'backend'),
  ('c++', '["C/C++","C++","C"]', 'backend'),
  ('rust', '["Rust"]', 'backend'),
  ('vue', '["Vue","Vue2","Vue3"]', 'frontend'),
  ('react', '["React","React Native"]', 'frontend'),
  ('javascript', '["JavaScript","JS","ES6"]', 'frontend'),
  ('typescript', '["TypeScript","TS"]', 'frontend'),
  ('css', '["CSS","CSS3","SCSS","Sass","Less"]', 'frontend'),
  ('html', '["HTML","HTML5"]', 'frontend'),
  ('webgl', '["WebGL","Three.js","ThreeJS","Echarts","ECharts"]', 'frontend'),
  ('vite', '["Vite"]', 'frontend'),
  ('bootstrap', '["Bootstrap","ElementUI","Element-UI"]', 'frontend'),
  ('mysql', '["MySQL"]', 'data'),
  ('postgresql', '["PostgreSQL","Postgres","PG"]', 'data'),
  ('sql', '["SQL","Sql"]', 'data'),
  ('redis', '["Redis","Redis 缓存"]', 'data'),
  ('mongodb', '["MongoDB","Mongo"]', 'data'),
  ('hive', '["Hive"]', 'data'),
  ('spark', '["Spark","SparkSQL"]', 'data'),
  ('flink', '["Flink"]', 'data'),
  ('kafka', '["Kafka"]', 'data'),
  ('tableau', '["Tableau","PowerBI","Power BI"]', 'data'),
  ('etl', '["ETL","Kettle","数据仓库"]', 'data'),
  ('linux', '["Linux","Linux 运维"]', 'ops'),
  ('docker', '["Docker"]', 'ops'),
  ('k8s', '["K8s","Kubernetes"]', 'ops'),
  ('terraform', '["Terraform"]', 'ops'),
  ('cicd', '["CI/CD","CI","CD","Jenkins","GitLab CI"]', 'ops'),
  ('shell', '["Shell","Shell 脚本"]', 'ops'),
  ('nginx', '["Nginx"]', 'ops'),
  ('cloud', '["云计算","腾讯云","阿里云","AWS"]', 'cloud'),
  ('nlp', '["NLP","自然语言处理"]', 'ai'),
  ('pytorch', '["PyTorch","PyTorch"]', 'ai'),
  ('tensorflow', '["TensorFlow","TF"]', 'ai'),
  ('llm', '["LLM","大模型","Agent","RAG","Prompt"]', 'ai'),
  ('rtos', '["RTOS","嵌入式"]', 'ai'),
  ('stm32', '["STM32","单片机"]', 'ai'),
  ('networking', '["网络","网络工程","HCIP","CCNP"]', 'network'),
  ('security', '["安全","等保","CISP","网络安全"]', 'security'),
  ('automation_test', '["自动化测试","Selenium","pytest"]', 'soft'),
  ('product', '["PRD","AI产品","产品"]', 'soft'),
  ('softskills', '["TOC","沟通","项目管理"]', 'soft')
ON CONFLICT (name) DO NOTHING;
